//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.4016
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// Ce code source a été automatiquement généré par xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class myanimelist
{

    private myanimelistMyinfo myinfoField;

    private myanimelistAnime[] animeField;

    /// <remarks/>
    public myanimelistMyinfo myinfo
    {
        get
        {
            return this.myinfoField;
        }
        set
        {
            this.myinfoField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("anime")]
    public myanimelistAnime[] anime
    {
        get
        {
            return this.animeField;
        }
        set
        {
            this.animeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class myanimelistMyinfo
{

    private int user_idField;

    private string user_nameField;

    private int user_watchingField;

    private int user_completedField;

    private int user_onholdField;

    private int user_droppedField;

    private int user_plantowatchField;

    private decimal user_days_spent_watchingField;

    /// <remarks/>
    public int user_id
    {
        get
        {
            return this.user_idField;
        }
        set
        {
            this.user_idField = value;
        }
    }

    /// <remarks/>
    public string user_name
    {
        get
        {
            return this.user_nameField;
        }
        set
        {
            this.user_nameField = value;
        }
    }

    /// <remarks/>
    public int user_watching
    {
        get
        {
            return this.user_watchingField;
        }
        set
        {
            this.user_watchingField = value;
        }
    }

    /// <remarks/>
    public int user_completed
    {
        get
        {
            return this.user_completedField;
        }
        set
        {
            this.user_completedField = value;
        }
    }

    /// <remarks/>
    public int user_onhold
    {
        get
        {
            return this.user_onholdField;
        }
        set
        {
            this.user_onholdField = value;
        }
    }

    /// <remarks/>
    public int user_dropped
    {
        get
        {
            return this.user_droppedField;
        }
        set
        {
            this.user_droppedField = value;
        }
    }

    /// <remarks/>
    public int user_plantowatch
    {
        get
        {
            return this.user_plantowatchField;
        }
        set
        {
            this.user_plantowatchField = value;
        }
    }

    /// <remarks/>
    public decimal user_days_spent_watching
    {
        get
        {
            return this.user_days_spent_watchingField;
        }
        set
        {
            this.user_days_spent_watchingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class myanimelistAnime
{

    private int series_animedb_idField;

    private string series_titleField;

    private string series_synonymsField;

    private int series_typeField;

    private int series_episodesField;

    private int series_statusField;

    private string series_startField;

    private string series_endField;

    private string series_imageField;

    private int my_idField;

    private int my_watched_episodesField;

    private string my_start_dateField;

    private string my_finish_dateField;

    private int my_scoreField;

    private int my_statusField;

    private string my_rewatchingField;

    private int my_rewatching_epField;

    private int my_last_updatedField;

    private object my_tagsField;

    /// <remarks/>
    public int series_animedb_id
    {
        get
        {
            return this.series_animedb_idField;
        }
        set
        {
            this.series_animedb_idField = value;
        }
    }

    /// <remarks/>
    public string series_title
    {
        get
        {
            return this.series_titleField;
        }
        set
        {
            this.series_titleField = value;
        }
    }

    /// <remarks/>
    public string series_synonyms
    {
        get
        {
            return this.series_synonymsField;
        }
        set
        {
            this.series_synonymsField = value;
        }
    }

    /// <remarks/>
    public int series_type
    {
        get
        {
            return this.series_typeField;
        }
        set
        {
            this.series_typeField = value;
        }
    }

    /// <remarks/>
    public int series_episodes
    {
        get
        {
            return this.series_episodesField;
        }
        set
        {
            this.series_episodesField = value;
        }
    }

    /// <remarks/>
    public int series_status
    {
        get
        {
            return this.series_statusField;
        }
        set
        {
            this.series_statusField = value;
        }
    }

    /// <remarks/>
    public string series_start
    {
        get
        {
            return this.series_startField;
        }
        set
        {
            this.series_startField = value;
        }
    }

    /// <remarks/>
    public string series_end
    {
        get
        {
            return this.series_endField;
        }
        set
        {
            this.series_endField = value;
        }
    }

    /// <remarks/>
    public string series_image
    {
        get
        {
            return this.series_imageField;
        }
        set
        {
            this.series_imageField = value;
        }
    }

    /// <remarks/>
    public int my_id
    {
        get
        {
            return this.my_idField;
        }
        set
        {
            this.my_idField = value;
        }
    }

    /// <remarks/>
    public int my_watched_episodes
    {
        get
        {
            return this.my_watched_episodesField;
        }
        set
        {
            this.my_watched_episodesField = value;
        }
    }

    /// <remarks/>
    public string my_start_date
    {
        get
        {
            return this.my_start_dateField;
        }
        set
        {
            this.my_start_dateField = value;
        }
    }

    /// <remarks/>
    public string my_finish_date
    {
        get
        {
            return this.my_finish_dateField;
        }
        set
        {
            this.my_finish_dateField = value;
        }
    }

    /// <remarks/>
    public int my_score
    {
        get
        {
            return this.my_scoreField;
        }
        set
        {
            this.my_scoreField = value;
        }
    }

    /// <remarks/>
    public int my_status
    {
        get
        {
            return this.my_statusField;
        }
        set
        {
            this.my_statusField = value;
        }
    }

    /// <remarks/>
    public string my_rewatching
    {
        get
        {
            return this.my_rewatchingField;
        }
        set
        {
            this.my_rewatchingField = value;
        }
    }

    /// <remarks/>
    public int my_rewatching_ep
    {
        get
        {
            return this.my_rewatching_epField;
        }
        set
        {
            this.my_rewatching_epField = value;
        }
    }

    /// <remarks/>
    public int my_last_updated
    {
        get
        {
            return this.my_last_updatedField;
        }
        set
        {
            this.my_last_updatedField = value;
        }
    }

    /// <remarks/>
    public object my_tags
    {
        get
        {
            return this.my_tagsField;
        }
        set
        {
            this.my_tagsField = value;
        }
    }
}
