using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Text;

namespace Shoko.BuildTools;

/// <summary>
///   Generates C# assembly metadata files for plugin builds and reads the
///   metadata back from compiled assemblies.
/// </summary>
internal static class AssemblyInfoGenerator
{
    /// <summary>
    ///   Assembly metadata key for the serialized dependency string.
    /// </summary>
    private const string DependenciesKey = "PackageDependencies";

    /// <summary>
    ///   Write a generated .cs file with assembly-level metadata attributes.
    /// </summary>
    public static void WriteAssemblyInfo(
        string path,
        string runtimeIdentifier,
        string releaseDate,
        string releaseTag,
        string sourceRevision,
        IReadOnlyList<DependencyInfo> dependencies,
        IReadOnlyList<string>? tags,
        Guid? pluginId = null,
        string? pluginName = null,
        string? pluginDescription = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file is generated by Shoko.BuildTools. Do not edit manually.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(runtimeIdentifier))
            sb.AppendLine($"[assembly: AssemblyMetadata(\"RuntimeIdentifier\", \"{EscapeAttrValue(runtimeIdentifier)}\")]");

        if (!string.IsNullOrEmpty(releaseDate))
            sb.AppendLine($"[assembly: AssemblyMetadata(\"ReleaseDate\", \"{EscapeAttrValue(releaseDate)}\")]");

        if (!string.IsNullOrEmpty(releaseTag))
            sb.AppendLine($"[assembly: AssemblyMetadata(\"ReleaseTag\", \"{EscapeAttrValue(releaseTag)}\")]");

        if (!string.IsNullOrEmpty(sourceRevision))
            sb.AppendLine($"[assembly: AssemblyMetadata(\"SourceRevision\", \"{EscapeAttrValue(sourceRevision)}\")]");

        // Inject tags from manifest as a single comma-separated PackageTags
        // attribute, matching the format the server reads at runtime.
        if (tags is { Count: > 0 })
        {
            var filtered = tags.Where(t => !string.IsNullOrEmpty(t)).ToList();
            if (filtered.Count > 0)
                sb.AppendLine($"[assembly: AssemblyMetadata(\"PackageTags\", \"{EscapeAttrValue(string.Join(",", filtered))}\")]");
        }

        // Inject plugin identity from manifest (so the server can read it
        // without instantiating the plugin type)
        if (pluginId.HasValue)
            sb.AppendLine($"[assembly: AssemblyMetadata(\"PackageID\", \"{pluginId.Value:D}\")]");

        if (!string.IsNullOrEmpty(pluginName))
            sb.AppendLine($"[assembly: AssemblyMetadata(\"PackageName\", \"{EscapeAttrValue(pluginName)}\")]");

        if (!string.IsNullOrEmpty(pluginDescription))
            sb.AppendLine($"[assembly: AssemblyMetadata(\"PackageOverview\", \"{EscapeAttrValue(pluginDescription)}\")]");

        // Inject dependencies as a single serialized string:
        //   guid:versionRange[:true][,next]*
        if (dependencies.Count > 0)
        {
            var serialized = string.Join(",",
                dependencies.Select(d =>
                {
                    var s = $"{d.PluginID:D}:{d.VersionRange}";
                    if (d.IsOptional) s += ":true";
                    return s;
                }));
            sb.AppendLine($"[assembly: AssemblyMetadata(\"{DependenciesKey}\", \"{EscapeAttrValue(serialized)}\")]");
        }

        File.WriteAllText(path, sb.ToString());
    }

    /// <summary>
    ///   The full name of the attribute the build stamps its metadata with.
    /// </summary>
    private const string MetadataAttributeName = "System.Reflection.AssemblyMetadataAttribute";

    /// <summary>
    ///   Read embedded metadata from a compiled plugin DLL, out of its
    ///   metadata tables. The assembly is never loaded, so it need not be
    ///   loadable into this process.
    /// </summary>
    public static AssemblyMetadata ReadAssemblyMetadata(string dllPath)
    {
        using var stream = File.OpenRead(dllPath);
        using var peReader = new PEReader(stream);

        if (!peReader.HasMetadata)
            throw new BadImageFormatException($"'{dllPath}' carries no managed metadata.");

        var reader = peReader.GetMetadataReader();
        var assemblyDefinition = reader.GetAssemblyDefinition();

        var version = assemblyDefinition.Version;
        var abstractionVersion = (Version?)null;
        foreach (var handle in reader.AssemblyReferences)
        {
            var reference = reader.GetAssemblyReference(handle);
            if (reader.GetString(reference.Name) is "Shoko.Abstractions")
            {
                abstractionVersion = reference.Version;
                break;
            }
        }

        var metadata = ReadMetadataAttributes(reader, assemblyDefinition)
            .ToLookup(pair => pair.Key, pair => pair.Value, StringComparer.OrdinalIgnoreCase);

        var dependencies = new List<DependencyInfo>();

        // Try the serialized format first (single attribute with comma-separated deps)
        if (metadata[DependenciesKey].FirstOrDefault() is { } serialized && !string.IsNullOrEmpty(serialized))
        {
            foreach (var segment in serialized.Split(','))
            {
                var parts = segment.Split(':');
                if (parts.Length >= 2 && Guid.TryParse(parts[0], out var pluginId))
                {
                    dependencies.Add(new DependencyInfo
                    {
                        PluginID = pluginId,
                        VersionRange = parts[1],
                        IsOptional = parts.Length > 2 && (parts[2] == "true" || parts[2] == "True"),
                    });
                }
            }
        }

        return new AssemblyMetadata
        {
            Version = version.Revision > 0
                ? new Version(version.Major, version.Minor, version.Build, version.Revision)
                : new Version(version.Major, version.Minor, version.Build),
            AbstractionVersion = abstractionVersion is not null ? new Version(abstractionVersion.Major, abstractionVersion.Minor, abstractionVersion.Build) : new Version(0, 0, 0),
            Dependencies = dependencies,
            Tags = metadata["Tag"].ToList(),
            // Every value, not the first: the disagreement check needs them all.
            RuntimeIdentifiers = metadata["RuntimeIdentifier"].ToList(),
        };
    }

    /// <summary>
    ///   Every <c>[assembly: AssemblyMetadata(key, value)]</c> pair on the
    ///   assembly, matched by the name of the attribute constructor's
    ///   declaring type rather than by resolving it.
    /// </summary>
    private static IEnumerable<(string Key, string Value)> ReadMetadataAttributes(
        MetadataReader reader,
        AssemblyDefinition assemblyDefinition)
    {
        foreach (var handle in assemblyDefinition.GetCustomAttributes())
        {
            var attribute = reader.GetCustomAttribute(handle);
            if (GetAttributeTypeName(reader, attribute) != MetadataAttributeName)
                continue;

            CustomAttributeValue<string> decoded;
            try
            {
                decoded = attribute.DecodeValue(StringNamingTypeProvider.Instance);
            }
            catch (BadImageFormatException)
            {
                continue;
            }

            if (decoded.FixedArguments.Length < 2)
                continue;

            if (decoded.FixedArguments[0].Value is string key &&
                decoded.FixedArguments[1].Value is string value)
                yield return (key, value);
        }
    }

    /// <summary>
    ///   The namespace-qualified name of the type a custom attribute's
    ///   constructor belongs to, or <c>null</c> when it is a construction
    ///   we do not read (a generic instantiation, say).
    /// </summary>
    private static string? GetAttributeTypeName(MetadataReader reader, CustomAttribute attribute)
    {
        switch (attribute.Constructor.Kind)
        {
            case HandleKind.MemberReference:
            {
                var member = reader.GetMemberReference((MemberReferenceHandle)attribute.Constructor);
                if (member.Parent.Kind is not HandleKind.TypeReference)
                    return null;

                var typeReference = reader.GetTypeReference((TypeReferenceHandle)member.Parent);
                return Qualify(reader.GetString(typeReference.Namespace), reader.GetString(typeReference.Name));
            }

            case HandleKind.MethodDefinition:
            {
                var method = reader.GetMethodDefinition((MethodDefinitionHandle)attribute.Constructor);
                var typeDefinition = reader.GetTypeDefinition(method.GetDeclaringType());
                return Qualify(reader.GetString(typeDefinition.Namespace), reader.GetString(typeDefinition.Name));
            }

            default:
                return null;
        }

        static string Qualify(string @namespace, string name)
            => string.IsNullOrEmpty(@namespace) ? name : $"{@namespace}.{name}";
    }

    private static string EscapeAttrValue(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    /// <summary>
    ///   Decodes a custom-attribute blob by naming types rather than
    ///   resolving them, which is all a string-argument attribute needs.
    /// </summary>
    private sealed class StringNamingTypeProvider : ICustomAttributeTypeProvider<string>
    {
        public static readonly StringNamingTypeProvider Instance = new();

        public string GetPrimitiveType(PrimitiveTypeCode typeCode) => typeCode.ToString();

        public string GetSystemType() => "System.Type";

        public string GetSZArrayType(string elementType) => elementType + "[]";

        public string GetTypeFromDefinition(MetadataReader reader, TypeDefinitionHandle handle, byte rawTypeKind)
        {
            var definition = reader.GetTypeDefinition(handle);
            var @namespace = reader.GetString(definition.Namespace);
            var name = reader.GetString(definition.Name);
            return string.IsNullOrEmpty(@namespace) ? name : $"{@namespace}.{name}";
        }

        public string GetTypeFromReference(MetadataReader reader, TypeReferenceHandle handle, byte rawTypeKind)
        {
            var reference = reader.GetTypeReference(handle);
            var @namespace = reader.GetString(reference.Namespace);
            var name = reader.GetString(reference.Name);
            return string.IsNullOrEmpty(@namespace) ? name : $"{@namespace}.{name}";
        }

        public string GetTypeFromSerializedName(string name) => name;

        public PrimitiveTypeCode GetUnderlyingEnumType(string type) => PrimitiveTypeCode.Int32;

        public bool IsSystemType(string type) => type is "System.Type";
    }
}

/// <summary>
///   Metadata read from a compiled plugin assembly.
/// </summary>
internal sealed class AssemblyMetadata
{
    public Version Version { get; init; } = new(0, 0, 0);
    public Version AbstractionVersion { get; init; } = new(0, 0, 0);
    public IReadOnlyList<DependencyInfo> Dependencies { get; init; } = [];
    public IReadOnlyList<string> Tags { get; init; } = [];

    /// <summary>
    ///   Every <c>RuntimeIdentifier</c> the assembly is stamped with. More
    ///   than one means the build tools disagreed about what was built.
    /// </summary>
    public IReadOnlyList<string> RuntimeIdentifiers { get; init; } = [];
}

/// <summary>
///   A dependency declaration for embedding into manifest and assembly.
/// </summary>
internal sealed class DependencyInfo
{
    public Guid PluginID { get; init; }
    public string VersionRange { get; init; } = ">=0.0.0";
    public bool IsOptional { get; init; }
}
