using System;
using System.Linq;
using Shoko.Plugin.Abstractions.DataModels;

namespace Shoko.Plugin.Abstractions.Extensions;

public static class LanguageExtensions
{
    public static TitleLanguage GetTitleLanguage(this string lang)
    {
        return lang.ToUpper() switch
        {
            "EN" or "ENG" => TitleLanguage.English,
            "X-JAT" => TitleLanguage.Romaji,
            "JA" or "JPN" => TitleLanguage.Japanese,
            "AR" or "ARA" => TitleLanguage.Arabic,
            "BD" or "BAN" => TitleLanguage.Bangladeshi,
            "BG" or "BUL" => TitleLanguage.Bulgarian,
            "CA" => TitleLanguage.FrenchCanadian,
            "CS" or "CES" or "CZ" => TitleLanguage.Czech,
            "DA" or "DAN" or "DK" => TitleLanguage.Danish,
            "DE" or "DEU" => TitleLanguage.German,
            "EL" or "ELL" or "GR" => TitleLanguage.Greek,
            "ES" or "SPA" => TitleLanguage.Spanish,
            "ET" or "EST" => TitleLanguage.Estonian,
            "FI" or "FIN" => TitleLanguage.Finnish,
            "FR" or "FRA" or "CA" => TitleLanguage.French,
            "GL" or "GLG" => TitleLanguage.Galician,
            "HE" or "HEB" or "IL" => TitleLanguage.Hebrew,
            "HU" or "HUN" => TitleLanguage.Hungarian,
            "IT" or "ITA" => TitleLanguage.Italian,
            "KO" or "KOR" => TitleLanguage.Korean,
            "LT" or "LIT" => TitleLanguage.Lithuanian,
            "MN" or "MON" => TitleLanguage.Mongolian,
            "MS" or "MSA" or "MY" => TitleLanguage.Malaysian,
            "NL" or "NLD" => TitleLanguage.Dutch,
            "NO" or "NOR" => TitleLanguage.Norwegian,
            "PL" or "POL" => TitleLanguage.Polish,
            "PT" or "POR" => TitleLanguage.Portuguese,
            "PT-BR" => TitleLanguage.BrazilianPortuguese,
            "RO" or "RON" => TitleLanguage.Romanian,
            "RU" or "RUS" => TitleLanguage.Russian,
            "SK" or "SLK" => TitleLanguage.Slovak,
            "SL" or "SLV" => TitleLanguage.Slovenian,
            "SR" or "SRP" => TitleLanguage.Serbian,
            "SV" or "SWE" or "SE" => TitleLanguage.Swedish,
            "TH" or "THA" => TitleLanguage.Thai,
            "TR" or "TUR" => TitleLanguage.Turkish,
            "UK" or "UKR" or "UA" => TitleLanguage.Ukrainian,
            "VI" or "VIE" => TitleLanguage.Vietnamese,
            "ZH" or "ZHO" => TitleLanguage.Chinese,
            "X-ZHT" => TitleLanguage.Pinyin,
            "ZH-HANS" => TitleLanguage.ChineseSimplified,
            "ZH-HANT" => TitleLanguage.ChineseTraditional,
            "AF" or "AFR" => TitleLanguage.Afrikaans,
            "SQ" or "SQI" => TitleLanguage.Albanian,
            "AM" or "AMH" => TitleLanguage.Amharic,
            "HY" or "HYE" => TitleLanguage.Armenian,
            "AZ" or "AZE" => TitleLanguage.Azerbaijani,
            "EU" or "EUS" => TitleLanguage.Basque,
            "BE" or "BEL" => TitleLanguage.Belarusian,
            "BN" or "BEN" => TitleLanguage.Bengali,
            "BS" or "BOS" => TitleLanguage.Bosnian,
            "CA" or "CAT" => TitleLanguage.Catalan,
            "NY" or "NYA" => TitleLanguage.Chichewa,
            "CO" or "COS" => TitleLanguage.Corsican,
            "HR" or "HRV" => TitleLanguage.Croatian,
            "DV" or "DIV" => TitleLanguage.Divehi,
            "EO" or "EPO" => TitleLanguage.Esperanto,
            "FJ" or "FIJ" => TitleLanguage.Fijian,
            "KA" or "KAT" => TitleLanguage.Georgian,
            "GU" or "GUJ" => TitleLanguage.Gujarati,
            "HT" or "HAT" => TitleLanguage.HaitianCreole,
            "HA" or "HAU" => TitleLanguage.Hausa,
            "IS" or "ISL" => TitleLanguage.Icelandic,
            "IG" or "IBO" => TitleLanguage.Igbo,
            "ID" or "IND" => TitleLanguage.Indonesian,
            "GA" or "GLE" => TitleLanguage.Irish,
            "JV" or "JAV" => TitleLanguage.Javanese,
            "KN" or "KAN" => TitleLanguage.Kannada,
            "KK" or "KAZ" => TitleLanguage.Kazakh,
            "KM" or "KHM" => TitleLanguage.Khmer,
            "KU" or "KUR" => TitleLanguage.Kurdish,
            "KY" or "KIR" => TitleLanguage.Kyrgyz,
            "LO" or "LAO" => TitleLanguage.Lao,
            "LA" or "LAT" => TitleLanguage.Latin,
            "LV" or "LAV" => TitleLanguage.Latvian,
            "LB" or "LUX" => TitleLanguage.Luxembourgish,
            "MK" or "MKD" => TitleLanguage.Macedonian,
            "MG" or "MLG" => TitleLanguage.Malagasy,
            "ML" or "MAL" => TitleLanguage.Malayalam,
            "MT" or "MLT" => TitleLanguage.Maltese,
            "MI" or "MRI" => TitleLanguage.Maori,
            "MR" or "MAR" => TitleLanguage.Marathi,
            "MY" or "MYA" => TitleLanguage.MyanmarBurmese,
            "NE" or "NEP" => TitleLanguage.Nepali,
            "OR" or "ORI" => TitleLanguage.Oriya,
            "PS" or "PUS" => TitleLanguage.Pashto,
            "FA" or "FAS" => TitleLanguage.Persian,
            "PA" or "PAN" => TitleLanguage.Punjabi,
            "QU" or "QUE" => TitleLanguage.Quechua,
            "SM" or "SMO" => TitleLanguage.Samoan,
            "GD" or "GLA" => TitleLanguage.ScotsGaelic,
            "ST" or "SOT" => TitleLanguage.Sesotho,
            "SN" or "SNA" => TitleLanguage.Shona,
            "SD" or "SND" => TitleLanguage.Sindhi,
            "SI" or "SIN" => TitleLanguage.Sinhala,
            "SO" or "SOM" => TitleLanguage.Somali,
            "SW" or "SWA" => TitleLanguage.Swahili,
            "TG" or "TGK" => TitleLanguage.Tajik,
            "TA" or "TAM" => TitleLanguage.Tamil,
            "TT" or "TAT" => TitleLanguage.Tatar,
            "TE" or "TEL" => TitleLanguage.Telugu,
            "TK" or "TUK" => TitleLanguage.Turkmen,
            "UG" or "UIG" => TitleLanguage.Uighur,
            "UZ" or "UZB" => TitleLanguage.Uzbek,
            "CY" or "CYM" => TitleLanguage.Welsh,
            "XH" or "XHO" => TitleLanguage.Xhosa,
            "YI" or "YID" => TitleLanguage.Yiddish,
            "YO" or "YOR" => TitleLanguage.Yoruba,
            "ZU" or "ZUL" => TitleLanguage.Zulu,
            "UNK" => TitleLanguage.Unknown,
            _ => TitleLanguage.Unknown,
        };
    }
    
    public static string GetDescription(this TitleLanguage lang)
    {
        return lang switch
        {
            TitleLanguage.Romaji => "Japanese (romanji/x-jat)",
            TitleLanguage.Japanese => "Japanese (kanji)",
            TitleLanguage.Bangladeshi => "Bangladesh",
            TitleLanguage.FrenchCanadian => "Canadian-French",
            TitleLanguage.BrazilianPortuguese => "Brazilian Portuguese",
            TitleLanguage.Chinese => "Chinese (any)",
            TitleLanguage.ChineseSimplified => "Chinese (simplified)",
            TitleLanguage.ChineseTraditional => "Chinese (traditional)",
            TitleLanguage.Pinyin => "Chinese (pinyin/x-zhn)",
            _ => lang.ToString(),
        };
    }

    public static string GetString(this TitleLanguage lang)
    {
        return lang switch
        {
            TitleLanguage.English => "en",
            TitleLanguage.Romaji => "x-jat",
            TitleLanguage.Japanese => "ja",
            TitleLanguage.Arabic => "ar",
            TitleLanguage.Bangladeshi => "bd",
            TitleLanguage.Bulgarian => "bg",
            TitleLanguage.FrenchCanadian => "ca",
            TitleLanguage.Czech => "cz",
            TitleLanguage.Danish => "da",
            TitleLanguage.German => "de",
            TitleLanguage.Greek => "gr",
            TitleLanguage.Spanish => "es",
            TitleLanguage.Estonian => "et",
            TitleLanguage.Finnish => "fi",
            TitleLanguage.French => "fr",
            TitleLanguage.Galician => "gl",
            TitleLanguage.Hebrew => "he",
            TitleLanguage.Hungarian => "hu",
            TitleLanguage.Italian => "it",
            TitleLanguage.Korean => "ko",
            TitleLanguage.Lithuanian => "lt",
            TitleLanguage.Mongolian => "mn",
            TitleLanguage.Malaysian => "ms",
            TitleLanguage.Dutch => "ml",
            TitleLanguage.Norwegian => "no",
            TitleLanguage.Polish => "pl",
            TitleLanguage.Portuguese => "pt",
            TitleLanguage.BrazilianPortuguese => "pt-br",
            TitleLanguage.Romanian => "ro",
            TitleLanguage.Russian => "ru",
            TitleLanguage.Slovak => "sk",
            TitleLanguage.Slovenian => "sl",
            TitleLanguage.Serbian => "sr",
            TitleLanguage.Swedish => "sv",
            TitleLanguage.Thai => "th",
            TitleLanguage.Turkish => "tr",
            TitleLanguage.Ukrainian => "uk",
            TitleLanguage.Vietnamese => "vi",
            TitleLanguage.Chinese => "zh",
            TitleLanguage.Pinyin => "x-zht",
            TitleLanguage.ChineseSimplified => "zh-hans",
            TitleLanguage.ChineseTraditional => "zh-hant",
            TitleLanguage.Afrikaans => "af",
            TitleLanguage.Albanian => "sq",
            TitleLanguage.Amharic => "am",
            TitleLanguage.Armenian => "hy",
            TitleLanguage.Azerbaijani => "az",
            TitleLanguage.Basque => "eu",
            TitleLanguage.Belarusian => "be",
            TitleLanguage.Bengali => "bn",
            TitleLanguage.Bosnian => "bs",
            TitleLanguage.Catalan => "ca",
            TitleLanguage.Chichewa => "ny",
            TitleLanguage.Corsican => "co",
            TitleLanguage.Croatian => "hr",
            TitleLanguage.Divehi => "dv",
            TitleLanguage.Esperanto => "eo",
            TitleLanguage.Fijian => "fj",
            TitleLanguage.Georgian => "ka",
            TitleLanguage.Gujarati => "gu",
            TitleLanguage.HaitianCreole => "ht",
            TitleLanguage.Hausa => "ha",
            TitleLanguage.Icelandic => "is",
            TitleLanguage.Igbo => "ig",
            TitleLanguage.Indonesian => "id",
            TitleLanguage.Irish => "ga",
            TitleLanguage.Javanese => "jv",
            TitleLanguage.Kannada => "kn",
            TitleLanguage.Kazakh => "kk",
            TitleLanguage.Khmer => "km",
            TitleLanguage.Kurdish => "ku",
            TitleLanguage.Kyrgyz => "ky",
            TitleLanguage.Lao => "lo",
            TitleLanguage.Latin => "la",
            TitleLanguage.Latvian => "lv",
            TitleLanguage.Luxembourgish => "lb",
            TitleLanguage.Macedonian => "mk",
            TitleLanguage.Malagasy => "mg",
            TitleLanguage.Malayalam => "ml",
            TitleLanguage.Maltese => "mt",
            TitleLanguage.Maori => "mi",
            TitleLanguage.Marathi => "mr",
            TitleLanguage.MyanmarBurmese => "my",
            TitleLanguage.Nepali => "ne",
            TitleLanguage.Oriya => "or",
            TitleLanguage.Pashto => "ps",
            TitleLanguage.Persian => "fa",
            TitleLanguage.Punjabi => "pa",
            TitleLanguage.Quechua => "qu",
            TitleLanguage.Samoan => "sm",
            TitleLanguage.ScotsGaelic => "gd",
            TitleLanguage.Sesotho => "st",
            TitleLanguage.Shona => "sn",
            TitleLanguage.Sindhi => "sd",
            TitleLanguage.Sinhala => "si",
            TitleLanguage.Somali => "so",
            TitleLanguage.Swahili => "sw",
            TitleLanguage.Tajik => "tg",
            TitleLanguage.Tamil => "ta",
            TitleLanguage.Tatar => "tt",
            TitleLanguage.Telugu => "te",
            TitleLanguage.Turkmen => "tk",
            TitleLanguage.Uighur => "ug",
            TitleLanguage.Uzbek => "uz",
            TitleLanguage.Welsh => "cy",
            TitleLanguage.Xhosa => "xh",
            TitleLanguage.Yiddish => "yi",
            TitleLanguage.Yoruba => "yo",
            TitleLanguage.Zulu => "zu",
            _ => "unk",
        };
    }
    
    public static string GetString(this TitleType type)
    {
        return type.ToString().ToLowerInvariant();
    }

    public static TitleType GetTitleType(this string name)
    {
        foreach (var type in Enum.GetValues(typeof(TitleType)).Cast<TitleType>())
        {
            if (type.GetString().Equals(name.ToLowerInvariant())) return type;
        }

        return name.ToLowerInvariant() switch
        {
            "syn" => TitleType.Synonym,
            "card" => TitleType.TitleCard,
            "kana" => TitleType.KanjiReading,
            "kanareading" => TitleType.KanjiReading,
            _ => TitleType.None,
        };
    }
}
