using System.Text;
using Microsoft.Build.Framework;

namespace Shoko.BuildTools.Tasks;

/// <summary>
///   Appends release channel metadata if ReleaseChannel is set.
/// </summary>
public class AppendReleaseChannel : Microsoft.Build.Utilities.Task
{

    [Required]
    public string ProjectDir { get; set; } = string.Empty;

    [Required]
    public string OutputPath { get; set; } = string.Empty;

    public string? ReleaseChannel { get; set; }

    private static readonly string[] _knownChannels = ["Stable", "Dev", "Debug"];

    public override bool Execute()
    {
        try
        {
            var channel = NormalizeChannel(ReleaseChannel);
            if (channel is null && !string.IsNullOrWhiteSpace(ReleaseChannel))
            {
                Log.LogError("Unknown ReleaseChannel '{0}'. Expected one of: {1}.", ReleaseChannel, string.Join(", ", _knownChannels));
                return false;
            }

            if (channel is null)
                return true;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Shoko.BuildTools.Tasks.AppendReleaseChannel");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System.Reflection;");
            sb.AppendLine();
            sb.AppendLine($"[assembly: AssemblyMetadata(\"ReleaseChannel\", \"{Escape(channel)}\")]");

            File.WriteAllText(OutputPath, sb.ToString());
            Log.LogMessage(MessageImportance.Normal, "Generated release channel metadata: {0}", OutputPath);
            return true;
        }
        catch (Exception ex)
        {
            Log.LogError("Failed to stamp git metadata: {0}", ex.Message);
            return false;
        }
    }

    private static string? NormalizeChannel(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return null;

        var trimmed = value!.Trim();
        foreach (var known in _knownChannels)
        {
            if (string.Equals(known, trimmed, StringComparison.OrdinalIgnoreCase))
                return known;
        }

        return null;
    }

    private static string Escape(string value)
        => value.Replace("\\", "\\\\")
                .Replace("\"", "\\\"");
}
