using System.Text;
using Microsoft.Build.Framework;

namespace Shoko.BuildTools.Tasks;

/// <summary>
///   Base for the tasks that stamp the plugin's identity, tags and
///   dependencies. Whatever a task finds on its own is replaced by the
///   matching <c>Plugin*</c> property when that is set; lists are never
///   merged.
/// </summary>
public abstract class PluginMetadataTask : Microsoft.Build.Utilities.Task
{
    [Required]
    public string ProjectDir { get; set; } = string.Empty;

    [Required]
    public string OutputPath { get; set; } = string.Empty;

    /// <summary>
    ///   <c>$(PluginID)</c>. Must be a GUID.
    /// </summary>
    public string? PluginID { get; set; }

    /// <summary>
    ///   <c>$(PluginName)</c>.
    /// </summary>
    public string? PluginName { get; set; }

    /// <summary>
    ///   <c>$(PluginOverview)</c>.
    /// </summary>
    public string? PluginOverview { get; set; }

    /// <summary>
    ///   <c>$(PluginTags)</c>, comma-separated.
    /// </summary>
    public string? PluginTags { get; set; }

    /// <summary>
    ///   <c>$(PluginDependencies)</c>, in the format
    ///   <see cref="PluginDependencyList" /> reads.
    /// </summary>
    public string? PluginDependencies { get; set; }

    /// <summary>
    ///   Apply the <c>Plugin*</c> properties over what the task found, check
    ///   the result, and write it to <see cref="OutputPath" />. Logs every
    ///   problem and returns <c>false</c> if there is any.
    /// </summary>
    private protected bool WriteMetadata(
        string generatorName,
        Guid? id,
        string? name,
        string? overview,
        IReadOnlyList<string>? tags,
        IReadOnlyList<PluginDependencyEntry>? dependencies,
        string dependencySource)
    {
        if (!string.IsNullOrWhiteSpace(PluginID))
        {
            if (!Guid.TryParse(PluginID.Trim(), out var parsedId))
            {
                Log.LogError("PluginID '{0}' is not a GUID.", PluginID);
                return false;
            }

            id = parsedId;
        }

        if (!string.IsNullOrWhiteSpace(PluginName))
            name = PluginName.Trim();

        if (!string.IsNullOrWhiteSpace(PluginOverview))
            overview = PluginOverview.Trim();

        if (!string.IsNullOrWhiteSpace(PluginTags))
            tags = PluginTags.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

        if (!string.IsNullOrWhiteSpace(PluginDependencies))
        {
            dependencies = PluginDependencyList.Parse(PluginDependencies, out var parseErrors);
            dependencySource = "PluginDependencies";
            foreach (var error in parseErrors)
                Log.LogError("Invalid {0}: {1}", dependencySource, error);

            if (parseErrors.Count > 0)
                return false;
        }

        if (dependencies is { Count: > 0 })
        {
            var errors = PluginDependencyList.Validate(dependencies);
            foreach (var error in errors)
                Log.LogError("Invalid {0}: {1}", dependencySource, error);

            if (errors.Count > 0)
                return false;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// Generated by Shoko.BuildTools.Tasks.{generatorName}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine();

        if (id.HasValue)
            sb.AppendLine($"[assembly: AssemblyMetadata(\"PackageID\", \"{id.Value:D}\")]");

        if (!string.IsNullOrEmpty(name))
            sb.AppendLine($"[assembly: AssemblyMetadata(\"PackageName\", \"{Escape(name)}\")]");

        if (!string.IsNullOrEmpty(overview))
            sb.AppendLine($"[assembly: AssemblyMetadata(\"PackageOverview\", \"{Escape(overview)}\")]");

        if (tags is { Count: > 0 })
            sb.AppendLine($"[assembly: AssemblyMetadata(\"PackageTags\", \"{Escape(string.Join(",", tags))}\")]");

        if (dependencies is { Count: > 0 })
            sb.AppendLine($"[assembly: AssemblyMetadata(\"PackageDependencies\", \"{Escape(PluginDependencyList.Format(dependencies))}\")]");

        File.WriteAllText(OutputPath, sb.ToString());
        Log.LogMessage(MessageImportance.Normal, "Generated: {0}", OutputPath);
        return true;
    }

    private static string Escape(string value)
        => value.Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\n", "\\n")
                .Replace("\r", "\\r")
                .Replace("\t", "\\t");
}
