using System.Reflection;
using System.Runtime.Loader;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Shoko.BuildTools.Tasks;

/// <summary>
///   Reads plugin identity (ID, Name, Description) from source files using
///   Roslyn syntax trees, falling back to calling UuidUtility.GetV5 via
///   reflection when the GUID is computed from a type name.
/// </summary>
public class ReadPluginIdentityFromSource : Microsoft.Build.Utilities.Task
{
    [Required]
    public string ProjectDir { get; set; } = string.Empty;

    [Required]
    public string OutputPath { get; set; } = string.Empty;

    /// <summary>
    ///   Path to search for the Shoko.Abstractions assembly in NuGet cache.
    /// </summary>
    public string? NuGetPackageRoot { get; set; }

    public override bool Execute()
    {
        try
        {
            var csFiles = Directory.GetFiles(ProjectDir, "*.cs", SearchOption.AllDirectories);
            Guid? pluginId = null;
            string? pluginName = null;
            string? pluginDescription = null;
            string? pluginClassFullName = null;

            foreach (var file in csFiles)
            {
                var source = File.ReadAllText(file);
                var tree = CSharpSyntaxTree.ParseText(source, CSharpParseOptions.Default.WithKind(SourceCodeKind.Regular));
                var root = tree.GetRoot();

                foreach (var classDecl in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
                {
                    if (!ImplementsIPlugin(classDecl))
                        continue;

                    var fullName = GetFullName(classDecl);

                    // Extract ID, Name, Description from property declarations
                    Guid? candidateId = null;
                    string? candidateName = null;
                    string? candidateDesc = null;

                    foreach (var member in classDecl.Members)
                    {
                        if (member is PropertyDeclarationSyntax prop)
                        {
                            var propName = prop.Identifier.Text;
                            var value = GetExpressionValue(prop.Initializer?.Value);

                            // Also check expression-bodied members: => "value"
                            if (value is null && prop.ExpressionBody is not null)
                                value = GetExpressionValue(prop.ExpressionBody.Expression);

                            switch (propName)
                            {
                                case "ID" when value is not null && Guid.TryParse(value, out var g):
                                    candidateId = g;
                                    break;
                                case "Name":
                                    candidateName = value;
                                    break;
                                case "Description":
                                    candidateDesc = value;
                                    break;
                            }
                        }
                    }

                    // If ID wasn't found as a literal, check GetV5 patterns
                    if (candidateId is null)
                    {
                        // Check the ID property itself
                        candidateId = TryResolveGetV5Guid(classDecl, NuGetPackageRoot);

                        // Also check static fields that compute the ID (e.g., StaticID = GetV5(...))
                        if (candidateId is null)
                        {
                            candidateId = TryResolveGetV5FromField(classDecl, NuGetPackageRoot);
                        }
                    }

                    // Take the first result with at least an ID; prefer results with more fields
                    if (candidateId.HasValue)
                    {
                        pluginId = candidateId;
                        pluginName ??= candidateName;
                        pluginDescription ??= candidateDesc;
                        pluginClassFullName ??= fullName;
                    }
                }
            }

            if (pluginClassFullName is null)
            {
                Log.LogMessage(MessageImportance.Low, "No IPlugin implementation found in source files.");
                return true;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Shoko.BuildTools.Tasks.ReadPluginIdentityFromSource");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System.Reflection;");
            sb.AppendLine();

            if (pluginId.HasValue)
                sb.AppendLine($"[assembly: AssemblyMetadata(\"PackageID\", \"{pluginId.Value:D}\")]");

            if (pluginName is not null)
                sb.AppendLine($"[assembly: AssemblyMetadata(\"PackageName\", \"{Escape(pluginName)}\")]");

            if (pluginDescription is not null)
                sb.AppendLine($"[assembly: AssemblyMetadata(\"PackageOverview\", \"{Escape(pluginDescription)}\")]");

            File.WriteAllText(OutputPath, sb.ToString());
            Log.LogMessage(MessageImportance.Normal, "Generated plugin identity: {0}", OutputPath);
            return true;
        }
        catch (Exception ex)
        {
            Log.LogError("Failed to read plugin identity from source: {0}", ex.Message);
            return false;
        }
    }

    private static bool ImplementsIPlugin(ClassDeclarationSyntax classDecl)
    {
        if (classDecl.BaseList is null)
            return false;

        return classDecl.BaseList.Types.Any(bt =>
        {
            var name = bt.Type switch
            {
                IdentifierNameSyntax id => id.Identifier.Text,
                GenericNameSyntax gen => gen.Identifier.Text,
                QualifiedNameSyntax qn => qn switch
                {
                    { Right: IdentifierNameSyntax rid } => rid.Identifier.Text,
                    { Right: GenericNameSyntax rgen } => rgen.Identifier.Text,
                    _ => null,
                },
                _ => null,
            };
            return name == "IPlugin";
        });
    }

    private static string GetFullName(ClassDeclarationSyntax classDecl)
    {
        var parts = new List<string> { classDecl.Identifier.Text };
        var parent = classDecl.Parent;
        while (parent is BaseNamespaceDeclarationSyntax ns)
        {
            parts.Insert(0, ns.Name.ToString());
            parent = ns.Parent;
        }
        while (parent is ClassDeclarationSyntax parentClass)
        {
            parts.Insert(0, parentClass.Identifier.Text);
            parent = parentClass.Parent;
        }
        return string.Join(".", parts);
    }

    private static string? GetExpressionValue(ExpressionSyntax? expr)
    {
        if (expr is null)
            return null;

        // String literal: "value"
        if (expr is LiteralExpressionSyntax lit && lit.IsKind(SyntaxKind.StringLiteralExpression))
            return lit.Token.ValueText;

        // new Guid("...")
        if (expr is ImplicitObjectCreationExpressionSyntax || expr is ObjectCreationExpressionSyntax)
        {
            var argList = expr.DescendantNodes().OfType<ArgumentListSyntax>().FirstOrDefault();
            if (argList?.Arguments.Count == 1)
            {
                var arg = argList.Arguments[0].Expression;
                if (arg is LiteralExpressionSyntax argLit && argLit.IsKind(SyntaxKind.StringLiteralExpression))
                    return argLit.Token.ValueText;
            }
        }

        // nameof(Plugin)
        if (expr is InvocationExpressionSyntax inv)
        {
            var invoked = inv.Expression.ToString();
            if (invoked == "nameof" && inv.ArgumentList?.Arguments.Count > 0)
                return inv.ArgumentList.Arguments[0].ToString();
        }

        // Ternary: condition ? "value1" : "value2"
        if (expr is ConditionalExpressionSyntax ternary)
        {
            var whenTrue = GetExpressionValue(ternary.WhenTrue);
            var whenFalse = GetExpressionValue(ternary.WhenFalse);
            return whenTrue ?? whenFalse;
        }

        return null;
    }

    /// <summary>
    ///   For plugins that compute their ID via UuidUtility.GetV5(typeof(X).FullName),
    ///   load the referenced Shoko.Abstractions assembly from NuGet cache and call
    ///   GetV5 via reflection.
    /// </summary>
    private Guid? TryResolveGetV5Guid(ClassDeclarationSyntax classDecl, string? nuGetPackageRoot)
    {
        try
        {
            // Look for GetV5(typeof(X).FullName) or UuidUtility.GetV5(typeof(X).FullName!) expressions
            foreach (var member in classDecl.Members)
            {
                if (member is PropertyDeclarationSyntax prop && prop.Identifier.Text == "ID")
                {
                    var fullName = ExtractGetV5TypeName(prop);
                    if (fullName is null && classDecl.Parent is BaseNamespaceDeclarationSyntax ns)
                    {
                        // Try typeof(ClassName).FullName where ClassName is the current class
                        fullName = $"{ns.Name}.{classDecl.Identifier.Text}";
                    }

                    if (fullName is not null)
                        return CallGetV5(fullName, nuGetPackageRoot);
                }
            }

            // Fallback: check if ID is computed via GetV5 in the member list
            foreach (var member in classDecl.Members)
            {
                if (member is PropertyDeclarationSyntax prop && prop.Identifier.Text == "ID")
                {
                    var fullName = ExtractGetV5TypeName(prop);
                    if (fullName is not null)
                        return CallGetV5(fullName, nuGetPackageRoot);
                }
            }
        }
        catch (Exception ex)
        {
            Log.LogWarning("Failed to resolve GetV5 GUID: {0}", ex.Message);
        }

        return null;
    }

    /// <summary>
    ///   Check if a static field (like <c>StaticID = GetV5(typeof(X).FullName!)</c> or
    ///   <c>StaticID = new Guid("...")</c>) provides the plugin ID, and resolve it.
    /// </summary>
    private Guid? TryResolveGetV5FromField(ClassDeclarationSyntax classDecl, string? nuGetPackageRoot)
    {
        try
        {
            foreach (var member in classDecl.Members)
            {
                if (member is FieldDeclarationSyntax field &&
                    field.Modifiers.Any(m => m.IsKind(SyntaxKind.StaticKeyword)))
                {
                    // Check for GetV5 expression in the field initializer
                    var fullName = ExtractGetV5TypeName(field);
                    if (fullName is not null)
                        return CallGetV5(fullName, nuGetPackageRoot);

                    // Check for new Guid("...") literal in the field initializer
                    foreach (var eq in field.DescendantNodes().OfType<EqualsValueClauseSyntax>())
                    {
                        var guidStr = GetExpressionValue(eq.Value);
                        if (guidStr is not null && Guid.TryParse(guidStr, out var guid))
                            return guid;
                    }
                }
            }
        }
        catch (Exception ex)
        {
            Log.LogWarning("Failed to resolve GetV5 from field: {0}", ex.Message);
        }

        return null;
    }

    private static string? ExtractGetV5TypeName(SyntaxNode member)
    {
        // Look for patterns like:
        //   GetV5(typeof(Plugin).FullName!)
        //   UuidUtility.GetV5(typeof(Plugin).FullName!)
        foreach (var inv in member.DescendantNodes().OfType<InvocationExpressionSyntax>())
        {
            var methodName = inv.Expression.ToString();
            if (!methodName.Contains("GetV5"))
                continue;

            // Get the first argument
            if (inv.ArgumentList?.Arguments.Count < 1)
                continue;

            var arg = inv.ArgumentList!.Arguments[0].Expression;

            // typeof(Plugin).FullName or typeof(Plugin).FullName!
            if (arg is MemberAccessExpressionSyntax memberAccess)
            {
                var inner = memberAccess.Expression;
                // Strip null-forgiving operator
                if (inner is PostfixUnaryExpressionSyntax postfix && postfix.IsKind(SyntaxKind.SuppressNullableWarningExpression))
                    inner = postfix.Operand;

                if (inner is TypeOfExpressionSyntax typeofExpr)
                {
                    return typeofExpr.Type switch
                    {
                        IdentifierNameSyntax id => id.Identifier.Text,
                        QualifiedNameSyntax qn => qn.ToString(),
                        _ => null,
                    };
                }
            }

            // Direct type name as string
            if (arg is LiteralExpressionSyntax lit && lit.IsKind(SyntaxKind.StringLiteralExpression))
                return lit.Token.ValueText;
        }

        return null;
    }

    private Guid? CallGetV5(string typeName, string? nuGetPackageRoot)
    {
        // Find the Shoko.Abstractions DLL from the NuGet cache
        var root = nuGetPackageRoot
                   ?? Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".nuget", "packages");

        var abstractionsDir = Directory.GetDirectories(Path.Combine(root, "shoko.abstractions"))
            .OrderByDescending(d => d)
            .FirstOrDefault()
            ?? Directory.GetDirectories(Path.Combine(root, "Shoko.Abstractions"))
                .OrderByDescending(d => d)
                .FirstOrDefault();

        if (abstractionsDir is null)
        {
            Log.LogMessage(MessageImportance.Low, "Shoko.Abstractions not found in NuGet cache.");
            return null;
        }

        var dllPath = Directory.GetFiles(abstractionsDir, "Shoko.Abstractions.dll", SearchOption.AllDirectories)
            .FirstOrDefault();

        if (dllPath is null)
        {
            Log.LogMessage(MessageImportance.Low, "Shoko.Abstractions.dll not found at {0}", abstractionsDir);
            return null;
        }

        try
        {
            // Load in an isolated collectible context so we can call GetV5
            var alc = new AssemblyLoadContext("GetV5Loader", isCollectible: true);
            try
            {
                var abstractionsAssembly = alc.LoadFromAssemblyPath(dllPath);
                var uuidUtilType = abstractionsAssembly.GetType("Shoko.Abstractions.Utilities.UuidUtility");

                if (uuidUtilType is null)
                {
                    Log.LogMessage(MessageImportance.Low, "UuidUtility type not found.");
                    return null;
                }

                var getV5Method = uuidUtilType.GetMethod("GetV5", [typeof(string), typeof(Guid)]);
                if (getV5Method is null)
                {
                    Log.LogMessage(MessageImportance.Low, "UuidUtility.GetV5 method not found.");
                    return null;
                }

                var result = getV5Method.Invoke(null, [typeName, Guid.Empty]);
                if (result is Guid guid)
                    return guid;
            }
            finally
            {
                alc.Unload();
            }
        }
        catch (Exception ex)
        {
            Log.LogMessage(MessageImportance.Low, "Failed to invoke GetV5 via reflection: {0}", ex.Message);
        }

        return null;
    }

    private static string Escape(string value)
        => value.Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\n", "\\n")
                .Replace("\r", "\\r")
                .Replace("\t", "\\t");
}
