using System.Diagnostics;
using System.Text;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;

namespace Shoko.BuildTools.Tasks;

/// <summary>
///   Runs git commands to extract release metadata and writes a .cs file
///   with assembly-level AssemblyMetadata attributes.
/// </summary>
public class StampGitMetadata : Microsoft.Build.Utilities.Task
{
    [Required]
    public string ProjectDir { get; set; } = string.Empty;

    [Required]
    public string OutputPath { get; set; } = string.Empty;

    public override bool Execute()
    {
        try
        {
            var releaseDate = RunGit("log -1 --format=%aI");
            var sourceRevision = RunGit("rev-parse HEAD");
            var releaseTag = RunGit("describe --exact-match --tags --match \"v[0-9]*.[0-9]*.[0-9]*\"");

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Shoko.BuildTools.Tasks.StampGitMetadata");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System.Reflection;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(releaseDate))
                sb.AppendLine($"[assembly: AssemblyMetadata(\"ReleaseDate\", \"{Escape(releaseDate)}\")]");

            if (!string.IsNullOrEmpty(sourceRevision))
                sb.AppendLine($"[assembly: AssemblyMetadata(\"SourceRevision\", \"{Escape(sourceRevision)}\")]");

            if (!string.IsNullOrEmpty(releaseTag))
                sb.AppendLine($"[assembly: AssemblyMetadata(\"ReleaseTag\", \"{Escape(releaseTag)}\")]");

            File.WriteAllText(OutputPath, sb.ToString());
            Log.LogMessage(MessageImportance.Normal, "Generated git metadata: {0}", OutputPath);
            return true;
        }
        catch (Exception ex)
        {
            Log.LogError("Failed to stamp git metadata: {0}", ex.Message);
            return false;
        }
    }

    private string RunGit(string arguments)
    {
        try
        {
            var psi = new ProcessStartInfo("git", arguments)
            {
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true,
                WorkingDirectory = ProjectDir,
            };

            using var process = Process.Start(psi);
            if (process is null) return "";

            var output = process.StandardOutput.ReadToEnd().Trim();
            process.WaitForExit();

            // If git exited with non-zero (e.g., no tag), return empty
            return process.ExitCode == 0 ? output : "";
        }
        catch (Exception ex)
        {
            Log.LogMessage(MessageImportance.Low, "Git command failed: {0}", ex.Message);
            return "";
        }
    }

    private static string Escape(string value)
        => value.Replace("\\", "\\\\")
                .Replace("\"", "\\\"");
}
