section .text

global _MD5_Transform_p5@0
align 10h

_MD5_Transform_p5@0:
   mov     edi, [esp+28h]
   mov     eax, [edi+8]
   mov     ebx, [edi+0Ch]
   mov     ecx, [edi+10h]
   mov     edx, [edi+14h]
   mov     esi, ecx
   xor     ecx, edx
   add     eax, [ebp+0]
   and     ecx, ebx
   add     eax, 0D76AA478h
   xor     ecx, edx
   add     eax, ecx
   rol     eax, 7
   add     eax, ebx
   mov     ecx, ebx
   xor     ebx, esi
   add     edx, [ebp+4]
   and     ebx, eax
   add     edx, 0E8C7B756h
   xor     ebx, esi
   add     edx, ebx
   rol     edx, 0Ch
   add     edx, eax
   mov     ebx, eax
   xor     eax, ecx
   add     esi, [ebp+8]
   and     eax, edx
   add     esi, 242070DBh
   xor     eax, ecx
   add     esi, eax
   rol     esi, 11h
   add     esi, edx
   mov     eax, edx
   xor     edx, ebx
   add     ecx, [ebp+0Ch]
   and     edx, esi
   add     ecx, 0C1BDCEEEh
   xor     edx, ebx
   add     ecx, edx
   rol     ecx, 16h
   add     ecx, esi
   mov     edx, esi
   xor     esi, eax
   add     ebx, [ebp+10h]
   and     esi, ecx
   add     ebx, 0F57C0FAFh
   xor     esi, eax
   add     ebx, esi
   rol     ebx, 7
   add     ebx, ecx
   mov     esi, ecx
   xor     ecx, edx
   add     eax, [ebp+14h]
   and     ecx, ebx
   add     eax, 4787C62Ah
   xor     ecx, edx
   add     eax, ecx
   rol     eax, 0Ch
   add     eax, ebx
   mov     ecx, ebx
   xor     ebx, esi
   add     edx, [ebp+18h]
   and     ebx, eax
   add     edx, 0A8304613h
   xor     ebx, esi
   add     edx, ebx
   rol     edx, 11h
   add     edx, eax
   mov     ebx, eax
   xor     eax, ecx
   add     esi, [ebp+1Ch]
   and     eax, edx
   add     esi, 0FD469501h
   xor     eax, ecx
   add     esi, eax
   rol     esi, 16h
   add     esi, edx
   mov     eax, edx
   xor     edx, ebx
   add     ecx, [ebp+20h]
   and     edx, esi
   add     ecx, 698098D8h
   xor     edx, ebx
   add     ecx, edx
   rol     ecx, 7
   add     ecx, esi
   mov     edx, esi
   xor     esi, eax
   add     ebx, [ebp+24h]
   and     esi, ecx
   add     ebx, 8B44F7AFh
   xor     esi, eax
   add     ebx, esi
   rol     ebx, 0Ch
   add     ebx, ecx
   mov     esi, ecx
   xor     ecx, edx
   add     eax, [ebp+28h]
   and     ecx, ebx
   add     eax, 0FFFF5BB1h
   xor     ecx, edx
   add     eax, ecx
   rol     eax, 11h
   add     eax, ebx
   mov     ecx, ebx
   xor     ebx, esi
   add     edx, [ebp+2Ch]
   and     ebx, eax
   add     edx, 895CD7BEh
   xor     ebx, esi
   add     edx, ebx
   rol     edx, 16h
   add     edx, eax
   mov     ebx, eax
   xor     eax, ecx
   add     esi, [ebp+30h]
   and     eax, edx
   add     esi, 6B901122h
   xor     eax, ecx
   add     esi, eax
   rol     esi, 7
   add     esi, edx
   mov     eax, edx
   xor     edx, ebx
   add     ecx, [ebp+34h]
   and     edx, esi
   add     ecx, 0FD987193h
   xor     edx, ebx
   add     ecx, edx
   rol     ecx, 0Ch
   add     ecx, esi
   mov     edx, esi
   xor     esi, eax
   add     ebx, [ebp+38h]
   and     esi, ecx
   add     ebx, 0A679438Eh
   xor     esi, eax
   add     ebx, esi
   rol     ebx, 11h
   add     ebx, ecx
   mov     esi, ecx
   xor     ecx, edx
   add     eax, [ebp+3Ch]
   and     ecx, ebx
   add     eax, 49B40821h
   xor     ecx, edx
   add     eax, ecx
   rol     eax, 16h
   add     eax, ebx
   mov     ecx, eax
   xor     eax, ebx
   add     edx, [ebp+4]
   and     eax, esi
   add     edx, 0F61E2562h
   xor     eax, ebx
   add     edx, eax
   rol     edx, 5
   add     edx, ecx
   mov     eax, edx
   xor     edx, ecx
   add     esi, [ebp+18h]
   and     edx, ebx
   add     esi, 0C040B340h
   xor     edx, ecx
   add     esi, edx
   rol     esi, 9
   add     esi, eax
   mov     edx, esi
   xor     esi, eax
   add     ebx, [ebp+2Ch]
   and     esi, ecx
   add     ebx, 265E5A51h
   xor     esi, eax
   add     ebx, esi
   rol     ebx, 0Eh
   add     ebx, edx
   mov     esi, ebx
   xor     ebx, edx
   add     ecx, [ebp+0]
   and     ebx, eax
   add     ecx, 0E9B6C7AAh
   xor     ebx, edx
   add     ecx, ebx
   rol     ecx, 14h
   add     ecx, esi
   mov     ebx, ecx
   xor     ecx, esi
   add     eax, [ebp+14h]
   and     ecx, edx
   add     eax, 0D62F105Dh
   xor     ecx, esi
   add     eax, ecx
   rol     eax, 5
   add     eax, ebx
   mov     ecx, eax
   xor     eax, ebx
   add     edx, [ebp+28h]
   and     eax, esi
   add     edx, 2441453h
   xor     eax, ebx
   add     edx, eax
   rol     edx, 9
   add     edx, ecx
   mov     eax, edx
   xor     edx, ecx
   add     esi, [ebp+3Ch]
   and     edx, ebx
   add     esi, 0D8A1E681h
   xor     edx, ecx
   add     esi, edx
   rol     esi, 0Eh
   add     esi, eax
   mov     edx, esi
   xor     esi, eax
   add     ebx, [ebp+10h]
   and     esi, ecx
   add     ebx, 0E7D3FBC8h
   xor     esi, eax
   add     ebx, esi
   rol     ebx, 14h
   add     ebx, edx
   mov     esi, ebx
   xor     ebx, edx
   add     ecx, [ebp+24h]
   and     ebx, eax
   add     ecx, 21E1CDE6h
   xor     ebx, edx
   add     ecx, ebx
   rol     ecx, 5
   add     ecx, esi
   mov     ebx, ecx
   xor     ecx, esi
   add     eax, [ebp+38h]
   and     ecx, edx
   add     eax, 0C33707D6h
   xor     ecx, esi
   add     eax, ecx
   rol     eax, 9
   add     eax, ebx
   mov     ecx, eax
   xor     eax, ebx
   add     edx, [ebp+0Ch]
   and     eax, esi
   add     edx, 0F4D50D87h
   xor     eax, ebx
   add     edx, eax
   rol     edx, 0Eh
   add     edx, ecx
   mov     eax, edx
   xor     edx, ecx
   add     esi, [ebp+20h]
   and     edx, ebx
   add     esi, 455A14EDh
   xor     edx, ecx
   add     esi, edx
   rol     esi, 14h
   add     esi, eax
   mov     edx, esi
   xor     esi, eax
   add     ebx, [ebp+34h]
   and     esi, ecx
   add     ebx, 0A9E3E905h
   xor     esi, eax
   add     ebx, esi
   rol     ebx, 5
   add     ebx, edx
   mov     esi, ebx
   xor     ebx, edx
   add     ecx, [ebp+8]
   and     ebx, eax
   add     ecx, 0FCEFA3F8h
   xor     ebx, edx
   add     ecx, ebx
   rol     ecx, 9
   add     ecx, esi
   mov     ebx, ecx
   xor     ecx, esi
   add     eax, [ebp+1Ch]
   and     ecx, edx
   add     eax, 676F02D9h
   xor     ecx, esi
   add     eax, ecx
   rol     eax, 0Eh
   add     eax, ebx
   mov     ecx, eax
   xor     eax, ebx
   add     edx, [ebp+30h]
   and     eax, esi
   add     edx, 8D2A4C8Ah
   xor     eax, ebx
   add     edx, eax
   rol     edx, 14h
   add     edx, ecx
   mov     eax, edx
   xor     edx, ecx
   add     esi, [ebp+14h]
   xor     edx, ebx
   add     esi, 0FFFA3942h
   add     esi, edx
   rol     esi, 4
   add     esi, eax
   mov     edx, esi
   xor     esi, eax
   add     ebx, [ebp+20h]
   xor     esi, ecx
   add     ebx, 8771F681h
   add     ebx, esi
   rol     ebx, 0Bh
   add     ebx, edx
   mov     esi, ebx
   xor     ebx, edx
   add     ecx, [ebp+2Ch]
   xor     ebx, eax
   add     ecx, 6D9D6122h
   add     ecx, ebx
   rol     ecx, 10h
   add     ecx, esi
   mov     ebx, ecx
   xor     ecx, esi
   add     eax, [ebp+38h]
   xor     ecx, edx
   add     eax, 0FDE5380Ch
   add     eax, ecx
   rol     eax, 17h
   add     eax, ebx
   mov     ecx, eax
   xor     eax, ebx
   add     edx, [ebp+4]
   xor     eax, esi
   add     edx, 0A4BEEA44h
   add     edx, eax
   rol     edx, 4
   add     edx, ecx
   mov     eax, edx
   xor     edx, ecx
   add     esi, [ebp+10h]
   xor     edx, ebx
   add     esi, 4BDECFA9h
   add     esi, edx
   rol     esi, 0Bh
   add     esi, eax
   mov     edx, esi
   xor     esi, eax
   add     ebx, [ebp+1Ch]
   xor     esi, ecx
   add     ebx, 0F6BB4B60h
   add     ebx, esi
   rol     ebx, 10h
   add     ebx, edx
   mov     esi, ebx
   xor     ebx, edx
   add     ecx, [ebp+28h]
   xor     ebx, eax
   add     ecx, 0BEBFBC70h
   add     ecx, ebx
   rol     ecx, 17h
   add     ecx, esi
   mov     ebx, ecx
   xor     ecx, esi
   add     eax, [ebp+34h]
   xor     ecx, edx
   add     eax, 289B7EC6h
   add     eax, ecx
   rol     eax, 4
   add     eax, ebx
   mov     ecx, eax
   xor     eax, ebx
   add     edx, [ebp+0]
   xor     eax, esi
   add     edx, 0EAA127FAh
   add     edx, eax
   rol     edx, 0Bh
   add     edx, ecx
   mov     eax, edx
   xor     edx, ecx
   add     esi, [ebp+0Ch]
   xor     edx, ebx
   add     esi, 0D4EF3085h
   add     esi, edx
   rol     esi, 10h
   add     esi, eax
   mov     edx, esi
   xor     esi, eax
   add     ebx, [ebp+18h]
   xor     esi, ecx
   add     ebx, 4881D05h
   add     ebx, esi
   rol     ebx, 17h
   add     ebx, edx
   mov     esi, ebx
   xor     ebx, edx
   add     ecx, [ebp+24h]
   xor     ebx, eax
   add     ecx, 0D9D4D039h
   add     ecx, ebx
   rol     ecx, 4
   add     ecx, esi
   mov     ebx, ecx
   xor     ecx, esi
   add     eax, [ebp+30h]
   xor     ecx, edx
   add     eax, 0E6DB99E5h
   add     eax, ecx
   rol     eax, 0Bh
   add     eax, ebx
   mov     ecx, eax
   xor     eax, ebx
   add     edx, [ebp+3Ch]
   xor     eax, esi
   add     edx, 1FA27CF8h
   add     edx, eax
   rol     edx, 10h
   add     edx, ecx
   mov     eax, edx
   xor     edx, ecx
   add     esi, [ebp+8]
   xor     edx, ebx
   add     esi, 0C4AC5665h
   add     esi, edx
   rol     esi, 17h
   add     esi, eax
   mov     edx, ecx
   not     ecx
   add     ebx, [ebp+0]
   or      ecx, esi
   add     ebx, 0F4292244h
   xor     ecx, eax
   add     ebx, ecx
   rol     ebx, 6
   add     ebx, esi
   mov     ecx, eax
   not     eax
   add     edx, [ebp+1Ch]
   or      eax, ebx
   add     edx, 432AFF97h
   xor     eax, esi
   add     edx, eax
   rol     edx, 0Ah
   add     edx, ebx
   mov     eax, esi
   not     esi
   add     ecx, [ebp+38h]
   or      esi, edx
   add     ecx, 0AB9423A7h
   xor     esi, ebx
   add     ecx, esi
   rol     ecx, 0Fh
   add     ecx, edx
   mov     esi, ebx
   not     ebx
   add     eax, [ebp+14h]
   or      ebx, ecx
   add     eax, 0FC93A039h
   xor     ebx, edx
   add     eax, ebx
   rol     eax, 15h
   add     eax, ecx
   mov     ebx, edx
   not     edx
   add     esi, [ebp+30h]
   or      edx, eax
   add     esi, 655B59C3h
   xor     edx, ecx
   add     esi, edx
   rol     esi, 6
   add     esi, eax
   mov     edx, ecx
   not     ecx
   add     ebx, [ebp+0Ch]
   or      ecx, esi
   add     ebx, 8F0CCC92h
   xor     ecx, eax
   add     ebx, ecx
   rol     ebx, 0Ah
   add     ebx, esi
   mov     ecx, eax
   not     eax
   add     edx, [ebp+28h]
   or      eax, ebx
   add     edx, 0FFEFF47Dh
   xor     eax, esi
   add     edx, eax
   rol     edx, 0Fh
   add     edx, ebx
   mov     eax, esi
   not     esi
   add     ecx, [ebp+4]
   or      esi, edx
   add     ecx, 85845DD1h
   xor     esi, ebx
   add     ecx, esi
   rol     ecx, 15h
   add     ecx, edx
   mov     esi, ebx
   not     ebx
   add     eax, [ebp+20h]
   or      ebx, ecx
   add     eax, 6FA87E4Fh
   xor     ebx, edx
   add     eax, ebx
   rol     eax, 6
   add     eax, ecx
   mov     ebx, edx
   not     edx
   add     esi, [ebp+3Ch]
   or      edx, eax
   add     esi, 0FE2CE6E0h
   xor     edx, ecx
   add     esi, edx
   rol     esi, 0Ah
   add     esi, eax
   mov     edx, ecx
   not     ecx
   add     ebx, [ebp+18h]
   or      ecx, esi
   add     ebx, 0A3014314h
   xor     ecx, eax
   add     ebx, ecx
   rol     ebx, 0Fh
   add     ebx, esi
   mov     ecx, eax
   not     eax
   add     edx, [ebp+34h]
   or      eax, ebx
   add     edx, 4E0811A1h
   xor     eax, esi
   add     edx, eax
   rol     edx, 15h
   add     edx, ebx
   mov     eax, esi
   not     esi
   add     ecx, [ebp+10h]
   or      esi, edx
   add     ecx, 0F7537E82h
   xor     esi, ebx
   add     ecx, esi
   rol     ecx, 6
   add     ecx, edx
   mov     esi, ebx
   not     ebx
   add     eax, [ebp+2Ch]
   or      ebx, ecx
   add     eax, 0BD3AF235h
   xor     ebx, edx
   add     eax, ebx
   rol     eax, 0Ah
   add     eax, ecx
   mov     ebx, edx
   not     edx
   add     esi, [ebp+8]
   or      edx, eax
   add     esi, 2AD7D2BBh
   xor     edx, ecx
   add     esi, edx
   rol     esi, 0Fh
   add     esi, eax
   mov     edx, ecx
   not     ecx
   add     ebx, [ebp+24h]
   or      ecx, esi
   add     ebx, 0EB86D391h
   xor     ecx, eax
   add     ebx, ecx
   rol     ebx, 15h
   add     ebx, esi
   add     [edi+8], edx
   add     [edi+0Ch], ebx
   add     [edi+10h], esi
   add     [edi+14h], eax
   retn   
    
global _MD5_Add_p5@12
align 10h

_MD5_Add_p5@12:
   pusha   
   mov     ecx, [esp+20h+12]
   and     ecx, ecx
   jz      get_out
   xor     edx, edx
   mov     ebp, [esp+20h+8]
   mov     edi, [esp+20h+4]
   mov     ebx, [edi]
   mov     eax, ebx
   add     ebx, ecx
   mov     [edi], ebx
   adc     [edi+4], edx
   and     eax, 3Fh
   jnz     partial_buffer
full_blocks:
   mov     ecx, [esp+20h+12]
   and     ecx, ecx
   jz      get_out
   sub     ecx, 40h
   jb      end_of_stream
   mov     [esp+20h+12], ecx
   call    _MD5_Transform_p5@0
   add     ebp, 40h
   jmp     full_blocks
end_of_stream:
   mov     edi, [esp+20h+4]
   mov     esi, ebp
   lea     edi, [edi+18h]
   add     ecx, 40h
   rep movsb
   jmp     get_out
partial_buffer:
   add     ecx, eax
   cmp     ecx, 40h
   jb      short_stream
   mov     ecx, 0FFFFFFC0h
   add     ecx, eax
   add     [esp+20h+12], ecx
loc:
   mov     bl, [ebp+0]
   inc     ebp
   mov     [edi+ecx+58h], bl
   inc     ecx
   jnz     loc
   mov     [esp+20h+8], ebp
   lea     ebp, [edi+18h]
   call    _MD5_Transform_p5@0
   mov     ebp, [esp+20h+8]
   jmp     full_blocks
short_stream:
   sub     ecx, eax
   mov     esi, ebp
   lea     edi, [edi+eax+18h]
   rep movsb
get_out:
   popa    
   retn    0Ch
   