using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Shoko.Abstractions.Extensions;
using Shoko.Abstractions.Metadata.Enums;
using Shoko.Abstractions.Video.Enums;
using Shoko.Abstractions.Video.Media;
using Shoko.Server.MediaInfo;
using Shoko.Server.Models.Release;
using Shoko.Server.Models.Shoko;
using Shoko.Server.Repositories.Cached;
using Shoko.Server.Repositories.Cached.AniDB;

namespace Shoko.Server.Services;

/// <summary>
/// A <see cref="VideoLocal_Place"/> with its associated video and optional
/// release info already loaded, ready to pass to
/// <see cref="VideoReleaseGroupingService.Group(System.Collections.Generic.IEnumerable{Shoko.Server.Services.ResolvedVideoPlace}, int)"/>.
/// </summary>
public record ResolvedVideoPlace(VideoLocal_Place Place, VideoLocal Video, StoredReleaseInfo? ReleaseInfo);

/// <summary>
/// Groups <see cref="VideoLocal_Place"/> objects into <see cref="VideoReleaseCandidate"/>
/// buckets using a deterministic heuristic over release-provider metadata and
/// MediaInfo stream signals.
/// </summary>
/// <remarks>
/// Grouping is a four-pass process:
/// <list type="number">
///   <item><b>Fuzzy grouping</b> — files are placed into the first bucket where no
///     known signal conflicts with the bucket's existing files.</item>
///   <item><b>Same-group merge</b> — buckets sharing the same release-group key
///     (GroupID + GroupSource) are merged. Quality variation within a group (e.g.
///     chaptered episodes alongside unchaptered) is reported as a mixed signal on
///     the combined candidate rather than producing separate candidates.</item>
///   <item><b>Version-strategy candidates</b> — within each merged group, episodes covered
///     by multiple version numbers produce a BestAvailable candidate (highest version
///     per episode) and a Consistent(v) candidate for each older version.</item>
///   <item><b>Gap-fill candidates</b> — for each partial-coverage version-strategy spec,
///     one gap-fill is generated by greedily selecting filler groups (in order of how
///     many remaining uncovered episodes they contribute) until all gaps are filled or
///     no further progress is possible. Multiple filler groups may be combined. Files
///     without a release-group identity participate via a synthetic per-file-set key.</item>
/// </list>
/// </remarks>
public class VideoReleaseGroupingService(
    VideoLocalRepository videoLocalRepository,
    AniDB_EpisodeRepository anidbEpisodeRepository,
    StoredReleaseInfoRepository releaseInfoRepository,
    CrossRef_File_EpisodeRepository crossRefRepository,
    VideoLocal_PlaceRepository placeRepository)
{
    /// <summary>
    /// Fast heuristic that checks whether a series is likely to produce more than
    /// one release candidate. Inspects SRI group keys, source, and MediaInfo-based
    /// hard separators (codec, resolution, bit depth) so it catches the common case
    /// of the same group publishing both 1080p and 720p (or HEVC and H264) at the
    /// same version without running the full grouper.
    /// <para>
    /// Returns <c>false</c> only when every file has an identified SRI with the
    /// same release-group key, source, codec, resolution, and bit depth, there are
    /// no per-episode version collisions, and no episode is covered by files from
    /// more than one <c>(ManagedFolderID, ParentDirectory)</c> partition — the
    /// latter is a guaranteed hard separator in <c>FuzzyGroup</c>/<c>AreCompatible</c>
    /// regardless of how well every other signal matches, so two otherwise-identical
    /// copies of the same episode living in different folders always produce two
    /// candidates in the full grouper. Only when all of the above hold is a
    /// single-candidate result certain. Returns <c>true</c> when in doubt, so false
    /// negatives are avoided.
    /// </para>
    /// </summary>
    public bool MightHaveMultipleCandidates(IEnumerable<VideoLocal> videos, int animeId)
    {
        var groupKey = (string?)null;
        var source = (ReleaseSource?)null;
        var resolution = (string?)null;
        var videoCodec = (string?)null;
        var bitDepth = (int?)null;
        var episodeVersions = new Dictionary<int, int>();
        var episodeLocations = new Dictionary<int, (int ManagedFolderID, string ParentDirectory)>();

        foreach (var video in videos)
        {
            var sri = releaseInfoRepository.GetByEd2kAndFileSize(video.Hash, video.FileSize);
            if (sri is null) return true;       // unidentified file
            var key = GroupKey(sri);
            if (key is null) return true;       // SRI has no group info
            if (groupKey is null) groupKey = key;
            else if (groupKey != key) return true;

            // Source — soft separator, but cheap to check from SRI
            if (sri.Source != ReleaseSource.Unknown)
            {
                if (source is null) source = sri.Source;
                else if (source.Value != sri.Source) return true;
            }

            // MediaInfo hard separators — VideoLocal.MediaInfo is already in memory
            // (cached entity), so no extra DB queries are needed.
            var videoStream = video.MediaInfo?.VideoStream;
            if (videoStream is not null)
            {
                var codec = MediaInfoUtility.TranslateCodec(videoStream) ?? videoStream.Format?.ToUpperInvariant();
                if (codec is not null)
                {
                    if (videoCodec is null) videoCodec = codec;
                    else if (videoCodec != codec) return true;
                }

                if (videoStream.Width > 0 || videoStream.Height > 0)
                {
                    var res = MediaInfoUtility.GetStandardResolution(Tuple.Create(videoStream.Width, videoStream.Height))
                              ?? $"{videoStream.Width}x{videoStream.Height}";
                    if (resolution is null) resolution = res;
                    else if (resolution != res) return true;
                }

                if (videoStream.BitDepth > 0)
                {
                    if (bitDepth is null) bitDepth = videoStream.BitDepth;
                    else if (bitDepth.Value != videoStream.BitDepth) return true;
                }
            }

            // Representative place for this video — mirrors BuildSignature, which uses
            // the first place of each VideoLocalID group for folder/parent-directory purposes.
            var place = placeRepository.GetByVideoLocal(video.VideoLocalID).FirstOrDefault();
            var location = place is null
                ? ((int ManagedFolderID, string ParentDirectory)?)null
                : (place.ManagedFolderID, GetParentDirectory(place.RelativePath));

            foreach (var xref in sri.CrossReferences)
            {
                // Cross-references to a different anime (crossover/tie-in releases), or whose
                // episode can't be resolved locally at all, must not participate in this anime's
                // version-collision/folder-separation checks.
                if (xref.AnidbEpisodeID <= 0)
                    continue;
                var episode = anidbEpisodeRepository.GetByEpisodeID(xref.AnidbEpisodeID);
                if (episode is null || episode.AnimeID != animeId)
                    continue;

                // Version collision within the same group → GenerateVersionStrategyCandidates
                // would produce BestAvailable + Consistent variants.
                if (episodeVersions.TryGetValue(xref.AnidbEpisodeID, out var existingVersion))
                {
                    if (existingVersion != sri.Version) return true;
                }
                else
                {
                    episodeVersions[xref.AnidbEpisodeID] = sri.Version;
                }

                // Folder hard separator: the same episode covered by files from two different
                // (ManagedFolderID, ParentDirectory) partitions is always split into separate
                // FuzzyGroup buckets, independent of every other signal matching.
                if (location is { } loc)
                {
                    if (episodeLocations.TryGetValue(xref.AnidbEpisodeID, out var existingLocation))
                    {
                        if (existingLocation.ManagedFolderID != loc.ManagedFolderID || existingLocation.ParentDirectory != loc.ParentDirectory)
                            return true;
                    }
                    else
                    {
                        episodeLocations[xref.AnidbEpisodeID] = loc;
                    }
                }
            }
        }
        return false;
    }

    /// <summary>
    /// Resolves the set of (EpisodeType, EpisodeNumber) pairs <paramref name="video"/> covers,
    /// scoped strictly to <paramref name="animeId"/>. A single <see cref="StoredReleaseInfo"/> can
    /// legitimately cross-reference episodes from a <em>different</em> anime entirely — e.g. a
    /// crossover/tie-in release covering one episode of each of two distinct shows. Those
    /// foreign-anime cross-references must never leak into this anime's episode coverage,
    /// grouping, or display; every caller that resolves per-file episode coverage for one
    /// series must go through this method rather than reading <c>CrossReferences</c> directly.
    /// <para>
    /// A cross-reference whose episode can't be resolved locally (metadata not yet synced) is
    /// excluded outright rather than kept with a placeholder — coverage is only ever meaningful
    /// once it has a real episode number to compare/display/dedup with, and every downstream
    /// consumer (ranking, redundancy, DTOs) needs that number anyway, so a partially-resolved
    /// entry has no legitimate use and would only produce confusing nonsense downstream (e.g. a
    /// six-digit AniDB episode ID rendered as if it were an episode number).
    /// </para>
    /// </summary>
    public IReadOnlySet<(EpisodeType Type, int Number)> GetEpisodeCoverageForAnime(VideoLocal video, int animeId)
        => GetEpisodeCoverageForAnime(video, releaseInfoRepository.GetByEd2kAndFileSize(video.Hash, video.FileSize), animeId);

    /// <summary>
    /// Same as <see cref="GetEpisodeCoverageForAnime(VideoLocal, int)"/>, but takes an
    /// already-resolved <paramref name="sri"/> to avoid a redundant repository lookup when the
    /// caller (e.g. <see cref="BuildSignature"/>) already has it in hand.
    /// </summary>
    private IReadOnlySet<(EpisodeType Type, int Number)> GetEpisodeCoverageForAnime(
        VideoLocal video, StoredReleaseInfo? sri, int animeId)
    {
        var result = new HashSet<(EpisodeType, int)>();
        if (sri is not null)
        {
            foreach (var x in sri.CrossReferences)
            {
                if (x.AnidbEpisodeID <= 0) continue;
                var episode = anidbEpisodeRepository.GetByEpisodeID(x.AnidbEpisodeID);
                if (episode is null || episode.AnimeID != animeId) continue;
                result.Add((episode.EpisodeType, episode.EpisodeNumber));
            }
        }
        else
        {
            foreach (var x in crossRefRepository.GetByEd2k(video.Hash))
            {
                if (x.EpisodeID <= 0 || x.AnimeID != animeId) continue;
                var episode = anidbEpisodeRepository.GetByEpisodeID(x.EpisodeID);
                if (episode is null) continue;
                result.Add((episode.EpisodeType, episode.EpisodeNumber));
            }
        }
        return result;
    }

    /// <summary>
    /// Returns the AniDB anime IDs where at least one episode has more than one distinct,
    /// currently-existing video file mapped to it. A series can only produce more than one
    /// release candidate (<see cref="Group(System.Collections.Generic.IEnumerable{Shoko.Server.Models.Shoko.VideoLocal_Place}, int)"/> returning more than one entry) if some episode
    /// is coverable by more than one file — grouping/gap-fill always collapses a series where
    /// every episode has exactly one file down to a single candidate. This is therefore a safe
    /// (never under-inclusive) pre-filter, computed in one pass over <c>CrossRef_File_Episode</c>
    /// rather than per-series repository calls, so it can cut the anime library down to the
    /// (typically much smaller) set worth running <see cref="MightHaveMultipleCandidates"/> and
    /// the full grouper against at all.
    /// </summary>
    public IReadOnlySet<int> GetAnimeIDsWithMultipleFilesPerEpisode()
    {
        // Snapshot existing (Hash, FileSize) pairs once instead of calling the
        // ReaderWriterLockSlim-guarded GetByEd2kAndSize per cross-reference — with
        // 100k+ rows, per-row locked lookups dominate the runtime far more than the
        // O(1) cost of each individual lookup would suggest.
        var existingFiles = videoLocalRepository.GetAll()
            .Select(v => (v.Hash, v.FileSize))
            .ToHashSet();

        var filesPerEpisode = new Dictionary<(int AnimeID, int EpisodeID), HashSet<(string Hash, long FileSize)>>();
        foreach (var xref in crossRefRepository.GetAll())
        {
            if (string.IsNullOrEmpty(xref.Hash) || xref.FileSize <= 0)
                continue;
            if (!existingFiles.Contains((xref.Hash, xref.FileSize)))
                continue; // orphaned cross-reference; the file no longer exists

            var key = (xref.AnimeID, xref.EpisodeID);
            if (!filesPerEpisode.TryGetValue(key, out var files))
                filesPerEpisode[key] = files = [];
            files.Add((xref.Hash, xref.FileSize));
        }

        return filesPerEpisode
            .Where(kv => kv.Value.Count > 1)
            .Select(kv => kv.Key.AnimeID)
            .ToHashSet();
    }

    /// <summary>
    /// Groups the given places into release candidates, resolving the
    /// associated video and release info from the repositories. <paramref name="animeId"/>
    /// scopes episode resolution to this anime — see <see cref="GetEpisodeCoverageForAnime(VideoLocal, int)"/>.
    /// Every place passed in is expected to already belong to this anime; callers are
    /// always single-anime-scoped (there is no code path that groups files across series).
    /// </summary>
    public IReadOnlyList<VideoReleaseCandidate> Group(IEnumerable<VideoLocal_Place> places, int animeId)
        => Group(places.Select(p =>
        {
            var video = videoLocalRepository.GetByID(p.VideoID);
            if (video is null)
                return null;
            var sri = releaseInfoRepository.GetByEd2kAndFileSize(video.Hash, video.FileSize);
            return new ResolvedVideoPlace(p, video, sri);
        }).OfType<ResolvedVideoPlace>(), animeId);

    /// <summary>
    /// Returns one <see cref="VideoReleaseOverride"/> per merged release-group bucket —
    /// the same FuzzyGroup + same-group-merge passes as <see cref="Group(IEnumerable{VideoLocal_Place}, int)"/>
    /// but without the coverage filter or version-strategy split. Used as the data
    /// source for the release override (Mix &amp; Match) view.
    /// </summary>
    public IReadOnlyList<VideoReleaseOverride> GetOverrides(IEnumerable<VideoLocal_Place> places, int animeId)
        => GetOverrides(places.Select(p =>
        {
            var video = videoLocalRepository.GetByID(p.VideoID);
            if (video is null)
                return null;
            var sri = releaseInfoRepository.GetByEd2kAndFileSize(video.Hash, video.FileSize);
            return new ResolvedVideoPlace(p, video, sri);
        }).OfType<ResolvedVideoPlace>(), animeId);

    /// <summary>
    /// Returns one <see cref="VideoReleaseOverride"/> per merged release-group bucket
    /// from pre-resolved place records.
    /// </summary>
    public IReadOnlyList<VideoReleaseOverride> GetOverrides(IEnumerable<ResolvedVideoPlace> resolved, int animeId)
    {
        var sigs = BuildSignatures(resolved, animeId);
        var allEpisodes = (IReadOnlySet<(EpisodeType, int)>)sigs.SelectMany(s => s.Episodes).ToHashSet();
        var buckets = FuzzyGroup(sigs);
        var mergedBuckets = MergeSameGroupBuckets(buckets);
        return mergedBuckets.Select(b => BuildOverride(b, allEpisodes)).ToList();
    }

    /// <summary>
    /// Groups pre-resolved place records into release candidates.
    /// </summary>
    public IReadOnlyList<VideoReleaseCandidate> Group(IEnumerable<ResolvedVideoPlace> resolved, int animeId)
    {
        var sigs = BuildSignatures(resolved, animeId);

        // Full episode set across all files — used to filter incomplete candidates
        var allEpisodes = sigs.SelectMany(s => s.Episodes).ToHashSet();

        var buckets = FuzzyGroup(sigs);

        // Merge buckets that share the same release group — quality variation within a group
        // (subtitle count, chaptered vs. unchaptered per episode) is expressed as mixed signals
        // on the combined candidate rather than splitting into separate candidates.
        var mergedBuckets = MergeSameGroupBuckets(buckets);

        // Guard: a series only belongs in the Multiple Releases utility when at least
        // one episode has files from two or more distinct buckets — i.e., there is a
        // genuine per-episode choice to make. When all buckets cover completely disjoint
        // episode sets (one file per episode spread across groups), there is nothing for
        // the user to decide; return empty so the series is not surfaced.
        // Exception: intra-bucket version collisions (same group, same episode, different
        // version numbers) are also a valid reason to surface a series — the version-strategy
        // pass will split those into BestAvailable + Consistent candidates.
        var bucketEpSets = mergedBuckets
            .Select(b => b.SelectMany(s => s.Episodes).ToHashSet())
            .Where(eps => eps.Count > 0)
            .ToList();
        if (bucketEpSets.Count >= 2)
        {
            var anyOverlap = false;
            for (var i = 0; i < bucketEpSets.Count && !anyOverlap; i++)
                for (var j = i + 1; j < bucketEpSets.Count; j++)
                    if (bucketEpSets[i].Overlaps(bucketEpSets[j]))
                    {
                        anyOverlap = true;
                        break;
                    }
            if (!anyOverlap && !mergedBuckets.Any(HasIntraBucketVersionCollision))
                return [];
        }

        // Phase 2: version-strategy candidates per merged family
        var specs = mergedBuckets.SelectMany(GenerateVersionStrategyCandidates).ToList();

        // Phase 2.5: cross-bucket same-group candidates
        // When two buckets from the same release group overlap on at least one episode
        // (i.e. FuzzyGroup split the same-group files into separate (ManagedFolderID,
        // ParentDirectory) partitions), generate one candidate per bucket's "take" on
        // those episodes. This is the cross-partition analogue of the intra-bucket
        // version split: two different files from the same group for the same episode
        // are competing releases regardless of which managed folder or directory they live in.
        specs.AddRange(GenerateCrossBucketCandidates(mergedBuckets));

        // Phase 3: gap-fill candidates — one per partial anchor, greedily filled
        // across as many filler groups as needed to cover all episodes.
        var gapFillSpecs = GenerateGapFillCandidates(specs, allEpisodes).ToList();

        // Build candidates, dedup by file set.
        // Filter out:
        //   • specs with zero episode coverage when other files have coverage (unrecognised
        //     files that landed in a separate bucket)
        //   • partial-coverage specs (cover some but not all episodes) — selecting a partial
        //     candidate would leave gaps while deleting the only files for those missing episodes.
        //     Gap-fill generation runs first so that full-coverage combined candidates are
        //     always available whenever the individual specs are all partial.
        var seenFileSets = new HashSet<string>();
        var result = new List<VideoReleaseCandidate>();
        foreach (var spec in specs.Concat(gapFillSpecs))
        {
            var specEpisodes = spec.Files.SelectMany(f => f.Episodes).ToHashSet();
            if (specEpisodes.Count == 0 && allEpisodes.Count > 0) continue;
            if (allEpisodes.Count > 0 && !specEpisodes.IsSupersetOf(allEpisodes)) continue;

            var fileSetKey = string.Join(",", spec.Files.SelectMany(f => f.Places).Select(p => p.ID).OrderBy(id => id));
            if (seenFileSets.Add(fileSetKey))
                result.Add(BuildCandidate(spec, allEpisodes));
        }

        return result;
    }

    /// <summary>
    /// Builds one <see cref="FileSignature"/> per distinct <see cref="VideoLocal.VideoLocalID"/>,
    /// carrying every <see cref="VideoLocal_Place"/> that shares that video. This guarantees that
    /// places of the exact same video (e.g. the same file duplicated across two managed folders)
    /// are never split into different fuzzy-group buckets or candidates — they are always ranked,
    /// kept, and deleted together.
    /// </summary>
    private List<FileSignature> BuildSignatures(IEnumerable<ResolvedVideoPlace> resolved, int animeId)
        => resolved
            .GroupBy(r => r.Video.VideoLocalID)
            .Select(g => BuildSignature(g.ToList(), animeId))
            .ToList();

    private FileSignature BuildSignature(IReadOnlyList<ResolvedVideoPlace> group, int animeId)
    {
        var (place, video, sri) = group[0];
        var places = group.Select(g => g.Place).ToList();
        var media = video.MediaInfo;

        var videoStream = media?.VideoStream;
        var audioStream = media?.AudioStreams.FirstOrDefault();
        var generalStream = media?.IsUsable == true ? media.GeneralStream : null;

        var videoCodec = videoStream is not null
            ? MediaInfoUtility.TranslateCodec(videoStream) ?? videoStream.Format?.ToUpperInvariant()
            : null;
        var audioCodec = audioStream is not null
            ? MediaInfoUtility.TranslateCodec(audioStream) ?? audioStream.Format?.ToUpperInvariant()
            : null;
        var resolution = videoStream is not null && (videoStream.Width > 0 || videoStream.Height > 0)
            ? MediaInfoUtility.GetStandardResolution(Tuple.Create(videoStream.Width, videoStream.Height))
              ?? $"{videoStream.Width}x{videoStream.Height}"
            : null;
        var bitDepth = videoStream?.BitDepth ?? 0;
        var container = generalStream?.Format?.ToUpperInvariant();
        var audioStreamCount = media?.AudioStreams.Count ?? 0;
        var subtitleStreamCount = media?.TextStreams.Count ?? 0;

        var mediaAudioLangs = media?.AudioStreams
            .Select(a => a.Language?.GetTitleLanguage() ?? TitleLanguage.Unknown)
            .ToList() ?? [];
        var mediaSubLangs = media?.TextStreams
            .Where(t => !t.External)
            .Select(t => t.Language?.GetTitleLanguage() ?? TitleLanguage.Unknown)
            .ToList() ?? [];

        IReadOnlyList<TitleLanguage> audioLangs;
        IReadOnlyList<TitleLanguage> subLangs;
        if (sri is not null)
        {
            var sriAudioLangs = sri.AudioLanguages?.ToList() ?? [];
            var sriSubLangs = sri.SubtitleLanguages?.ToList() ?? [];
            audioLangs = MergeLanguages(sriAudioLangs, mediaAudioLangs);
            subLangs = MergeLanguages(sriSubLangs, mediaSubLangs);
        }
        else
        {
            audioLangs = mediaAudioLangs.Distinct().ToList();
            subLangs = mediaSubLangs.Distinct().ToList();
        }

        bool? isChaptered = sri?.IsChaptered;
        if (isChaptered is null && (media as IMediaInfo)?.Chapters.Count > 0)
            isChaptered = true;

        var episodes = GetEpisodeCoverageForAnime(video, sri, animeId);

        var parentDirectory = GetParentDirectory(place.RelativePath);
        return new FileSignature
        {
            Place = place,
            Places = places,
            ParentDirectory = parentDirectory,
            ReleaseInfo = sri,
            GroupKeyValue = GroupKey(sri),
            AudioLanguages = audioLangs,
            AudioLanguageSet = audioLangs.ToHashSet(),
            SubtitleLanguages = subLangs,
            SubtitleLanguageSet = subLangs.ToHashSet(),
            VideoCodec = videoCodec,
            BitDepth = bitDepth,
            Resolution = resolution,
            AudioCodec = audioCodec,
            Container = container,
            AudioStreamCount = audioStreamCount,
            SubtitleStreamCount = subtitleStreamCount,
            IsChaptered = isChaptered,
            Episodes = episodes,
        };
    }

    /// <summary>
    /// Places each signature into the first existing bucket where it does not
    /// conflict with any file already in that bucket. Files with SRI are
    /// processed first so they seed buckets with complete signals.
    /// <para>
    /// Partitions by (ManagedFolderID, ParentDirectory) first — the only two
    /// unconditional hard separators in <see cref="AreCompatible"/> (checked before any
    /// wildcard-tolerant signal), so a signature from one partition can never be compatible
    /// with a bucket seeded from a different partition. Scanning each partition's signatures
    /// against only that partition's own buckets — instead of every bucket in the whole
    /// series — turns an O(files × totalBuckets) scan into many much smaller independent
    /// scans, which matters for series with hundreds to thousands of files spread across
    /// many managed folders and directories (e.g. very long-running shows). LINQ's <c>GroupBy</c> preserves
    /// deterministic ordering (groups in first-occurrence order, elements within a group
    /// in source order), so the result is deterministic for a given input even though
    /// bucket order may no longer exactly match a single global scan.
    /// </para>
    /// </summary>
    private static List<List<FileSignature>> FuzzyGroup(List<FileSignature> signatures)
    {
        var ordered = signatures.OrderByDescending(s => s.ReleaseInfo is not null).ToList();
        var buckets = new List<List<FileSignature>>();

        foreach (var partition in ordered.GroupBy(s => (s.Place.ManagedFolderID, s.ParentDirectory)))
        {
            var partitionBuckets = new List<List<FileSignature>>();
            foreach (var sig in partition)
            {
                var target = partitionBuckets.FirstOrDefault(b => b.All(existing => AreCompatible(sig, existing)));
                if (target is not null)
                    target.Add(sig);
                else
                    partitionBuckets.Add([sig]);
            }
            buckets.AddRange(partitionBuckets);
        }

        return buckets;
    }

    /// <summary>
    /// Returns true when the two signatures do not conflict on any known signal.
    /// Missing values on either side are treated as wildcards.
    /// </summary>
    private static bool AreCompatible(FileSignature a, FileSignature b)
    {
        // Hard separators — always split regardless of missing data
        if (a.Place.ManagedFolderID != b.Place.ManagedFolderID) return false;
        if (a.ParentDirectory != b.ParentDirectory) return false;

        // Video encoding signals — only conflict when both are non-null/non-zero and differ
        if (!NullOrCompatible(a.VideoCodec, b.VideoCodec)) return false;
        if (a.BitDepth > 0 && b.BitDepth > 0 && a.BitDepth != b.BitDepth) return false;
        if (!NullOrCompatible(a.Resolution, b.Resolution)) return false;

        // Release group — when both files carry episode data and cover the same episode,
        // require a confirmed matching identity (both sides non-null and equal). Two
        // distinct files for the same episode are competing releases and must land in
        // separate buckets whenever we can't prove otherwise — including when neither
        // side has group metadata (e.g. two manually-linked files), since a missing
        // key is an absence of proof, not proof of sameness. When episodes are disjoint
        // or one side has no episode data, keep the wildcard behaviour so files from the
        // same group that lack group metadata on a subset of episodes still merge correctly.
        var aKey = a.GroupKeyValue;
        var bKey = b.GroupKeyValue;
        var episodesOverlap = a.Episodes.Count > 0 && b.Episodes.Count > 0 && a.Episodes.Overlaps(b.Episodes);
        if (episodesOverlap ? aKey is null || bKey is null || aKey != bKey : !NullOrCompatible(aKey, bKey)) return false;

        // Source — only conflicts when both are explicitly set and differ
        var aSource = a.ReleaseInfo?.Source ?? ReleaseSource.Unknown;
        var bSource = b.ReleaseInfo?.Source ?? ReleaseSource.Unknown;
        if (aSource != ReleaseSource.Unknown && bSource != ReleaseSource.Unknown && aSource != bSource) return false;

        // Language sets — only conflict when both sides have at least one identified language and the sets differ.
        if (a.AudioLanguageSet.Count > 0 && b.AudioLanguageSet.Count > 0 && !a.AudioLanguageSet.SetEquals(b.AudioLanguageSet)) return false;
        if (a.SubtitleLanguageSet.Count > 0 && b.SubtitleLanguageSet.Count > 0 && !a.SubtitleLanguageSet.SetEquals(b.SubtitleLanguageSet)) return false;

        // Audio codec and container — soft separators
        if (!NullOrCompatible(a.AudioCodec, b.AudioCodec)) return false;
        if (!NullOrCompatible(a.Container, b.Container)) return false;

        return true;
    }

    /// <summary>
    /// Merges FuzzyGroup buckets that share the same release-group key (GroupID + GroupSource)
    /// and cover disjoint sets of episodes into a single combined bucket.
    /// <para>
    /// Episode overlap is the signal that two same-group buckets are genuinely different products
    /// (e.g., a 1080p and a 720p encode both covering episode 1). Non-overlapping buckets are
    /// incidental quality variation within one release (e.g., chaptered eps 1–10 alongside
    /// unchaptered eps 11–12, or BD eps 1–12 alongside a DVD-only ep 13).
    /// </para>
    /// Buckets without a known group key, or without any episode data, are left as-is.
    /// </summary>
    private static List<List<FileSignature>> MergeSameGroupBuckets(List<List<FileSignature>> buckets)
    {
        var result = new List<List<FileSignature>>();

        foreach (var bucket in buckets)
        {
            var groupKey = bucket.Select(s => s.GroupKeyValue).FirstOrDefault(k => k is not null);
            if (groupKey is null)
            {
                result.Add(bucket);
                continue;
            }

            var bucketEps = bucket.SelectMany(s => s.Episodes).ToHashSet();

            // Without episode data we cannot verify that the episodes don't overlap — keep separate.
            if (bucketEps.Count > 0)
            {
                var target = result.FirstOrDefault(r =>
                {
                    var rKey = r.Select(s => s.GroupKeyValue).FirstOrDefault(k => k is not null);
                    if (rKey != groupKey) return false;
                    var rEps = r.SelectMany(s => s.Episodes).ToHashSet();
                    return rEps.Count > 0 && !rEps.Overlaps(bucketEps);
                });

                if (target is not null)
                {
                    target.AddRange(bucket);
                    continue;
                }
            }

            result.Add(new List<FileSignature>(bucket));
        }

        return result;
    }

    /// <summary>
    /// For each pair of same-release-group buckets that overlap on at least one episode,
    /// generates a candidate where bucket <c>j</c>'s files are preferred for the overlapping
    /// episodes and bucket <c>i</c>'s files cover the rest. This lets gap-fill assemble a
    /// full-coverage candidate rooted in either bucket's files for the contested episode,
    /// treating them as competing alternatives rather than duplicates.
    /// </summary>
    /// <remarks>
    /// The "prefer i for overlap" direction is already represented by bucket <c>i</c>'s existing
    /// version-strategy spec, so it is only generated here when bucket <c>j</c> has additional
    /// files outside the overlap that would not otherwise appear together with <c>i</c>'s files.
    /// </remarks>
    private static IEnumerable<CandidateSpec> GenerateCrossBucketCandidates(
        IReadOnlyList<List<FileSignature>> mergedBuckets)
    {
        for (var i = 0; i < mergedBuckets.Count; i++)
        {
            var keyI = mergedBuckets[i].Select(s => s.GroupKeyValue).FirstOrDefault(k => k is not null);
            if (keyI is null) continue;
            var epsI = mergedBuckets[i].SelectMany(s => s.Episodes).ToHashSet();
            if (epsI.Count == 0) continue;

            for (var j = i + 1; j < mergedBuckets.Count; j++)
            {
                var keyJ = mergedBuckets[j].Select(s => s.GroupKeyValue).FirstOrDefault(k => k is not null);
                if (keyJ != keyI) continue;
                var epsJ = mergedBuckets[j].SelectMany(s => s.Episodes).ToHashSet();
                if (epsJ.Count == 0 || !epsI.Overlaps(epsJ)) continue;

                // "Prefer j for the overlapping episodes":
                // Take all of j's files, then add i's files that don't cover any episode j covers.
                // This produces a candidate where j's file is used for the contest and i supplies
                // the rest — the counterpart to i's existing BestAvailable spec.
                var iNonOverlap = mergedBuckets[i]
                    .Where(s => !s.Episodes.Any(ep => epsJ.Contains(ep)))
                    .ToList();
                var preferJFiles = mergedBuckets[j].Concat(iNonOverlap).ToList();
                if (preferJFiles.Count > 0)
                    yield return new CandidateSpec(preferJFiles, ReleaseVersionStrategy.BestAvailable,
                        MaxVersion(preferJFiles), false, []);

                // "Prefer i for the overlapping episodes":
                // Only needed when j has files outside the overlap; otherwise it is
                // identical to i's existing version-strategy spec.
                var jNonOverlap = mergedBuckets[j]
                    .Where(s => !s.Episodes.Any(ep => epsI.Contains(ep)))
                    .ToList();
                if (jNonOverlap.Count == 0) continue;
                var preferIFiles = mergedBuckets[i].Concat(jNonOverlap).ToList();
                yield return new CandidateSpec(preferIFiles, ReleaseVersionStrategy.BestAvailable,
                    MaxVersion(preferIFiles), false, []);
            }
        }
    }

    /// <summary>
    /// For each FuzzyGroup bucket, generates one or more version-strategy candidates:
    /// BestAvailable (highest version per episode) and Consistent(v) for each older version
    /// when version-colliding episodes exist.
    /// </summary>
    private static IEnumerable<CandidateSpec> GenerateVersionStrategyCandidates(List<FileSignature> signatures)
    {
        // Separate SRI-backed files from unidentified ones. Unidentified files cannot
        // participate in version-collision detection, but are carried along with every
        // generated candidate since we cannot determine which version they belong to.
        var sriSigs = signatures.Where(s => s.ReleaseInfo is not null && s.Episodes.Count > 0).ToList();
        var noSriSigs = signatures.Where(s => s.ReleaseInfo is null || s.Episodes.Count == 0).ToList();

        if (sriSigs.Count == 0)
        {
            yield return new CandidateSpec(signatures, ReleaseVersionStrategy.BestAvailable, 0, false, []);
            yield break;
        }

        // Map each episode to the set of (version, sig) pairs covering it
        var episodeToVersionedFiles = sriSigs
            .SelectMany(s => s.Episodes.Select(ep => (ep, Version: s.ReleaseInfo!.Version, Sig: s)))
            .GroupBy(x => x.ep)
            .ToDictionary(
                g => g.Key,
                g => g.Select(x => (x.Version, x.Sig)).ToList());

        // Version-colliding episodes: same episode, different version numbers
        var collidingEpisodes = episodeToVersionedFiles
            .Where(kv => kv.Value.Select(x => x.Version).Distinct().Count() > 1)
            .Select(kv => kv.Key)
            .ToHashSet();

        if (collidingEpisodes.Count == 0)
        {
            yield return new CandidateSpec(signatures, ReleaseVersionStrategy.BestAvailable,
                MaxVersion(sriSigs), false, []);
            yield break;
        }

        var maxVersion = MaxVersion(sriSigs);

        // BestAvailable: for each colliding episode, keep only the highest-version file(s).
        // No-SRI files are appended to every candidate since their version is unknown.
        var bestAvailableFiles = SelectFilesForStrategy(episodeToVersionedFiles, collidingEpisodes, bestAvailable: true);
        yield return new CandidateSpec([..bestAvailableFiles, ..noSriSigs], ReleaseVersionStrategy.BestAvailable, maxVersion, false, []);

        // Consistent(v) for each distinct version below maxVersion
        var distinctVersionsBeforeMax = sriSigs
            .Where(s => (s.ReleaseInfo?.Version ?? 0) > 0)
            .Select(s => s.ReleaseInfo!.Version)
            .Distinct()
            .Where(v => v < maxVersion)
            .OrderBy(v => v);

        foreach (var version in distinctVersionsBeforeMax)
        {
            var consistentFiles = SelectFilesForStrategy(episodeToVersionedFiles, collidingEpisodes,
                bestAvailable: false, targetVersion: version);
            if (consistentFiles.Count == 0) continue;
            yield return new CandidateSpec([..consistentFiles, ..noSriSigs], ReleaseVersionStrategy.Consistent, version, false, []);
        }
    }

    /// <summary>
    /// For each version-strategy spec with partial episode coverage, generates a single
    /// gap-fill candidate per anchor spec. Two passes per anchor:
    /// <list type="number">
    ///   <item><b>Single-filler pass</b> — emits one gap-fill per filler group that can
    ///     cover the entire gap on its own (original behaviour, one choice per viable filler).</item>
    ///   <item><b>Multi-filler greedy pass</b> — only when no single filler covers the
    ///     entire gap, greedily combines multiple filler groups (picking whichever covers the
    ///     most remaining uncovered episodes at each step) to produce one fully-covered candidate.
    ///     Anonymous specs (no release-group identity) are included via synthetic per-file-set
    ///     keys so ungrouped files can participate as fillers.</item>
    /// </list>
    /// </summary>
    private static IEnumerable<CandidateSpec> GenerateGapFillCandidates(
        IReadOnlyList<CandidateSpec> specs, IReadOnlySet<(EpisodeType, int)> allEpisodes)
    {
        if (allEpisodes.Count == 0) yield break;

        // Build a filler pool — one representative spec per distinct key.
        // Named groups use their GroupID+GroupSource composite; anonymous specs
        // (no release info or no GroupID) get a synthetic key from their sorted
        // file IDs so they can still participate in the multi-filler pass.
        var bestSpecByKey = specs
            .GroupBy(GetFillerKey)
            .ToDictionary(
                g => g.Key,
                g => g.FirstOrDefault(s => s.Strategy == ReleaseVersionStrategy.BestAvailable) ?? g.First());

        foreach (var anchor in specs)
        {
            var anchorEps = anchor.Files.SelectMany(f => f.Episodes).ToHashSet();
            if (anchorEps.Count == 0 || anchorEps.IsSupersetOf(allEpisodes)) continue;

            var anchorKey = GetFillerKey(anchor);
            var uncoveredBase = allEpisodes.Except(anchorEps).ToHashSet();
            var singleFillerFound = false;

            // Pass 1: single-filler — one gap-fill per filler that alone covers the entire gap.
            foreach (var (key, fillerSpec) in bestSpecByKey)
            {
                if (key == anchorKey) continue;

                var fillerFiles = fillerSpec.Files
                    .Where(f => f.Episodes.Any(ep => uncoveredBase.Contains(ep)))
                    .ToList();
                if (fillerFiles.Count == 0) continue;

                var fillerEps = fillerFiles.SelectMany(f => f.Episodes).ToHashSet();
                if (!fillerEps.IsSupersetOf(uncoveredBase)) continue;

                singleFillerFound = true;
                var shortName = fillerFiles
                    .Select(f => f.ReleaseInfo?.GroupShortName)
                    .FirstOrDefault(n => n is not null);
                IReadOnlyList<string> secondary = shortName is not null ? [shortName] : [];

                yield return new CandidateSpec(
                    anchor.Files.Concat(fillerFiles).ToList(),
                    anchor.Strategy,
                    anchor.Version,
                    IsMixed: true,
                    SecondaryGroupShortNames: secondary);
            }

            // Pass 2: multi-filler greedy — only when no single filler can cover the whole gap.
            // At each step pick the filler contributing the most uncovered episodes.
            if (singleFillerFound) continue;

            var uncovered = uncoveredBase.ToHashSet();
            var multiFillerFiles = new List<FileSignature>();
            var usedKeys = new HashSet<string> { anchorKey };
            var secondaryShortNames = new List<string>();

            while (uncovered.Count > 0)
            {
                string? bestKey = null;
                List<FileSignature>? bestFiles = null;
                var bestCoverCount = 0;

                foreach (var (key, fillerSpec) in bestSpecByKey)
                {
                    if (usedKeys.Contains(key)) continue;

                    var contribution = fillerSpec.Files
                        .Where(f => f.Episodes.Any(ep => uncovered.Contains(ep)))
                        .ToList();
                    if (contribution.Count == 0) continue;

                    var coverCount = contribution
                        .SelectMany(f => f.Episodes)
                        .Count(ep => uncovered.Contains(ep));
                    if (coverCount > bestCoverCount)
                    {
                        bestCoverCount = coverCount;
                        bestKey = key;
                        bestFiles = contribution;
                    }
                }

                if (bestFiles is null) break; // no filler can contribute anything further

                foreach (var ep in bestFiles.SelectMany(f => f.Episodes))
                    uncovered.Remove(ep);

                multiFillerFiles.AddRange(bestFiles);
                usedKeys.Add(bestKey!);

                var shortName = bestFiles
                    .Select(f => f.ReleaseInfo?.GroupShortName)
                    .FirstOrDefault(n => n is not null);
                if (shortName is not null && !secondaryShortNames.Contains(shortName))
                    secondaryShortNames.Add(shortName);
            }

            if (uncovered.Count > 0) continue; // couldn't cover all episodes even with multiple fillers

            yield return new CandidateSpec(
                anchor.Files.Concat(multiFillerFiles).ToList(),
                anchor.Strategy,
                anchor.Version,
                IsMixed: true,
                SecondaryGroupShortNames: secondaryShortNames);
        }
    }

    /// <summary>
    /// Returns the filler-pool key for a <see cref="CandidateSpec"/>: the named
    /// group key when one exists, or a synthetic key built from sorted file IDs for
    /// anonymous specs (no <c>GroupID</c> / <c>GroupSource</c>).
    /// <para>
    /// For named groups the episode set is included in the key so that two specs
    /// from the same release group but covering different episodes (i.e., originating
    /// from distinct merged buckets) remain independent entries in the filler pool.
    /// BestAvailable and Consistent strategy variants from the <em>same</em> bucket
    /// always cover identical episode sets and therefore still collapse to one entry.
    /// </para>
    /// </summary>
    private static string GetFillerKey(CandidateSpec spec)
    {
        var named = spec.Files.Select(f => f.GroupKeyValue).FirstOrDefault(k => k is not null);
        if (named is null)
            return "__anon__" + string.Join(",", spec.Files.SelectMany(f => f.Places).Select(p => p.ID).OrderBy(id => id));
        var epsKey = string.Join(",", spec.Files
            .SelectMany(f => f.Episodes)
            .Select(e => $"{(int)e.Item1}:{e.Item2}")
            .Distinct()
            .OrderBy(k => k));
        return $"{named}|{epsKey}";
    }

    /// <summary>
    /// Selects files for a version strategy. For BestAvailable, picks the highest-version
    /// file per colliding episode (tiebreaker: prefer non-corrupted). For Consistent,
    /// picks files of a specific target version. Non-colliding episodes always pass through.
    /// </summary>
    private static List<FileSignature> SelectFilesForStrategy(
        Dictionary<(EpisodeType, int), List<(int Version, FileSignature Sig)>> episodeToVersionedFiles,
        HashSet<(EpisodeType, int)> collidingEpisodes,
        bool bestAvailable,
        int targetVersion = 0)
    {
        var selectedPlaceIds = new HashSet<int>();
        var selectedSigs = new List<FileSignature>();

        foreach (var (ep, epFiles) in episodeToVersionedFiles)
        {
            List<FileSignature> chosen;
            if (collidingEpisodes.Contains(ep))
            {
                if (bestAvailable)
                {
                    var epMax = epFiles.Max(x => x.Version);
                    var maxVersionFiles = epFiles.Where(x => x.Version == epMax).ToList();
                    // Tiebreaker: prefer non-corrupted when versions match
                    var nonCorrupted = maxVersionFiles.Where(x => x.Sig.ReleaseInfo?.IsCorrupted != true).ToList();
                    chosen = (nonCorrupted.Count > 0 ? nonCorrupted : maxVersionFiles).Select(x => x.Sig).ToList();
                }
                else
                {
                    chosen = epFiles.Where(x => x.Version == targetVersion).Select(x => x.Sig).ToList();
                }
            }
            else
            {
                // Non-colliding: include all files for this episode in every strategy
                chosen = epFiles.Select(x => x.Sig).ToList();
            }

            foreach (var sig in chosen)
            {
                if (selectedPlaceIds.Add(sig.Place.ID))
                    selectedSigs.Add(sig);
            }
        }

        return selectedSigs;
    }

    private static VideoReleaseOverride BuildOverride(
        List<FileSignature> signatures, IReadOnlySet<(EpisodeType, int)> allEpisodes)
    {
        var rep = signatures.FirstOrDefault(s => s.ReleaseInfo is not null) ?? signatures[0];
        var sri = rep.ReleaseInfo;

        var source = Majority(signatures.Select(s =>
            s.ReleaseInfo?.Source is { } src and not ReleaseSource.Unknown ? (ReleaseSource?)src : null))
            ?? ReleaseSource.Unknown;

        var bucketEps = signatures.SelectMany(s => s.Episodes).ToHashSet();

        var files = signatures
            .SelectMany(s => s.Places.Select(p => new VideoReleaseOverrideFile
            {
                Place = p,
                Version = s.ReleaseInfo?.Version ?? 0,
                IsChaptered = s.IsChaptered,
                SubtitleStreamCount = s.SubtitleStreamCount,
                Episodes = s.Episodes,
            }))
            .ToList();

        var resolution          = MajorityRef(signatures.Select(s => s.Resolution));
        var videoCodec          = MajorityRef(signatures.Select(s => s.VideoCodec));
        var bitDepth            = Majority(signatures.Select(s => s.BitDepth > 0 ? (int?)s.BitDepth : null)) ?? 0;
        var audioCodec          = MajorityRef(signatures.Select(s => s.AudioCodec));
        var audioStreamCount    = Majority(signatures.Select(s => s.AudioStreamCount > 0 ? (int?)s.AudioStreamCount : null)) ?? 0;
        var subtitleStreamCount = Majority(signatures.Select(s => s.SubtitleStreamCount > 0 ? (int?)s.SubtitleStreamCount : null)) ?? 0;
        var audioLanguages      = MajorityLanguageSet(signatures.Select(s => s.AudioLanguages));
        var subtitleLanguages   = MajorityLanguageSet(signatures.Select(s => s.SubtitleLanguages));
        var hasPartialCoverage  = allEpisodes.Count > 0 && !bucketEps.IsSupersetOf(allEpisodes);

        // Unlike VideoReleaseCandidate.Key, overrides are always single merged-group buckets
        // (GetOverrides skips the version-strategy/gap-fill passes) rather than composites, so
        // there's no "same aggregate profile, different recipe" ambiguity to guard against —
        // but unlike candidates, overrides had no Key at all, so two unnamed/unidentified
        // buckets in the same series (e.g. two GroupID-null groups) were indistinguishable to
        // any consumer. Always folding in the file composition guarantees uniqueness.
        var compositionKey = string.Join(",", signatures.SelectMany(s => s.Places).Select(p => p.ID).OrderBy(id => id));
        var key = ComputeKey(
            sri?.GroupID, sri?.GroupSource,
            source,
            string.Join(",", audioLanguages.Select(l => l.GetString()).Order()),
            string.Join(",", subtitleLanguages.Select(l => l.GetString()).Order()),
            videoCodec, bitDepth, resolution,
            audioCodec, (string?)null,
            audioStreamCount, subtitleStreamCount,
            (bool?)null, (bool?)null, (bool?)null,
            false, 0,
            ReleaseVersionStrategy.BestAvailable, false, string.Empty,
            compositionKey);

        return new VideoReleaseOverride
        {
            Key = key,
            GroupID = sri?.GroupID,
            GroupSource = sri?.GroupSource,
            GroupName = sri?.GroupName,
            GroupShortName = sri?.GroupShortName,
            Source = source,
            Resolution = resolution,
            VideoCodec = videoCodec,
            BitDepth = bitDepth,
            AudioCodec = audioCodec,
            AudioStreamCount = audioStreamCount,
            SubtitleStreamCount = subtitleStreamCount,
            AudioLanguages = audioLanguages,
            SubtitleLanguages = subtitleLanguages,
            HasPartialCoverage = hasPartialCoverage,
            Files = files,
        };
    }

    private static VideoReleaseCandidate BuildCandidate(CandidateSpec spec, IReadOnlySet<(EpisodeType, int)> allEpisodes)
    {
        var signatures = spec.Files;
        var rep = signatures.FirstOrDefault(s => s.ReleaseInfo is not null) ?? signatures[0];
        var sri = rep.ReleaseInfo;

        var videoCodec          = MajorityRef(signatures.Select(s => s.VideoCodec));
        var resolution          = MajorityRef(signatures.Select(s => s.Resolution));
        var bitDepth            = Majority(signatures.Select(s => s.BitDepth > 0 ? (int?)s.BitDepth : null)) ?? 0;
        var audioCodec          = MajorityRef(signatures.Select(s => s.AudioCodec));
        var container           = MajorityRef(signatures.Select(s => s.Container));
        var audioStreamCount    = Majority(signatures.Select(s => s.AudioStreamCount > 0 ? (int?)s.AudioStreamCount : null)) ?? 0;
        var subtitleStreamCount = Majority(signatures.Select(s => s.SubtitleStreamCount > 0 ? (int?)s.SubtitleStreamCount : null)) ?? 0;
        var source              = Majority(signatures.Select(s => s.ReleaseInfo?.Source is { } src and not ReleaseSource.Unknown ? (ReleaseSource?)src : null))
                                  ?? ReleaseSource.Unknown;
        var audioLanguages      = MajorityLanguageSet(signatures.Select(s => s.AudioLanguages));
        var subtitleLanguages   = MajorityLanguageSet(signatures.Select(s => s.SubtitleLanguages));

        // Majority+mixed for quality flags
        var (isChaptered, isChapteredMixed)   = MajorityWithMix(signatures.Select(s => s.IsChaptered));
        var (isCensored, isCensoredMixed)     = MajorityWithMix(signatures.Select(s => s.ReleaseInfo?.IsCensored));
        var (isCreditless, isCreditlessMixed) = MajorityWithMix(signatures.Select(s => s.ReleaseInfo?.IsCreditless));

        // Any-true for corruption — one corrupt file contaminates the whole candidate
        var isCorrupted = signatures.Any(s => s.ReleaseInfo?.IsCorrupted == true);

        // Homogeneous when all files with a known group share the same group key
        var distinctGroupKeys = signatures
            .Select(s => s.GroupKeyValue)
            .Where(k => k is not null)
            .Distinct()
            .Count();
        var isHomogeneous = distinctGroupKeys <= 1;

        var episodeCoverage = signatures.SelectMany(s => s.Episodes).ToHashSet();

        var episodeGroupMap = new Dictionary<(EpisodeType, int), string?>();
        foreach (var sig in signatures)
        {
            var groupShortName = sig.ReleaseInfo?.GroupShortName;
            foreach (var epId in sig.Episodes)
                episodeGroupMap.TryAdd(epId, groupShortName);
        }

        // Per-episode-type quality signals: aggregate each quality field across the
        // files that cover each type.  A single file can cover multiple types (e.g.
        // a batch that includes specials), so it may contribute to multiple buckets.
        var typeToSigs = new Dictionary<EpisodeType, List<FileSignature>>();
        foreach (var sig in signatures)
        {
            foreach (var (type, _) in sig.Episodes)
            {
                if (!typeToSigs.TryGetValue(type, out var bucket))
                    typeToSigs[type] = bucket = [];
                if (!bucket.Contains(sig))
                    bucket.Add(sig);
            }
        }
        var typeSignals = new Dictionary<EpisodeType, EpisodeTypeQualitySignals>(typeToSigs.Count);
        foreach (var (type, typeSigs) in typeToSigs)
        {
            var (typeIsChaptered, _) = MajorityWithMix(typeSigs.Select(s => s.IsChaptered));
            var (typeIsCensored, _)  = MajorityWithMix(typeSigs.Select(s => s.ReleaseInfo?.IsCensored));
            var (typeIsCreditless, _) = MajorityWithMix(typeSigs.Select(s => s.ReleaseInfo?.IsCreditless));
            typeSignals[type] = new EpisodeTypeQualitySignals(
                Source: Majority(typeSigs.Select(s =>
                    s.ReleaseInfo?.Source is { } src and not ReleaseSource.Unknown
                        ? (ReleaseSource?)src : null)) ?? ReleaseSource.Unknown,
                Resolution: MajorityRef(typeSigs.Select(s => s.Resolution)),
                VideoCodec: MajorityRef(typeSigs.Select(s => s.VideoCodec)),
                BitDepth: Majority(typeSigs.Select(s => s.BitDepth > 0 ? (int?)s.BitDepth : null)) ?? 0,
                AudioCodec: MajorityRef(typeSigs.Select(s => s.AudioCodec)),
                AudioStreamCount: Majority(typeSigs.Select(s =>
                    s.AudioStreamCount > 0 ? (int?)s.AudioStreamCount : null)) ?? 0,
                SubtitleStreamCount: Majority(typeSigs.Select(s =>
                    s.SubtitleStreamCount > 0 ? (int?)s.SubtitleStreamCount : null)) ?? 0,
                IsChaptered: typeIsChaptered,
                IsCensored: typeIsCensored,
                IsCreditless: typeIsCreditless,
                IsCorrupted: typeSigs.Any(s => s.ReleaseInfo?.IsCorrupted == true),
                AudioLanguages: MajorityLanguageSet(typeSigs.Select(s => s.AudioLanguages)),
                SubtitleLanguages: MajorityLanguageSet(typeSigs.Select(s => s.SubtitleLanguages)));
        }

        var sortedAudio          = string.Join(",", audioLanguages.Select(l => l.GetString()).Order());
        var sortedSubs           = string.Join(",", subtitleLanguages.Select(l => l.GetString()).Order());
        var sortedSecondaryGroups = string.Join(",", spec.SecondaryGroupShortNames.Order());

        // For non-mixed (single, homogeneous) candidates, the aggregate quality profile
        // alone fully determines the release's composition — two pure candidates with the
        // same profile represent "the same kind of release" even across different shows/
        // folders, so the key is intentionally location/file-independent there (see
        // VideoReleaseGroupingTests.IdenticalQualityProfiles_ProduceSameKey).
        // For mixed (gap-fill) composites this breaks down: two different combinations of
        // releases stitched together to reach full coverage can majority-vote to the exact
        // same aggregate profile while covering the same episodes with genuinely different
        // underlying files. Folding in the file composition (mirrors Group()'s fileSetKey)
        // for mixed candidates only guarantees Key uniqueness matches candidate uniqueness.
        var compositionKey = spec.IsMixed
            ? string.Join(",", signatures.SelectMany(s => s.Places).Select(p => p.ID).OrderBy(id => id))
            : string.Empty;

        var key = ComputeKey(
            sri?.GroupID, sri?.GroupSource,
            source, sortedAudio, sortedSubs,
            videoCodec, bitDepth, resolution,
            audioCodec, container,
            audioStreamCount, subtitleStreamCount,
            isChaptered, isCensored, isCreditless,
            isCorrupted, spec.Version,
            spec.Strategy, spec.IsMixed, sortedSecondaryGroups, compositionKey);

        // Every place sharing a signature (i.e. the same VideoLocalID) gets the same
        // signals — they are the same physical video, just present in multiple locations.
        var placeSignals = signatures
            .SelectMany(s => s.Places.Select(p => (p.ID, Signal: new PlaceQualitySignals(
                s.IsChaptered,
                s.ReleaseInfo?.IsCensored,
                s.ReleaseInfo?.IsCreditless,
                s.ReleaseInfo?.IsCorrupted ?? false,
                s.AudioLanguages,
                s.SubtitleLanguages,
                s.ReleaseInfo?.Source,
                s.Resolution,
                s.VideoCodec,
                s.BitDepth,
                s.AudioCodec,
                s.AudioStreamCount,
                s.SubtitleStreamCount,
                s.ReleaseInfo?.Version ?? 1))))
            .ToDictionary(x => x.ID, x => x.Signal);

        return new VideoReleaseCandidate
        {
            Key = key,
            HasReleaseInfo = signatures.All(s => s.ReleaseInfo is not null),
            GroupID = sri?.GroupID,
            GroupSource = sri?.GroupSource,
            GroupName = sri?.GroupName,
            GroupShortName = sri?.GroupShortName,
            Source = source,
            AudioLanguages = audioLanguages,
            SubtitleLanguages = subtitleLanguages,
            VideoCodec = videoCodec,
            BitDepth = bitDepth,
            Resolution = resolution,
            AudioCodec = audioCodec,
            Container = container,
            AudioStreamCount = audioStreamCount,
            SubtitleStreamCount = subtitleStreamCount,
            IsChaptered = isChaptered,
            IsChapteredMixed = isChapteredMixed,
            IsCensored = isCensored,
            IsCensoredMixed = isCensoredMixed,
            IsCreditless = isCreditless,
            IsCreditlessMixed = isCreditlessMixed,
            IsCorrupted = isCorrupted,
            Version = spec.Version,
            VersionStrategy = spec.Strategy,
            IsMixed = spec.IsMixed,
            IsHomogeneous = isHomogeneous,
            SecondaryGroupNames = spec.SecondaryGroupShortNames,
            Places = signatures.SelectMany(s => s.Places).ToList(),
            PlaceSignals = placeSignals,
            EpisodeCoverage = episodeCoverage,
            EpisodeGroupMap = episodeGroupMap,
            TypeSignals = typeSignals,
            HasPartialCoverage = allEpisodes.Count > 0 && !episodeCoverage.IsSupersetOf(allEpisodes),
        };
    }

    private static bool HasIntraBucketVersionCollision(List<FileSignature> bucket)
    {
        var episodeVersions = new Dictionary<(EpisodeType, int), int>();
        foreach (var sig in bucket)
        {
            if (sig.ReleaseInfo is null) continue;
            foreach (var ep in sig.Episodes)
            {
                if (episodeVersions.TryGetValue(ep, out var existing) && existing != sig.ReleaseInfo.Version)
                    return true;
                episodeVersions[ep] = sig.ReleaseInfo.Version;
            }
        }
        return false;
    }

    private static int MaxVersion(IEnumerable<FileSignature> sigs)
        => sigs.Max(s => s.ReleaseInfo?.Version ?? 0);

    private static (bool? Majority, bool IsMixed) MajorityWithMix(IEnumerable<bool?> values)
    {
        var knownValues = values.Where(v => v.HasValue).Select(v => v!.Value).ToList();
        if (knownValues.Count == 0) return (null, false);
        var trueCount = knownValues.Count(v => v);
        var falseCount = knownValues.Count - trueCount;
        return (trueCount >= falseCount, trueCount > 0 && falseCount > 0);
    }

    private static T? Majority<T>(IEnumerable<T?> values) where T : struct
        => values.Where(v => v.HasValue)
                 .GroupBy(v => v!.Value)
                 .OrderByDescending(g => g.Count())
                 .Select(g => (T?)g.Key)
                 .FirstOrDefault();

    private static T? MajorityRef<T>(IEnumerable<T?> values) where T : class
        => values.Where(v => v is not null)
                 .GroupBy(v => v)
                 .OrderByDescending(g => g.Count())
                 .Select(g => g.Key)
                 .FirstOrDefault();

    private static IReadOnlyList<TitleLanguage> MajorityLanguageSet(
        IEnumerable<IReadOnlyList<TitleLanguage>> sets)
        => sets.Where(s => s.Count > 0)
               .GroupBy(s => string.Join(",", s.Select(l => l.GetString()).Order()))
               .OrderByDescending(g => g.Count())
               .FirstOrDefault()
               ?.First() ?? [];

    private static string ComputeKey(
        string? groupId, string? groupSource,
        ReleaseSource source,
        string sortedAudio, string sortedSubs,
        string? videoCodec, int bitDepth, string? resolution,
        string? audioCodec, string? container,
        int audioStreamCount, int subtitleStreamCount,
        bool? isChaptered, bool? isCensored, bool? isCreditless,
        bool isCorrupted, int version,
        ReleaseVersionStrategy strategy, bool isMixed, string sortedSecondaryGroups,
        string compositionKey = "")
    {
        static string Tri(bool? v) => v is null ? "?" : v.Value ? "1" : "0";

        var signal = string.Join("|",
            groupId ?? string.Empty,
            groupSource ?? string.Empty,
            (int)source,
            sortedAudio,
            sortedSubs,
            videoCodec ?? string.Empty,
            bitDepth,
            resolution ?? string.Empty,
            audioCodec ?? string.Empty,
            container ?? string.Empty,
            audioStreamCount,
            subtitleStreamCount,
            Tri(isChaptered),
            Tri(isCensored),
            Tri(isCreditless),
            isCorrupted ? "1" : "0",
            version,
            (int)strategy,
            isMixed ? "1" : "0",
            sortedSecondaryGroups,
            compositionKey
        );
        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(signal));
        return Convert.ToHexStringLower(hash);
    }

    /// <summary>
    /// Merges SRI languages with MediaInfo stream languages.
    /// SRI languages occupy the first <paramref name="sriLangs"/>.Count positions;
    /// MediaInfo stream languages fill remaining positions beyond that count.
    /// </summary>
    private static IReadOnlyList<TitleLanguage> MergeLanguages(
        IReadOnlyList<TitleLanguage> sriLangs,
        IReadOnlyList<TitleLanguage> mediaLangs)
    {
        var result = new List<TitleLanguage>(sriLangs);
        for (var i = sriLangs.Count; i < mediaLangs.Count; i++)
            result.Add(mediaLangs[i]);
        return result;
    }

    private static string? GroupKey(StoredReleaseInfo? sri) =>
        !string.IsNullOrEmpty(sri?.GroupID) && !string.IsNullOrEmpty(sri?.GroupSource)
            ? $"{sri.GroupID}|{sri.GroupSource}"
            : null;

    private static bool NullOrCompatible(string? a, string? b) =>
        string.IsNullOrEmpty(a) || string.IsNullOrEmpty(b) || a == b;

    private static bool LanguageSetsMatch(IReadOnlyList<TitleLanguage> a, IReadOnlyList<TitleLanguage> b)
    {
        if (a.Count != b.Count) return false;
        var setA = a.ToHashSet();
        return b.All(l => setA.Contains(l));
    }

    private static string GetParentDirectory(string relativePath)
    {
        var lastSlash = relativePath.LastIndexOf('/');
        return lastSlash <= 0 ? string.Empty : relativePath[..lastSlash];
    }

    private sealed record CandidateSpec(
        List<FileSignature> Files,
        ReleaseVersionStrategy Strategy,
        int Version,
        bool IsMixed,
        IReadOnlyList<string> SecondaryGroupShortNames);

    private sealed class FileSignature
    {
        public required VideoLocal_Place Place { get; init; }
        public required IReadOnlyList<VideoLocal_Place> Places { get; init; }
        public required string ParentDirectory { get; init; }
        public StoredReleaseInfo? ReleaseInfo { get; init; }
        public required IReadOnlyList<TitleLanguage> AudioLanguages { get; init; }
        public required IReadOnlySet<TitleLanguage> AudioLanguageSet { get; init; }
        public required IReadOnlyList<TitleLanguage> SubtitleLanguages { get; init; }
        public required IReadOnlySet<TitleLanguage> SubtitleLanguageSet { get; init; }
        public string? VideoCodec { get; init; }
        public int BitDepth { get; init; }
        public string? Resolution { get; init; }
        public string? AudioCodec { get; init; }
        public string? Container { get; init; }
        public int AudioStreamCount { get; init; }
        public int SubtitleStreamCount { get; init; }
        public bool? IsChaptered { get; init; }
        public IReadOnlySet<(EpisodeType Type, int Number)> Episodes { get; init; } = new HashSet<(EpisodeType, int)>();

        /// <summary>
        /// Precomputed <see cref="GroupKey(StoredReleaseInfo?)"/> for <see cref="ReleaseInfo"/>.
        /// Cached once per signature instead of re-interpolating the group-ID/source string on
        /// every pairwise comparison — for large series (hundreds to thousands of files) the
        /// fuzzy-grouping pass calls this comparison enough times that the allocation matters.
        /// </summary>
        public string? GroupKeyValue { get; init; }
    }
}
