using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using Shoko.Abstractions.Extensions;
using Shoko.Abstractions.Metadata.Enums;
using Shoko.Abstractions.Video.Enums;
using Shoko.Abstractions.Video.Media;
using Shoko.Server.MediaInfo;
using Shoko.Server.Models.Release;
using Shoko.Server.Models.Shoko;
using Shoko.Server.Repositories.Cached;
using Shoko.Server.Repositories.Cached.AniDB;

namespace Shoko.Server.Services;

/// <summary>
/// A <see cref="VideoLocal_Place"/> with its associated video and optional
/// release info already loaded, ready to pass to
/// <see cref="VideoReleaseGroupingService.Group(System.Collections.Generic.IEnumerable{Shoko.Server.Services.ResolvedVideoPlace})"/>.
/// </summary>
public record ResolvedVideoPlace(VideoLocal_Place Place, VideoLocal Video, StoredReleaseInfo? ReleaseInfo);

/// <summary>
/// Groups <see cref="VideoLocal_Place"/> objects into <see cref="VideoReleaseCandidate"/>
/// buckets using a deterministic heuristic over release-provider metadata and
/// MediaInfo stream signals.
/// </summary>
/// <remarks>
/// Grouping is a four-pass process:
/// <list type="number">
///   <item><b>Fuzzy grouping</b> — files are placed into the first bucket where no
///     known signal conflicts with the bucket's existing files.</item>
///   <item><b>Same-group merge</b> — buckets sharing the same release-group key
///     (GroupID + GroupSource) are merged. Quality variation within a group (e.g.
///     chaptered episodes alongside unchaptered) is reported as a mixed signal on
///     the combined candidate rather than producing separate candidates.</item>
///   <item><b>Version-strategy candidates</b> — within each merged group, episodes covered
///     by multiple version numbers produce a BestAvailable candidate (highest version
///     per episode) and a Consistent(v) candidate for each older version.</item>
///   <item><b>Gap-fill candidates</b> — for each partial-coverage version-strategy spec,
///     one gap-fill is generated by greedily selecting filler groups (in order of how
///     many remaining uncovered episodes they contribute) until all gaps are filled or
///     no further progress is possible. Multiple filler groups may be combined. Files
///     without a release-group identity participate via a synthetic per-file-set key.</item>
/// </list>
/// </remarks>
public class VideoReleaseGroupingService(
    VideoLocalRepository videoLocalRepository,
    AniDB_EpisodeRepository anidbEpisodeRepository,
    StoredReleaseInfoRepository releaseInfoRepository,
    CrossRef_File_EpisodeRepository crossRefRepository)
{
    /// <summary>
    /// Fast heuristic that checks whether a series is likely to produce more than
    /// one release candidate. Inspects SRI group keys, source, and MediaInfo-based
    /// hard separators (codec, resolution, bit depth) so it catches the common case
    /// of the same group publishing both 1080p and 720p (or HEVC and H264) at the
    /// same version without running the full grouper.
    /// <para>
    /// Returns <c>false</c> only when every file has an identified SRI with the
    /// same release-group key, source, codec, resolution, and bit depth, and there
    /// are no per-episode version collisions — meaning a single-candidate result is
    /// certain. Returns <c>true</c> when in doubt, so false negatives are avoided.
    /// </para>
    /// </summary>
    public bool MightHaveMultipleCandidates(IEnumerable<VideoLocal> videos)
    {
        var groupKey = (string?)null;
        var source = (ReleaseSource?)null;
        var resolution = (string?)null;
        var videoCodec = (string?)null;
        var bitDepth = (int?)null;
        var episodeVersions = new Dictionary<int, int>();

        foreach (var video in videos)
        {
            var sri = releaseInfoRepository.GetByEd2kAndFileSize(video.Hash, video.FileSize);
            if (sri is null) return true;       // unidentified file
            var key = GroupKey(sri);
            if (key is null) return true;       // SRI has no group info
            if (groupKey is null) groupKey = key;
            else if (groupKey != key) return true;

            // Source — soft separator, but cheap to check from SRI
            if (sri.Source != ReleaseSource.Unknown)
            {
                if (source is null) source = sri.Source;
                else if (source.Value != sri.Source) return true;
            }

            // MediaInfo hard separators — VideoLocal.MediaInfo is already in memory
            // (cached entity), so no extra DB queries are needed.
            var videoStream = video.MediaInfo?.VideoStream;
            if (videoStream is not null)
            {
                var codec = MediaInfoUtility.TranslateCodec(videoStream) ?? videoStream.Format?.ToUpperInvariant();
                if (codec is not null)
                {
                    if (videoCodec is null) videoCodec = codec;
                    else if (videoCodec != codec) return true;
                }

                if (videoStream.Width > 0 || videoStream.Height > 0)
                {
                    var res = MediaInfoUtility.GetStandardResolution(Tuple.Create(videoStream.Width, videoStream.Height))
                              ?? $"{videoStream.Width}x{videoStream.Height}";
                    if (resolution is null) resolution = res;
                    else if (resolution != res) return true;
                }

                if (videoStream.BitDepth > 0)
                {
                    if (bitDepth is null) bitDepth = videoStream.BitDepth;
                    else if (bitDepth.Value != videoStream.BitDepth) return true;
                }
            }

            // Version collision within the same group → GenerateVersionStrategyCandidates
            // would produce BestAvailable + Consistent variants.
            foreach (var xref in sri.CrossReferences)
            {
                if (episodeVersions.TryGetValue(xref.AnidbEpisodeID, out var existing))
                {
                    if (existing != sri.Version) return true;
                }
                else
                {
                    episodeVersions[xref.AnidbEpisodeID] = sri.Version;
                }
            }
        }
        return false;
    }

    /// <summary>
    /// Groups the given places into release candidates, resolving the
    /// associated video and release info from the repositories.
    /// </summary>
    public IReadOnlyList<VideoReleaseCandidate> Group(IEnumerable<VideoLocal_Place> places)
        => Group(places.Select(p =>
        {
            var video = videoLocalRepository.GetByID(p.VideoID);
            if (video is null)
                return null;
            var sri = releaseInfoRepository.GetByEd2kAndFileSize(video.Hash, video.FileSize);
            return new ResolvedVideoPlace(p, video, sri);
        }).OfType<ResolvedVideoPlace>());

    /// <summary>
    /// Returns one <see cref="VideoReleaseOverride"/> per merged release-group bucket —
    /// the same FuzzyGroup + same-group-merge passes as <see cref="Group(IEnumerable{VideoLocal_Place})"/>
    /// but without the coverage filter or version-strategy split. Used as the data
    /// source for the release override (Mix &amp; Match) view.
    /// </summary>
    public IReadOnlyList<VideoReleaseOverride> GetOverrides(IEnumerable<VideoLocal_Place> places)
        => GetOverrides(places.Select(p =>
        {
            var video = videoLocalRepository.GetByID(p.VideoID);
            if (video is null)
                return null;
            var sri = releaseInfoRepository.GetByEd2kAndFileSize(video.Hash, video.FileSize);
            return new ResolvedVideoPlace(p, video, sri);
        }).OfType<ResolvedVideoPlace>());

    /// <summary>
    /// Returns one <see cref="VideoReleaseOverride"/> per merged release-group bucket
    /// from pre-resolved place records.
    /// </summary>
    public IReadOnlyList<VideoReleaseOverride> GetOverrides(IEnumerable<ResolvedVideoPlace> resolved)
    {
        var sigs = BuildSignatures(resolved);
        var allEpisodes = (IReadOnlySet<(EpisodeType, int)>)sigs.SelectMany(s => s.EpisodeIds).ToHashSet();
        var buckets = FuzzyGroup(sigs);
        var mergedBuckets = MergeSameGroupBuckets(buckets);
        return mergedBuckets.Select(b => BuildOverride(b, allEpisodes)).ToList();
    }

    /// <summary>
    /// Groups pre-resolved place records into release candidates.
    /// </summary>
    public IReadOnlyList<VideoReleaseCandidate> Group(IEnumerable<ResolvedVideoPlace> resolved)
    {
        var sigs = BuildSignatures(resolved);

        // Full episode set across all files — used to filter incomplete candidates
        var allEpisodes = sigs.SelectMany(s => s.EpisodeIds).ToHashSet();

        var buckets = FuzzyGroup(sigs);

        // Merge buckets that share the same release group — quality variation within a group
        // (subtitle count, chaptered vs. unchaptered per episode) is expressed as mixed signals
        // on the combined candidate rather than splitting into separate candidates.
        var mergedBuckets = MergeSameGroupBuckets(buckets);

        // Guard: a series only belongs in the Multiple Releases utility when at least
        // one episode has files from two or more distinct buckets — i.e., there is a
        // genuine per-episode choice to make. When all buckets cover completely disjoint
        // episode sets (one file per episode spread across groups), there is nothing for
        // the user to decide; return empty so the series is not surfaced.
        // Exception: intra-bucket version collisions (same group, same episode, different
        // version numbers) are also a valid reason to surface a series — the version-strategy
        // pass will split those into BestAvailable + Consistent candidates.
        var bucketEpSets = mergedBuckets
            .Select(b => b.SelectMany(s => s.EpisodeIds).ToHashSet())
            .Where(eps => eps.Count > 0)
            .ToList();
        if (bucketEpSets.Count >= 2)
        {
            var anyOverlap = false;
            for (var i = 0; i < bucketEpSets.Count && !anyOverlap; i++)
                for (var j = i + 1; j < bucketEpSets.Count; j++)
                    if (bucketEpSets[i].Overlaps(bucketEpSets[j]))
                    {
                        anyOverlap = true;
                        break;
                    }
            if (!anyOverlap && !mergedBuckets.Any(HasIntraBucketVersionCollision))
                return [];
        }

        // Phase 2: version-strategy candidates per merged family
        var specs = mergedBuckets.SelectMany(GenerateVersionStrategyCandidates).ToList();

        // Phase 2.5: cross-bucket same-group candidates
        // When two buckets from the same release group overlap on at least one episode
        // (i.e. FuzzyGroup placed the same-group files in separate managed-folder buckets),
        // generate one candidate per bucket's "take" on those episodes. This is the
        // cross-folder analogue of the intra-bucket version split: two different files
        // from the same group for the same episode are competing releases regardless of
        // which managed folder they live in.
        specs.AddRange(GenerateCrossBucketCandidates(mergedBuckets));

        // Phase 3: gap-fill candidates — one per partial anchor, greedily filled
        // across as many filler groups as needed to cover all episodes.
        var gapFillSpecs = GenerateGapFillCandidates(specs, allEpisodes).ToList();

        // Build candidates, dedup by file set.
        // Filter out:
        //   • specs with zero episode coverage when other files have coverage (unrecognised
        //     files that landed in a separate bucket)
        //   • partial-coverage specs (cover some but not all episodes) — selecting a partial
        //     candidate would leave gaps while deleting the only files for those missing episodes.
        //     Gap-fill generation runs first so that full-coverage combined candidates are
        //     always available whenever the individual specs are all partial.
        var seenFileSets = new HashSet<string>();
        var result = new List<VideoReleaseCandidate>();
        foreach (var spec in specs.Concat(gapFillSpecs))
        {
            var specEpisodes = spec.Files.SelectMany(f => f.EpisodeIds).ToHashSet();
            if (specEpisodes.Count == 0 && allEpisodes.Count > 0) continue;
            if (allEpisodes.Count > 0 && !specEpisodes.IsSupersetOf(allEpisodes)) continue;

            var fileSetKey = string.Join(",", spec.Files.SelectMany(f => f.Places).Select(p => p.ID).OrderBy(id => id));
            if (seenFileSets.Add(fileSetKey))
                result.Add(BuildCandidate(spec, allEpisodes));
        }

        return result;
    }

    /// <summary>
    /// Builds one <see cref="FileSignature"/> per distinct <see cref="VideoLocal.VideoLocalID"/>,
    /// carrying every <see cref="VideoLocal_Place"/> that shares that video. This guarantees that
    /// places of the exact same video (e.g. the same file duplicated across two managed folders)
    /// are never split into different fuzzy-group buckets or candidates — they are always ranked,
    /// kept, and deleted together.
    /// </summary>
    private List<FileSignature> BuildSignatures(IEnumerable<ResolvedVideoPlace> resolved)
        => resolved
            .GroupBy(r => r.Video.VideoLocalID)
            .Select(g => BuildSignature(g.ToList()))
            .ToList();

    private FileSignature BuildSignature(IReadOnlyList<ResolvedVideoPlace> group)
    {
        var (place, video, sri) = group[0];
        var places = group.Select(g => g.Place).ToList();
        var media = video.MediaInfo;

        var videoStream = media?.VideoStream;
        var audioStream = media?.AudioStreams.FirstOrDefault();
        var generalStream = media?.IsUsable == true ? media.GeneralStream : null;

        var videoCodec = videoStream is not null
            ? MediaInfoUtility.TranslateCodec(videoStream) ?? videoStream.Format?.ToUpperInvariant()
            : null;
        var audioCodec = audioStream is not null
            ? MediaInfoUtility.TranslateCodec(audioStream) ?? audioStream.Format?.ToUpperInvariant()
            : null;
        var resolution = videoStream is not null && (videoStream.Width > 0 || videoStream.Height > 0)
            ? MediaInfoUtility.GetStandardResolution(Tuple.Create(videoStream.Width, videoStream.Height))
              ?? $"{videoStream.Width}x{videoStream.Height}"
            : null;
        var bitDepth = videoStream?.BitDepth ?? 0;
        var container = generalStream?.Format?.ToUpperInvariant();
        var audioStreamCount = media?.AudioStreams.Count ?? 0;
        var subtitleStreamCount = media?.TextStreams.Count ?? 0;

        var mediaAudioLangs = media?.AudioStreams
            .Select(a => a.Language?.GetTitleLanguage() ?? TitleLanguage.Unknown)
            .ToList() ?? [];
        var mediaSubLangs = media?.TextStreams
            .Where(t => !t.External)
            .Select(t => t.Language?.GetTitleLanguage() ?? TitleLanguage.Unknown)
            .ToList() ?? [];

        IReadOnlyList<TitleLanguage> audioLangs;
        IReadOnlyList<TitleLanguage> subLangs;
        if (sri is not null)
        {
            var sriAudioLangs = sri.AudioLanguages?.ToList() ?? [];
            var sriSubLangs = sri.SubtitleLanguages?.ToList() ?? [];
            audioLangs = MergeLanguages(sriAudioLangs, mediaAudioLangs);
            subLangs = MergeLanguages(sriSubLangs, mediaSubLangs);
        }
        else
        {
            audioLangs = mediaAudioLangs.Distinct().ToList();
            subLangs = mediaSubLangs.Distinct().ToList();
        }

        bool? isChaptered = sri?.IsChaptered;
        if (isChaptered is null && (media as IMediaInfo)?.Chapters.Count > 0)
            isChaptered = true;

        var episodeIds = sri is not null
            ? sri.CrossReferences
                .Select(x => (
                    anidbEpisodeRepository.GetByEpisodeID(x.AnidbEpisodeID) is { } episode
                        ? episode.EpisodeType
                        : EpisodeType.Episode,
                    x.AnidbEpisodeID))
                .Where(k => k.Item2 > 0)
                .ToHashSet()
            : crossRefRepository.GetByEd2k(video.Hash)
                .Select(x => (
                    anidbEpisodeRepository.GetByEpisodeID(x.EpisodeID) is { } episode
                        ? episode.EpisodeType
                        : EpisodeType.Episode,
                    x.EpisodeID))
                .Where(k => k.Item2 > 0)
                .ToHashSet();

        var parentDirectory = GetParentDirectory(place.RelativePath);
        return new FileSignature
        {
            Place = place,
            Places = places,
            ParentDirectory = parentDirectory,
            ReleaseInfo = sri,
            AudioLanguages = audioLangs,
            AudioLanguageSet = audioLangs.ToHashSet(),
            SubtitleLanguages = subLangs,
            SubtitleLanguageSet = subLangs.ToHashSet(),
            VideoCodec = videoCodec,
            BitDepth = bitDepth,
            Resolution = resolution,
            AudioCodec = audioCodec,
            Container = container,
            AudioStreamCount = audioStreamCount,
            SubtitleStreamCount = subtitleStreamCount,
            IsChaptered = isChaptered,
            EpisodeIds = episodeIds,
        };
    }

    /// <summary>
    /// Places each signature into the first existing bucket where it does not
    /// conflict with any file already in that bucket. Files with SRI are
    /// processed first so they seed buckets with complete signals.
    /// </summary>
    private static List<List<FileSignature>> FuzzyGroup(List<FileSignature> signatures)
    {
        var ordered = signatures.OrderByDescending(s => s.ReleaseInfo is not null).ToList();
        var buckets = new List<List<FileSignature>>();

        foreach (var sig in ordered)
        {
            var target = buckets.FirstOrDefault(b => b.All(existing => AreCompatible(sig, existing)));
            if (target is not null)
                target.Add(sig);
            else
                buckets.Add([sig]);
        }

        return buckets;
    }

    /// <summary>
    /// Returns true when the two signatures do not conflict on any known signal.
    /// Missing values on either side are treated as wildcards.
    /// </summary>
    private static bool AreCompatible(FileSignature a, FileSignature b)
    {
        // Hard separators — always split regardless of missing data
        if (a.Place.ManagedFolderID != b.Place.ManagedFolderID) return false;
        if (a.ParentDirectory != b.ParentDirectory) return false;

        // Video encoding signals — only conflict when both are non-null/non-zero and differ
        if (!NullOrCompatible(a.VideoCodec, b.VideoCodec)) return false;
        if (a.BitDepth > 0 && b.BitDepth > 0 && a.BitDepth != b.BitDepth) return false;
        if (!NullOrCompatible(a.Resolution, b.Resolution)) return false;

        // Release group — when both files carry episode data and cover the same episode,
        // use strict equality (null ≠ known key). Two files for the same episode from
        // different groups — even if one group is unidentified — are competing releases
        // and must land in separate buckets. When episodes are disjoint or one side has
        // no episode data, keep the wildcard behaviour so files from the same group that
        // lack group metadata on a subset of episodes still merge correctly.
        var aKey = GroupKey(a.ReleaseInfo);
        var bKey = GroupKey(b.ReleaseInfo);
        var episodesOverlap = a.EpisodeIds.Count > 0 && b.EpisodeIds.Count > 0 && a.EpisodeIds.Overlaps(b.EpisodeIds);
        if (episodesOverlap ? aKey != bKey : !NullOrCompatible(aKey, bKey)) return false;

        // Source — only conflicts when both are explicitly set and differ
        var aSource = a.ReleaseInfo?.Source ?? ReleaseSource.Unknown;
        var bSource = b.ReleaseInfo?.Source ?? ReleaseSource.Unknown;
        if (aSource != ReleaseSource.Unknown && bSource != ReleaseSource.Unknown && aSource != bSource) return false;

        // Language sets — only conflict when both sides have at least one identified language and the sets differ.
        if (a.AudioLanguageSet.Count > 0 && b.AudioLanguageSet.Count > 0 && !a.AudioLanguageSet.SetEquals(b.AudioLanguageSet)) return false;
        if (a.SubtitleLanguageSet.Count > 0 && b.SubtitleLanguageSet.Count > 0 && !a.SubtitleLanguageSet.SetEquals(b.SubtitleLanguageSet)) return false;

        // Audio codec and container — soft separators
        if (!NullOrCompatible(a.AudioCodec, b.AudioCodec)) return false;
        if (!NullOrCompatible(a.Container, b.Container)) return false;

        return true;
    }

    /// <summary>
    /// Merges FuzzyGroup buckets that share the same release-group key (GroupID + GroupSource)
    /// and cover disjoint sets of episodes into a single combined bucket.
    /// <para>
    /// Episode overlap is the signal that two same-group buckets are genuinely different products
    /// (e.g., a 1080p and a 720p encode both covering episode 1). Non-overlapping buckets are
    /// incidental quality variation within one release (e.g., chaptered eps 1–10 alongside
    /// unchaptered eps 11–12, or BD eps 1–12 alongside a DVD-only ep 13).
    /// </para>
    /// Buckets without a known group key, or without any episode data, are left as-is.
    /// </summary>
    private static List<List<FileSignature>> MergeSameGroupBuckets(List<List<FileSignature>> buckets)
    {
        var result = new List<List<FileSignature>>();

        foreach (var bucket in buckets)
        {
            var groupKey = bucket.Select(s => GroupKey(s.ReleaseInfo)).FirstOrDefault(k => k is not null);
            if (groupKey is null)
            {
                result.Add(bucket);
                continue;
            }

            var bucketEps = bucket.SelectMany(s => s.EpisodeIds).ToHashSet();

            // Without episode data we cannot verify that the episodes don't overlap — keep separate.
            if (bucketEps.Count > 0)
            {
                var target = result.FirstOrDefault(r =>
                {
                    var rKey = r.Select(s => GroupKey(s.ReleaseInfo)).FirstOrDefault(k => k is not null);
                    if (rKey != groupKey) return false;
                    var rEps = r.SelectMany(s => s.EpisodeIds).ToHashSet();
                    return rEps.Count > 0 && !rEps.Overlaps(bucketEps);
                });

                if (target is not null)
                {
                    target.AddRange(bucket);
                    continue;
                }
            }

            result.Add(new List<FileSignature>(bucket));
        }

        return result;
    }

    /// <summary>
    /// For each pair of same-release-group buckets that overlap on at least one episode,
    /// generates a candidate where bucket <c>j</c>'s files are preferred for the overlapping
    /// episodes and bucket <c>i</c>'s files cover the rest. This lets gap-fill assemble a
    /// full-coverage candidate rooted in either bucket's files for the contested episode,
    /// treating them as competing alternatives rather than duplicates.
    /// </summary>
    /// <remarks>
    /// The "prefer i for overlap" direction is already represented by bucket <c>i</c>'s existing
    /// version-strategy spec, so it is only generated here when bucket <c>j</c> has additional
    /// files outside the overlap that would not otherwise appear together with <c>i</c>'s files.
    /// </remarks>
    private static IEnumerable<CandidateSpec> GenerateCrossBucketCandidates(
        IReadOnlyList<List<FileSignature>> mergedBuckets)
    {
        for (var i = 0; i < mergedBuckets.Count; i++)
        {
            var keyI = mergedBuckets[i].Select(s => GroupKey(s.ReleaseInfo)).FirstOrDefault(k => k is not null);
            if (keyI is null) continue;
            var epsI = mergedBuckets[i].SelectMany(s => s.EpisodeIds).ToHashSet();
            if (epsI.Count == 0) continue;

            for (var j = i + 1; j < mergedBuckets.Count; j++)
            {
                var keyJ = mergedBuckets[j].Select(s => GroupKey(s.ReleaseInfo)).FirstOrDefault(k => k is not null);
                if (keyJ != keyI) continue;
                var epsJ = mergedBuckets[j].SelectMany(s => s.EpisodeIds).ToHashSet();
                if (epsJ.Count == 0 || !epsI.Overlaps(epsJ)) continue;

                // "Prefer j for the overlapping episodes":
                // Take all of j's files, then add i's files that don't cover any episode j covers.
                // This produces a candidate where j's file is used for the contest and i supplies
                // the rest — the counterpart to i's existing BestAvailable spec.
                var iNonOverlap = mergedBuckets[i]
                    .Where(s => !s.EpisodeIds.Any(ep => epsJ.Contains(ep)))
                    .ToList();
                var preferJFiles = mergedBuckets[j].Concat(iNonOverlap).ToList();
                if (preferJFiles.Count > 0)
                    yield return new CandidateSpec(preferJFiles, ReleaseVersionStrategy.BestAvailable,
                        MaxVersion(preferJFiles), false, []);

                // "Prefer i for the overlapping episodes":
                // Only needed when j has files outside the overlap; otherwise it is
                // identical to i's existing version-strategy spec.
                var jNonOverlap = mergedBuckets[j]
                    .Where(s => !s.EpisodeIds.Any(ep => epsI.Contains(ep)))
                    .ToList();
                if (jNonOverlap.Count == 0) continue;
                var preferIFiles = mergedBuckets[i].Concat(jNonOverlap).ToList();
                yield return new CandidateSpec(preferIFiles, ReleaseVersionStrategy.BestAvailable,
                    MaxVersion(preferIFiles), false, []);
            }
        }
    }

    /// <summary>
    /// For each FuzzyGroup bucket, generates one or more version-strategy candidates:
    /// BestAvailable (highest version per episode) and Consistent(v) for each older version
    /// when version-colliding episodes exist.
    /// </summary>
    private static IEnumerable<CandidateSpec> GenerateVersionStrategyCandidates(List<FileSignature> signatures)
    {
        // Separate SRI-backed files from unidentified ones. Unidentified files cannot
        // participate in version-collision detection, but are carried along with every
        // generated candidate since we cannot determine which version they belong to.
        var sriSigs = signatures.Where(s => s.ReleaseInfo is not null && s.EpisodeIds.Count > 0).ToList();
        var noSriSigs = signatures.Where(s => s.ReleaseInfo is null || s.EpisodeIds.Count == 0).ToList();

        if (sriSigs.Count == 0)
        {
            yield return new CandidateSpec(signatures, ReleaseVersionStrategy.BestAvailable, 0, false, []);
            yield break;
        }

        // Map each episode to the set of (version, sig) pairs covering it
        var episodeToVersionedFiles = sriSigs
            .SelectMany(s => s.EpisodeIds.Select(ep => (ep, Version: s.ReleaseInfo!.Version, Sig: s)))
            .GroupBy(x => x.ep)
            .ToDictionary(
                g => g.Key,
                g => g.Select(x => (x.Version, x.Sig)).ToList());

        // Version-colliding episodes: same episode, different version numbers
        var collidingEpisodes = episodeToVersionedFiles
            .Where(kv => kv.Value.Select(x => x.Version).Distinct().Count() > 1)
            .Select(kv => kv.Key)
            .ToHashSet();

        if (collidingEpisodes.Count == 0)
        {
            yield return new CandidateSpec(signatures, ReleaseVersionStrategy.BestAvailable,
                MaxVersion(sriSigs), false, []);
            yield break;
        }

        var maxVersion = MaxVersion(sriSigs);

        // BestAvailable: for each colliding episode, keep only the highest-version file(s).
        // No-SRI files are appended to every candidate since their version is unknown.
        var bestAvailableFiles = SelectFilesForStrategy(episodeToVersionedFiles, collidingEpisodes, bestAvailable: true);
        yield return new CandidateSpec([..bestAvailableFiles, ..noSriSigs], ReleaseVersionStrategy.BestAvailable, maxVersion, false, []);

        // Consistent(v) for each distinct version below maxVersion
        var distinctVersionsBeforeMax = sriSigs
            .Where(s => (s.ReleaseInfo?.Version ?? 0) > 0)
            .Select(s => s.ReleaseInfo!.Version)
            .Distinct()
            .Where(v => v < maxVersion)
            .OrderBy(v => v);

        foreach (var version in distinctVersionsBeforeMax)
        {
            var consistentFiles = SelectFilesForStrategy(episodeToVersionedFiles, collidingEpisodes,
                bestAvailable: false, targetVersion: version);
            if (consistentFiles.Count == 0) continue;
            yield return new CandidateSpec([..consistentFiles, ..noSriSigs], ReleaseVersionStrategy.Consistent, version, false, []);
        }
    }

    /// <summary>
    /// For each version-strategy spec with partial episode coverage, generates a single
    /// gap-fill candidate per anchor spec. Two passes per anchor:
    /// <list type="number">
    ///   <item><b>Single-filler pass</b> — emits one gap-fill per filler group that can
    ///     cover the entire gap on its own (original behaviour, one choice per viable filler).</item>
    ///   <item><b>Multi-filler greedy pass</b> — only when no single filler covers the
    ///     entire gap, greedily combines multiple filler groups (picking whichever covers the
    ///     most remaining uncovered episodes at each step) to produce one fully-covered candidate.
    ///     Anonymous specs (no release-group identity) are included via synthetic per-file-set
    ///     keys so ungrouped files can participate as fillers.</item>
    /// </list>
    /// </summary>
    private static IEnumerable<CandidateSpec> GenerateGapFillCandidates(
        IReadOnlyList<CandidateSpec> specs, IReadOnlySet<(EpisodeType, int)> allEpisodes)
    {
        if (allEpisodes.Count == 0) yield break;

        // Build a filler pool — one representative spec per distinct key.
        // Named groups use their GroupID+GroupSource composite; anonymous specs
        // (no release info or no GroupID) get a synthetic key from their sorted
        // file IDs so they can still participate in the multi-filler pass.
        var bestSpecByKey = specs
            .GroupBy(GetFillerKey)
            .ToDictionary(
                g => g.Key,
                g => g.FirstOrDefault(s => s.Strategy == ReleaseVersionStrategy.BestAvailable) ?? g.First());

        foreach (var anchor in specs)
        {
            var anchorEps = anchor.Files.SelectMany(f => f.EpisodeIds).ToHashSet();
            if (anchorEps.Count == 0 || anchorEps.IsSupersetOf(allEpisodes)) continue;

            var anchorKey = GetFillerKey(anchor);
            var uncoveredBase = allEpisodes.Except(anchorEps).ToHashSet();
            var singleFillerFound = false;

            // Pass 1: single-filler — one gap-fill per filler that alone covers the entire gap.
            foreach (var (key, fillerSpec) in bestSpecByKey)
            {
                if (key == anchorKey) continue;

                var fillerFiles = fillerSpec.Files
                    .Where(f => f.EpisodeIds.Any(ep => uncoveredBase.Contains(ep)))
                    .ToList();
                if (fillerFiles.Count == 0) continue;

                var fillerEps = fillerFiles.SelectMany(f => f.EpisodeIds).ToHashSet();
                if (!fillerEps.IsSupersetOf(uncoveredBase)) continue;

                singleFillerFound = true;
                var shortName = fillerFiles
                    .Select(f => f.ReleaseInfo?.GroupShortName)
                    .FirstOrDefault(n => n is not null);
                IReadOnlyList<string> secondary = shortName is not null ? [shortName] : [];

                yield return new CandidateSpec(
                    anchor.Files.Concat(fillerFiles).ToList(),
                    anchor.Strategy,
                    anchor.Version,
                    IsMixed: true,
                    SecondaryGroupShortNames: secondary);
            }

            // Pass 2: multi-filler greedy — only when no single filler can cover the whole gap.
            // At each step pick the filler contributing the most uncovered episodes.
            if (singleFillerFound) continue;

            var uncovered = uncoveredBase.ToHashSet();
            var multiFillerFiles = new List<FileSignature>();
            var usedKeys = new HashSet<string> { anchorKey };
            var secondaryShortNames = new List<string>();

            while (uncovered.Count > 0)
            {
                string? bestKey = null;
                List<FileSignature>? bestFiles = null;
                var bestCoverCount = 0;

                foreach (var (key, fillerSpec) in bestSpecByKey)
                {
                    if (usedKeys.Contains(key)) continue;

                    var contribution = fillerSpec.Files
                        .Where(f => f.EpisodeIds.Any(ep => uncovered.Contains(ep)))
                        .ToList();
                    if (contribution.Count == 0) continue;

                    var coverCount = contribution
                        .SelectMany(f => f.EpisodeIds)
                        .Count(ep => uncovered.Contains(ep));
                    if (coverCount > bestCoverCount)
                    {
                        bestCoverCount = coverCount;
                        bestKey = key;
                        bestFiles = contribution;
                    }
                }

                if (bestFiles is null) break; // no filler can contribute anything further

                foreach (var ep in bestFiles.SelectMany(f => f.EpisodeIds))
                    uncovered.Remove(ep);

                multiFillerFiles.AddRange(bestFiles);
                usedKeys.Add(bestKey!);

                var shortName = bestFiles
                    .Select(f => f.ReleaseInfo?.GroupShortName)
                    .FirstOrDefault(n => n is not null);
                if (shortName is not null && !secondaryShortNames.Contains(shortName))
                    secondaryShortNames.Add(shortName);
            }

            if (uncovered.Count > 0) continue; // couldn't cover all episodes even with multiple fillers

            yield return new CandidateSpec(
                anchor.Files.Concat(multiFillerFiles).ToList(),
                anchor.Strategy,
                anchor.Version,
                IsMixed: true,
                SecondaryGroupShortNames: secondaryShortNames);
        }
    }

    /// <summary>
    /// Returns the filler-pool key for a <see cref="CandidateSpec"/>: the named
    /// group key when one exists, or a synthetic key built from sorted file IDs for
    /// anonymous specs (no <c>GroupID</c> / <c>GroupSource</c>).
    /// <para>
    /// For named groups the episode set is included in the key so that two specs
    /// from the same release group but covering different episodes (i.e., originating
    /// from distinct merged buckets) remain independent entries in the filler pool.
    /// BestAvailable and Consistent strategy variants from the <em>same</em> bucket
    /// always cover identical episode sets and therefore still collapse to one entry.
    /// </para>
    /// </summary>
    private static string GetFillerKey(CandidateSpec spec)
    {
        var named = spec.Files.Select(f => GroupKey(f.ReleaseInfo)).FirstOrDefault(k => k is not null);
        if (named is null)
            return "__anon__" + string.Join(",", spec.Files.SelectMany(f => f.Places).Select(p => p.ID).OrderBy(id => id));
        var epsKey = string.Join(",", spec.Files
            .SelectMany(f => f.EpisodeIds)
            .Select(e => $"{(int)e.Item1}:{e.Item2}")
            .Distinct()
            .OrderBy(k => k));
        return $"{named}|{epsKey}";
    }

    /// <summary>
    /// Selects files for a version strategy. For BestAvailable, picks the highest-version
    /// file per colliding episode (tiebreaker: prefer non-corrupted). For Consistent,
    /// picks files of a specific target version. Non-colliding episodes always pass through.
    /// </summary>
    private static List<FileSignature> SelectFilesForStrategy(
        Dictionary<(EpisodeType, int), List<(int Version, FileSignature Sig)>> episodeToVersionedFiles,
        HashSet<(EpisodeType, int)> collidingEpisodes,
        bool bestAvailable,
        int targetVersion = 0)
    {
        var selectedPlaceIds = new HashSet<int>();
        var selectedSigs = new List<FileSignature>();

        foreach (var (ep, epFiles) in episodeToVersionedFiles)
        {
            List<FileSignature> chosen;
            if (collidingEpisodes.Contains(ep))
            {
                if (bestAvailable)
                {
                    var epMax = epFiles.Max(x => x.Version);
                    var maxVersionFiles = epFiles.Where(x => x.Version == epMax).ToList();
                    // Tiebreaker: prefer non-corrupted when versions match
                    var nonCorrupted = maxVersionFiles.Where(x => x.Sig.ReleaseInfo?.IsCorrupted != true).ToList();
                    chosen = (nonCorrupted.Count > 0 ? nonCorrupted : maxVersionFiles).Select(x => x.Sig).ToList();
                }
                else
                {
                    chosen = epFiles.Where(x => x.Version == targetVersion).Select(x => x.Sig).ToList();
                }
            }
            else
            {
                // Non-colliding: include all files for this episode in every strategy
                chosen = epFiles.Select(x => x.Sig).ToList();
            }

            foreach (var sig in chosen)
            {
                if (selectedPlaceIds.Add(sig.Place.ID))
                    selectedSigs.Add(sig);
            }
        }

        return selectedSigs;
    }

    private static VideoReleaseOverride BuildOverride(
        List<FileSignature> signatures, IReadOnlySet<(EpisodeType, int)> allEpisodes)
    {
        var rep = signatures.FirstOrDefault(s => s.ReleaseInfo is not null) ?? signatures[0];
        var sri = rep.ReleaseInfo;

        var source = Majority(signatures.Select(s =>
            s.ReleaseInfo?.Source is { } src and not ReleaseSource.Unknown ? (ReleaseSource?)src : null))
            ?? ReleaseSource.Unknown;

        var bucketEps = signatures.SelectMany(s => s.EpisodeIds).ToHashSet();

        var files = signatures
            .SelectMany(s => s.Places.Select(p => new VideoReleaseOverrideFile
            {
                Place = p,
                Version = s.ReleaseInfo?.Version ?? 0,
                IsChaptered = s.IsChaptered,
                SubtitleStreamCount = s.SubtitleStreamCount,
                EpisodeIds = s.EpisodeIds,
            }))
            .ToList();

        return new VideoReleaseOverride
        {
            GroupID = sri?.GroupID,
            GroupSource = sri?.GroupSource,
            GroupName = sri?.GroupName,
            GroupShortName = sri?.GroupShortName,
            Source = source,
            Resolution = MajorityRef(signatures.Select(s => s.Resolution)),
            VideoCodec = MajorityRef(signatures.Select(s => s.VideoCodec)),
            BitDepth = Majority(signatures.Select(s => s.BitDepth > 0 ? (int?)s.BitDepth : null)) ?? 0,
            AudioCodec = MajorityRef(signatures.Select(s => s.AudioCodec)),
            AudioStreamCount = Majority(signatures.Select(s => s.AudioStreamCount > 0 ? (int?)s.AudioStreamCount : null)) ?? 0,
            SubtitleStreamCount = Majority(signatures.Select(s => s.SubtitleStreamCount > 0 ? (int?)s.SubtitleStreamCount : null)) ?? 0,
            AudioLanguages = MajorityLanguageSet(signatures.Select(s => s.AudioLanguages)),
            SubtitleLanguages = MajorityLanguageSet(signatures.Select(s => s.SubtitleLanguages)),
            HasPartialCoverage = allEpisodes.Count > 0 && !bucketEps.IsSupersetOf(allEpisodes),
            Files = files,
        };
    }

    private static VideoReleaseCandidate BuildCandidate(CandidateSpec spec, IReadOnlySet<(EpisodeType, int)> allEpisodes)
    {
        var signatures = spec.Files;
        var rep = signatures.FirstOrDefault(s => s.ReleaseInfo is not null) ?? signatures[0];
        var sri = rep.ReleaseInfo;

        var videoCodec          = MajorityRef(signatures.Select(s => s.VideoCodec));
        var resolution          = MajorityRef(signatures.Select(s => s.Resolution));
        var bitDepth            = Majority(signatures.Select(s => s.BitDepth > 0 ? (int?)s.BitDepth : null)) ?? 0;
        var audioCodec          = MajorityRef(signatures.Select(s => s.AudioCodec));
        var container           = MajorityRef(signatures.Select(s => s.Container));
        var audioStreamCount    = Majority(signatures.Select(s => s.AudioStreamCount > 0 ? (int?)s.AudioStreamCount : null)) ?? 0;
        var subtitleStreamCount = Majority(signatures.Select(s => s.SubtitleStreamCount > 0 ? (int?)s.SubtitleStreamCount : null)) ?? 0;
        var source              = Majority(signatures.Select(s => s.ReleaseInfo?.Source is { } src and not ReleaseSource.Unknown ? (ReleaseSource?)src : null))
                                  ?? ReleaseSource.Unknown;
        var audioLanguages      = MajorityLanguageSet(signatures.Select(s => s.AudioLanguages));
        var subtitleLanguages   = MajorityLanguageSet(signatures.Select(s => s.SubtitleLanguages));

        // Majority+mixed for quality flags
        var (isChaptered, isChapteredMixed)   = MajorityWithMix(signatures.Select(s => s.IsChaptered));
        var (isCensored, isCensoredMixed)     = MajorityWithMix(signatures.Select(s => s.ReleaseInfo?.IsCensored));
        var (isCreditless, isCreditlessMixed) = MajorityWithMix(signatures.Select(s => s.ReleaseInfo?.IsCreditless));

        // Any-true for corruption — one corrupt file contaminates the whole candidate
        var isCorrupted = signatures.Any(s => s.ReleaseInfo?.IsCorrupted == true);

        // Homogeneous when all files with a known group share the same group key
        var distinctGroupKeys = signatures
            .Select(s => GroupKey(s.ReleaseInfo))
            .Where(k => k is not null)
            .Distinct()
            .Count();
        var isHomogeneous = distinctGroupKeys <= 1;

        var episodeCoverage = signatures.SelectMany(s => s.EpisodeIds).ToHashSet();

        var episodeGroupMap = new Dictionary<(EpisodeType, int), string?>();
        foreach (var sig in signatures)
        {
            var groupShortName = sig.ReleaseInfo?.GroupShortName;
            foreach (var epId in sig.EpisodeIds)
                episodeGroupMap.TryAdd(epId, groupShortName);
        }

        // Per-episode-type quality signals: aggregate each quality field across the
        // files that cover each type.  A single file can cover multiple types (e.g.
        // a batch that includes specials), so it may contribute to multiple buckets.
        var typeToSigs = new Dictionary<EpisodeType, List<FileSignature>>();
        foreach (var sig in signatures)
        {
            foreach (var (type, _) in sig.EpisodeIds)
            {
                if (!typeToSigs.TryGetValue(type, out var bucket))
                    typeToSigs[type] = bucket = [];
                if (!bucket.Contains(sig))
                    bucket.Add(sig);
            }
        }
        var typeSignals = new Dictionary<EpisodeType, EpisodeTypeQualitySignals>(typeToSigs.Count);
        foreach (var (type, typeSigs) in typeToSigs)
        {
            var (typeIsChaptered, _) = MajorityWithMix(typeSigs.Select(s => s.IsChaptered));
            var (typeIsCensored, _)  = MajorityWithMix(typeSigs.Select(s => s.ReleaseInfo?.IsCensored));
            var (typeIsCreditless, _) = MajorityWithMix(typeSigs.Select(s => s.ReleaseInfo?.IsCreditless));
            typeSignals[type] = new EpisodeTypeQualitySignals(
                Source: Majority(typeSigs.Select(s =>
                    s.ReleaseInfo?.Source is { } src and not ReleaseSource.Unknown
                        ? (ReleaseSource?)src : null)) ?? ReleaseSource.Unknown,
                Resolution: MajorityRef(typeSigs.Select(s => s.Resolution)),
                VideoCodec: MajorityRef(typeSigs.Select(s => s.VideoCodec)),
                BitDepth: Majority(typeSigs.Select(s => s.BitDepth > 0 ? (int?)s.BitDepth : null)) ?? 0,
                AudioCodec: MajorityRef(typeSigs.Select(s => s.AudioCodec)),
                AudioStreamCount: Majority(typeSigs.Select(s =>
                    s.AudioStreamCount > 0 ? (int?)s.AudioStreamCount : null)) ?? 0,
                SubtitleStreamCount: Majority(typeSigs.Select(s =>
                    s.SubtitleStreamCount > 0 ? (int?)s.SubtitleStreamCount : null)) ?? 0,
                IsChaptered: typeIsChaptered,
                IsCensored: typeIsCensored,
                IsCreditless: typeIsCreditless,
                IsCorrupted: typeSigs.Any(s => s.ReleaseInfo?.IsCorrupted == true),
                AudioLanguages: MajorityLanguageSet(typeSigs.Select(s => s.AudioLanguages)),
                SubtitleLanguages: MajorityLanguageSet(typeSigs.Select(s => s.SubtitleLanguages)));
        }

        var sortedAudio          = string.Join(",", audioLanguages.Select(l => l.GetString()).Order());
        var sortedSubs           = string.Join(",", subtitleLanguages.Select(l => l.GetString()).Order());
        var sortedSecondaryGroups = string.Join(",", spec.SecondaryGroupShortNames.Order());

        var key = ComputeKey(
            sri?.GroupID, sri?.GroupSource,
            source, sortedAudio, sortedSubs,
            videoCodec, bitDepth, resolution,
            audioCodec, container,
            audioStreamCount, subtitleStreamCount,
            isChaptered, isCensored, isCreditless,
            isCorrupted, spec.Version,
            spec.Strategy, spec.IsMixed, sortedSecondaryGroups);

        // Every place sharing a signature (i.e. the same VideoLocalID) gets the same
        // signals — they are the same physical video, just present in multiple locations.
        var placeSignals = signatures
            .SelectMany(s => s.Places.Select(p => (p.ID, Signal: new PlaceQualitySignals(
                s.IsChaptered,
                s.ReleaseInfo?.IsCensored,
                s.ReleaseInfo?.IsCreditless,
                s.ReleaseInfo?.IsCorrupted ?? false,
                s.AudioLanguages,
                s.SubtitleLanguages,
                s.ReleaseInfo?.Source,
                s.Resolution,
                s.VideoCodec,
                s.BitDepth,
                s.AudioCodec,
                s.AudioStreamCount,
                s.SubtitleStreamCount,
                s.ReleaseInfo?.Version ?? 1))))
            .ToDictionary(x => x.ID, x => x.Signal);

        return new VideoReleaseCandidate
        {
            Key = key,
            HasReleaseInfo = signatures.All(s => s.ReleaseInfo is not null),
            GroupID = sri?.GroupID,
            GroupSource = sri?.GroupSource,
            GroupName = sri?.GroupName,
            GroupShortName = sri?.GroupShortName,
            Source = source,
            AudioLanguages = audioLanguages,
            SubtitleLanguages = subtitleLanguages,
            VideoCodec = videoCodec,
            BitDepth = bitDepth,
            Resolution = resolution,
            AudioCodec = audioCodec,
            Container = container,
            AudioStreamCount = audioStreamCount,
            SubtitleStreamCount = subtitleStreamCount,
            IsChaptered = isChaptered,
            IsChapteredMixed = isChapteredMixed,
            IsCensored = isCensored,
            IsCensoredMixed = isCensoredMixed,
            IsCreditless = isCreditless,
            IsCreditlessMixed = isCreditlessMixed,
            IsCorrupted = isCorrupted,
            Version = spec.Version,
            VersionStrategy = spec.Strategy,
            IsMixed = spec.IsMixed,
            IsHomogeneous = isHomogeneous,
            SecondaryGroupNames = spec.SecondaryGroupShortNames,
            Places = signatures.SelectMany(s => s.Places).ToList(),
            PlaceSignals = placeSignals,
            EpisodeCoverage = episodeCoverage,
            EpisodeGroupMap = episodeGroupMap,
            TypeSignals = typeSignals,
            HasPartialCoverage = allEpisodes.Count > 0 && !episodeCoverage.IsSupersetOf(allEpisodes),
        };
    }

    private static bool HasIntraBucketVersionCollision(List<FileSignature> bucket)
    {
        var episodeVersions = new Dictionary<(EpisodeType, int), int>();
        foreach (var sig in bucket)
        {
            if (sig.ReleaseInfo is null) continue;
            foreach (var ep in sig.EpisodeIds)
            {
                if (episodeVersions.TryGetValue(ep, out var existing) && existing != sig.ReleaseInfo.Version)
                    return true;
                episodeVersions[ep] = sig.ReleaseInfo.Version;
            }
        }
        return false;
    }

    private static int MaxVersion(IEnumerable<FileSignature> sigs)
        => sigs.Max(s => s.ReleaseInfo?.Version ?? 0);

    private static (bool? Majority, bool IsMixed) MajorityWithMix(IEnumerable<bool?> values)
    {
        var knownValues = values.Where(v => v.HasValue).Select(v => v!.Value).ToList();
        if (knownValues.Count == 0) return (null, false);
        var trueCount = knownValues.Count(v => v);
        var falseCount = knownValues.Count - trueCount;
        return (trueCount >= falseCount, trueCount > 0 && falseCount > 0);
    }

    private static T? Majority<T>(IEnumerable<T?> values) where T : struct
        => values.Where(v => v.HasValue)
                 .GroupBy(v => v!.Value)
                 .OrderByDescending(g => g.Count())
                 .Select(g => (T?)g.Key)
                 .FirstOrDefault();

    private static T? MajorityRef<T>(IEnumerable<T?> values) where T : class
        => values.Where(v => v is not null)
                 .GroupBy(v => v)
                 .OrderByDescending(g => g.Count())
                 .Select(g => g.Key)
                 .FirstOrDefault();

    private static IReadOnlyList<TitleLanguage> MajorityLanguageSet(
        IEnumerable<IReadOnlyList<TitleLanguage>> sets)
        => sets.Where(s => s.Count > 0)
               .GroupBy(s => string.Join(",", s.Select(l => l.GetString()).Order()))
               .OrderByDescending(g => g.Count())
               .FirstOrDefault()
               ?.First() ?? [];

    private static string ComputeKey(
        string? groupId, string? groupSource,
        ReleaseSource source,
        string sortedAudio, string sortedSubs,
        string? videoCodec, int bitDepth, string? resolution,
        string? audioCodec, string? container,
        int audioStreamCount, int subtitleStreamCount,
        bool? isChaptered, bool? isCensored, bool? isCreditless,
        bool isCorrupted, int version,
        ReleaseVersionStrategy strategy, bool isMixed, string sortedSecondaryGroups)
    {
        static string Tri(bool? v) => v is null ? "?" : v.Value ? "1" : "0";

        var signal = string.Join("|",
            groupId ?? string.Empty,
            groupSource ?? string.Empty,
            (int)source,
            sortedAudio,
            sortedSubs,
            videoCodec ?? string.Empty,
            bitDepth,
            resolution ?? string.Empty,
            audioCodec ?? string.Empty,
            container ?? string.Empty,
            audioStreamCount,
            subtitleStreamCount,
            Tri(isChaptered),
            Tri(isCensored),
            Tri(isCreditless),
            isCorrupted ? "1" : "0",
            version,
            (int)strategy,
            isMixed ? "1" : "0",
            sortedSecondaryGroups
        );
        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(signal));
        return Convert.ToHexStringLower(hash);
    }

    /// <summary>
    /// Merges SRI languages with MediaInfo stream languages.
    /// SRI languages occupy the first <paramref name="sriLangs"/>.Count positions;
    /// MediaInfo stream languages fill remaining positions beyond that count.
    /// </summary>
    private static IReadOnlyList<TitleLanguage> MergeLanguages(
        IReadOnlyList<TitleLanguage> sriLangs,
        IReadOnlyList<TitleLanguage> mediaLangs)
    {
        var result = new List<TitleLanguage>(sriLangs);
        for (var i = sriLangs.Count; i < mediaLangs.Count; i++)
            result.Add(mediaLangs[i]);
        return result;
    }

    private static string? GroupKey(StoredReleaseInfo? sri) =>
        !string.IsNullOrEmpty(sri?.GroupID) && !string.IsNullOrEmpty(sri?.GroupSource)
            ? $"{sri.GroupID}|{sri.GroupSource}"
            : null;

    private static bool NullOrCompatible(string? a, string? b) =>
        string.IsNullOrEmpty(a) || string.IsNullOrEmpty(b) || a == b;

    private static bool LanguageSetsMatch(IReadOnlyList<TitleLanguage> a, IReadOnlyList<TitleLanguage> b)
    {
        if (a.Count != b.Count) return false;
        var setA = a.ToHashSet();
        return b.All(l => setA.Contains(l));
    }

    private static string GetParentDirectory(string relativePath)
    {
        var lastSlash = relativePath.LastIndexOf('/');
        return lastSlash <= 0 ? string.Empty : relativePath[..lastSlash];
    }

    private sealed record CandidateSpec(
        List<FileSignature> Files,
        ReleaseVersionStrategy Strategy,
        int Version,
        bool IsMixed,
        IReadOnlyList<string> SecondaryGroupShortNames);

    private sealed class FileSignature
    {
        public required VideoLocal_Place Place { get; init; }
        public required IReadOnlyList<VideoLocal_Place> Places { get; init; }
        public required string ParentDirectory { get; init; }
        public StoredReleaseInfo? ReleaseInfo { get; init; }
        public required IReadOnlyList<TitleLanguage> AudioLanguages { get; init; }
        public required IReadOnlySet<TitleLanguage> AudioLanguageSet { get; init; }
        public required IReadOnlyList<TitleLanguage> SubtitleLanguages { get; init; }
        public required IReadOnlySet<TitleLanguage> SubtitleLanguageSet { get; init; }
        public string? VideoCodec { get; init; }
        public int BitDepth { get; init; }
        public string? Resolution { get; init; }
        public string? AudioCodec { get; init; }
        public string? Container { get; init; }
        public int AudioStreamCount { get; init; }
        public int SubtitleStreamCount { get; init; }
        public bool? IsChaptered { get; init; }
        public IReadOnlySet<(EpisodeType Type, int Number)> EpisodeIds { get; init; } = new HashSet<(EpisodeType, int)>();
    }
}
