// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoko.IntegrationTests.PluginDatabases;

#nullable disable

namespace Shoko.IntegrationTests.PluginDatabases.Migrations.Sqlite
{
    [DbContext(typeof(SampleNotesContext))]
    partial class SampleNotesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Shoko.IntegrationTests.PluginDatabases.SampleBook", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Title = "Seeded"
                        });
                });

            modelBuilder.Entity("Shoko.IntegrationTests.PluginDatabases.SampleNote", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("BookID");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("Shoko.IntegrationTests.PluginDatabases.SampleNote", b =>
                {
                    b.HasOne("Shoko.IntegrationTests.PluginDatabases.SampleBook", "Book")
                        .WithMany("Notes")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Shoko.IntegrationTests.PluginDatabases.SampleBook", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
