// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoko.Server.Data.Context;

#nullable disable

namespace Shoko.Server.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250306055453_TMDBForeignKeys")]
    partial class TMDBForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_AlternateOrdering", b =>
                {
                    b.Property<int>("TMDB_AlternateOrderingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_AlternateOrderingID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("EnglishOverview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HiddenEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int>("SeasonCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbEpisodeGroupCollectionID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TmdbEpisodeGroupCollectionID");

                    b.Property<int?>("TmdbNetworkID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbNetworkID");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbShowID");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_AlternateOrderingID");

                    b.HasIndex(new[] { "TmdbEpisodeGroupCollectionID", "TmdbShowID" }, "IX_TMDB_AlternateOrdering_TmdbEpisodeGroupCollectionID_TmdbShowID");

                    b.HasIndex(new[] { "TmdbShowID" }, "IX_TMDB_AlternateOrdering_TmdbShowID");

                    b.HasIndex(new[] { "TmdbEpisodeGroupCollectionID" }, "UIX_TMDB_AlternateOrdering_TmdbEpisodeGroupCollectionID")
                        .IsUnique();

                    b.ToTable("TMDB_AlternateOrdering", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_AlternateOrdering_Episode", b =>
                {
                    b.Property<int>("TMDB_AlternateOrdering_EpisodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_AlternateOrdering_EpisodeID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbEpisodeGroupCollectionID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TmdbEpisodeGroupCollectionID");

                    b.Property<string>("TmdbEpisodeGroupID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TmdbEpisodeGroupID");

                    b.Property<int>("TmdbEpisodeID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbEpisodeID");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbShowID");

                    b.HasKey("TMDB_AlternateOrdering_EpisodeID");

                    b.HasIndex("TmdbEpisodeGroupCollectionID");

                    b.HasIndex("TmdbEpisodeID");

                    b.HasIndex("TmdbShowID");

                    b.ToTable("TMDB_AlternateOrdering_Episode", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_AlternateOrdering_Season", b =>
                {
                    b.Property<int>("TMDB_AlternateOrdering_SeasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_AlternateOrdering_SeasonID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HiddenEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbEpisodeGroupCollectionID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TmdbEpisodeGroupCollectionID");

                    b.Property<string>("TmdbEpisodeGroupID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TmdbEpisodeGroupID");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbShowID");

                    b.HasKey("TMDB_AlternateOrdering_SeasonID");

                    b.HasIndex(new[] { "TmdbEpisodeGroupCollectionID" }, "IX_TMDB_AlternateOrdering_Season_TmdbEpisodeGroupCollectionID");

                    b.HasIndex(new[] { "TmdbShowID" }, "IX_TMDB_AlternateOrdering_Season_TmdbShowID");

                    b.HasIndex(new[] { "TmdbEpisodeGroupID" }, "UIX_TMDB_AlternateOrdering_Season_TmdbEpisodeGroupID")
                        .IsUnique();

                    b.ToTable("TMDB_AlternateOrdering_Season", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Collection", b =>
                {
                    b.Property<int>("TMDB_CollectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_CollectionID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("EnglishOverview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int>("MovieCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbCollectionID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbCollectionID");

                    b.HasKey("TMDB_CollectionID");

                    b.HasIndex(new[] { "TMDB_CollectionID" }, "UIX_TMDB_Collection_TmdbCollectionID")
                        .IsUnique();

                    b.ToTable("TMDB_Collection", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Collection_Movie", b =>
                {
                    b.Property<int>("TMDB_Collection_MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_Collection_MovieID");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbCollectionID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbCollectionID");

                    b.Property<int>("TmdbMovieID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbMovieID");

                    b.HasKey("TMDB_Collection_MovieID");

                    b.HasIndex(new[] { "TmdbCollectionID" }, "IX_TMDB_Collection_Movie_TmdbCollectionID");

                    b.HasIndex(new[] { "TmdbMovieID" }, "IX_TMDB_Collection_Movie_TmdbMovieID");

                    b.ToTable("TMDB_Collection_Movie", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Company", b =>
                {
                    b.Property<int>("TMDB_CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_CompanyID");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbCompanyID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbCompanyID");

                    b.HasKey("TMDB_CompanyID");

                    b.HasIndex(new[] { "TMDB_CompanyID" }, "IX_TMDB_Company_TmdbCompanyID");

                    b.ToTable("TMDB_Company", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Company_Entity", b =>
                {
                    b.Property<int>("TMDB_Company_EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_Company_EntityID");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleasedAt")
                        .HasColumnType("DATE");

                    b.Property<int?>("TVShowTMDB_ShowID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbCompanyID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbCompanyID");

                    b.Property<int>("TmdbEntityID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbEntityID");

                    b.Property<int>("TmdbEntityType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_Company_EntityID");

                    b.HasIndex("TVShowTMDB_ShowID");

                    b.HasIndex("TmdbEntityID");

                    b.HasIndex(new[] { "TmdbCompanyID" }, "IX_TMDB_Company_Entity_TmdbCompanyID");

                    b.HasIndex(new[] { "TmdbEntityType", "TmdbEntityID" }, "IX_TMDB_Company_Entity_TmdbEntityType_TmdbEntityID");

                    b.ToTable("TMDB_Company_Entity", (string)null);

                    b.HasDiscriminator<int>("TmdbEntityType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Episode", b =>
                {
                    b.Property<int>("TMDB_EpisodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_EpisodeID");

                    b.Property<string>("AiredAt")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("EnglishOverview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonTMDB_SeasonID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShowTMDB_ShowID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NULL");

                    b.Property<int>("TmdbEpisodeID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbEpisodeID");

                    b.Property<int>("TmdbSeasonID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbSeasonID");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbShowID");

                    b.Property<int?>("TvdbEpisodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TvdbEpisodeID")
                        .HasDefaultValueSql("NULL");

                    b.Property<double>("UserRating")
                        .HasColumnType("REAL");

                    b.Property<int>("UserVotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_EpisodeID");

                    b.HasIndex("SeasonTMDB_SeasonID");

                    b.HasIndex("ShowTMDB_ShowID");

                    b.HasIndex(new[] { "TmdbSeasonID" }, "IX_TMDB_Episode_TmdbSeasonID");

                    b.HasIndex(new[] { "TmdbShowID" }, "IX_TMDB_Episode_TmdbShowID");

                    b.HasIndex(new[] { "TMDB_EpisodeID" }, "UIX_TMDB_Episode_TmdbEpisodeID")
                        .IsUnique();

                    b.ToTable("TMDB_Episode", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Episode_Cast", b =>
                {
                    b.Property<int>("TMDB_Episode_CastID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_Episode_CastID");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGuestRole")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TMDB_EpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbCreditID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TmdbCreditID");

                    b.Property<int>("TmdbEpisodeID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbEpisodeID");

                    b.Property<int>("TmdbPersonID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbPersonID");

                    b.Property<int>("TmdbSeasonID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbSeasonID");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbShowID");

                    b.HasKey("TMDB_Episode_CastID");

                    b.HasIndex("TMDB_EpisodeID");

                    b.HasIndex(new[] { "TmdbEpisodeID" }, "IX_TMDB_Episode_Cast_TmdbEpisodeID");

                    b.HasIndex(new[] { "TmdbPersonID" }, "IX_TMDB_Episode_Cast_TmdbPersonID");

                    b.HasIndex(new[] { "TmdbSeasonID" }, "IX_TMDB_Episode_Cast_TmdbSeasonID");

                    b.HasIndex(new[] { "TmdbShowID" }, "IX_TMDB_Episode_Cast_TmdbShowID");

                    b.ToTable("TMDB_Episode_Cast", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Episode_Crew", b =>
                {
                    b.Property<int>("TMDB_Episode_CrewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_Episode_CrewID");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TMDB_EpisodeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbCreditID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TmdbCreditID");

                    b.Property<int>("TmdbEpisodeID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbEpisodeID");

                    b.Property<int>("TmdbPersonID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbPersonID");

                    b.Property<int>("TmdbSeasonID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbSeasonID");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbShowID");

                    b.HasKey("TMDB_Episode_CrewID");

                    b.HasIndex("TMDB_EpisodeID");

                    b.HasIndex(new[] { "TmdbEpisodeID" }, "IX_TMDB_Episode_Crew_TmdbEpisodeID");

                    b.HasIndex(new[] { "TmdbPersonID" }, "IX_TMDB_Episode_Crew_TmdbPersonID");

                    b.HasIndex(new[] { "TmdbSeasonID" }, "IX_TMDB_Episode_Crew_TmdbSeasonID");

                    b.HasIndex(new[] { "TmdbShowID" }, "IX_TMDB_Episode_Crew_TmdbShowID");

                    b.ToTable("TMDB_Episode_Crew", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image", b =>
                {
                    b.Property<int>("TMDB_ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_ImageID");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("UserRating")
                        .HasColumnType("REAL");

                    b.Property<int>("UserVotes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_ImageID");

                    b.ToTable("TMDB_Image", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Entity", b =>
                {
                    b.Property<int>("TMDB_Image_EntityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_Image_EntityID");

                    b.Property<int>("ImageType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleasedAt")
                        .HasColumnType("DATE");

                    b.Property<string>("RemoteFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbEntityID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbEntityID");

                    b.Property<int>("TmdbEntityType")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_Image_EntityID");

                    b.HasIndex("RemoteFileName");

                    b.ToTable("TMDB_Image_Entity", (string)null);

                    b.HasDiscriminator<int>("TmdbEntityType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Movie", b =>
                {
                    b.Property<int>("TMDB_MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_MovieID");

                    b.Property<string>("BackdropPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("ContentRatings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("EnglishOverview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbMovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ImdbMovieID")
                        .HasDefaultValueSql("NULL");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVideo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NULL");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("OriginalLanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("ProductionCountries")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("ReleasedAt")
                        .HasColumnType("DATE");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TmdbCollectionID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbCollectionID");

                    b.Property<int>("TmdbMovieID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbMovieID");

                    b.Property<double>("UserRating")
                        .HasColumnType("REAL");

                    b.Property<int>("UserVotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_MovieID");

                    b.HasIndex(new[] { "TmdbCollectionID" }, "IX_TMDB_Movie_TmdbCollectionID");

                    b.HasIndex(new[] { "TmdbMovieID" }, "UIX_TMDB_Movie_TmdbMovieID")
                        .IsUnique();

                    b.ToTable("TMDB_Movie", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Movie_Cast", b =>
                {
                    b.Property<int>("TMDB_Movie_CastID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_Movie_CastID");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TMDB_MovieID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbCreditID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TmdbCreditID");

                    b.Property<int>("TmdbMovieID")
                        .HasColumnType("INT")
                        .HasColumnName("TmdbMovieID");

                    b.Property<int>("TmdbPersonID")
                        .HasColumnType("INT")
                        .HasColumnName("TmdbPersonID");

                    b.HasKey("TMDB_Movie_CastID");

                    b.HasIndex("TMDB_MovieID");

                    b.HasIndex(new[] { "TmdbMovieID" }, "IX_TMDB_Movie_Cast_TmdbMovieID");

                    b.HasIndex(new[] { "TmdbPersonID" }, "IX_TMDB_Movie_Cast_TmdbPersonID");

                    b.ToTable("TMDB_Movie_Cast", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Movie_Crew", b =>
                {
                    b.Property<int>("TMDB_Movie_CrewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_Movie_CrewID");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TMDB_MovieID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TmdbCreditID")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TmdbCreditID");

                    b.Property<int>("TmdbMovieID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbMovieID");

                    b.Property<int>("TmdbPersonID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbPersonID");

                    b.HasKey("TMDB_Movie_CrewID");

                    b.HasIndex("TMDB_MovieID");

                    b.HasIndex(new[] { "TmdbMovieID" }, "IX_TMDB_Movie_Crew_TmdbMovieID");

                    b.HasIndex(new[] { "TmdbPersonID" }, "IX_TMDB_Movie_Crew_TmdbPersonID");

                    b.ToTable("TMDB_Movie_Crew", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Network", b =>
                {
                    b.Property<int>("TMDB_NetworkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_NetworkID");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbNetworkID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbNetworkID");

                    b.HasKey("TMDB_NetworkID");

                    b.HasIndex(new[] { "TmdbNetworkID" }, "UIX_TMDB_Network_TmdbNetworkID")
                        .IsUnique();

                    b.ToTable("TMDB_Network", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Overview", b =>
                {
                    b.Property<int>("TMDB_OverviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_OverviewID");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ParentID");

                    b.Property<int>("ParentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TMDB_OverviewID");

                    b.HasIndex("ParentID");

                    b.HasIndex(new[] { "ParentType", "ParentID" }, "IX_TMDB_Overview");

                    b.ToTable("TMDB_Overview", (string)null);

                    b.HasDiscriminator<int>("ParentType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Person", b =>
                {
                    b.Property<int>("TMDB_PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_PersonID");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthDay")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("DeathDay")
                        .HasColumnType("DATE");

                    b.Property<string>("EnglishBiography")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbPersonID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbPersonID");

                    b.HasKey("TMDB_PersonID");

                    b.HasIndex(new[] { "TmdbPersonID" }, "IX_TMDB_Person_TmdbPersonID");

                    b.ToTable("TMDB_Person", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Season", b =>
                {
                    b.Property<int>("TMDB_SeasonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_SeasonID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("EnglishOverview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HiddenEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NULL");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ShowTMDB_ShowID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbSeasonID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbSeasonID");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbShowID");

                    b.HasKey("TMDB_SeasonID");

                    b.HasIndex("ShowTMDB_ShowID");

                    b.HasIndex(new[] { "TmdbShowID" }, "IX_TMDB_Season_TmdbShowID");

                    b.HasIndex(new[] { "TmdbSeasonID" }, "UIX_TMDB_Season_TmdbSeasonID")
                        .IsUnique();

                    b.ToTable("TMDB_Season", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Show", b =>
                {
                    b.Property<int>("TMDB_ShowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_ShowID");

                    b.Property<int>("AlternateOrderingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackdropPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("ContentRatings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("EnglishOverview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstAiredAt")
                        .HasColumnType("DATE");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HiddenEpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("LastAiredAt")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("OriginalLanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("PreferredAlternateOrderingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("PreferredAlternateOrderingID")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("ProductionCountries")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NULL");

                    b.Property<int>("SeasonCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbShowID");

                    b.Property<int?>("TvdbShowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TvdbShowID")
                        .HasDefaultValueSql("NULL");

                    b.Property<double>("UserRating")
                        .HasColumnType("REAL");

                    b.Property<int>("UserVotes")
                        .HasColumnType("INTEGER");

                    b.HasKey("TMDB_ShowID");

                    b.HasIndex(new[] { "TmdbShowID" }, "UIX_TMDB_Show_TmdbShowID")
                        .IsUnique();

                    b.ToTable("TMDB_Show", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Show_Network", b =>
                {
                    b.Property<int>("TMDB_Show_NetworkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_Show_NetworkID");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmdbNetworkID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbNetworkID");

                    b.Property<int>("TmdbShowID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TmdbShowID");

                    b.HasKey("TMDB_Show_NetworkID");

                    b.HasIndex("TmdbNetworkID");

                    b.HasIndex("TmdbShowID");

                    b.ToTable("Tmdb_Show_Network", (string)null);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Title", b =>
                {
                    b.Property<int>("TMDB_TitleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TMDB_TitleID");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ParentID");

                    b.Property<int>("ParentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TMDB_TitleID");

                    b.HasIndex("ParentID");

                    b.HasIndex(new[] { "ParentType", "ParentID" }, "IX_TMDB_Title");

                    b.ToTable("TMDB_Title", (string)null);

                    b.HasDiscriminator<int>("ParentType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Company_Movie", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Company_Entity");

                    b.Property<int?>("TMDB_MovieID")
                        .HasColumnType("INTEGER");

                    b.HasIndex("TMDB_MovieID");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Company_Show", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Company_Entity");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Character", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Image_Entity");

                    b.HasDiscriminator().HasValue(512);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Collection", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Image_Entity");

                    b.HasIndex("TmdbEntityID");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Company", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Image_Entity");

                    b.HasIndex("TmdbEntityID");

                    b.HasDiscriminator().HasValue(32);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Episode", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Image_Entity");

                    b.HasDiscriminator().HasValue(16);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Movie", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Image_Entity");

                    b.HasIndex("TmdbEntityID");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Network", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Image_Entity");

                    b.HasDiscriminator().HasValue(128);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Person", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Image_Entity");

                    b.HasIndex("TmdbEntityID");

                    b.HasDiscriminator().HasValue(256);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Season", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Image_Entity");

                    b.HasDiscriminator().HasValue(8);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Studio", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Image_Entity");

                    b.HasDiscriminator().HasValue(64);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_TVShow", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Image_Entity");

                    b.HasIndex("TmdbEntityID");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Overview_Collection", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Overview");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Overview_Episode", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Overview");

                    b.HasDiscriminator().HasValue(16);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Overview_Movie", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Overview");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Overview_Person", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Overview");

                    b.HasDiscriminator().HasValue(256);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Overview_Season", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Overview");

                    b.HasDiscriminator().HasValue(8);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Overview_TVShow", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Overview");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Title_Collection", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Title");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Title_Episode", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Title");

                    b.HasDiscriminator().HasValue(16);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Title_Movie", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Title");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Title_Season", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Title");

                    b.HasDiscriminator().HasValue(8);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Title_TVShow", b =>
                {
                    b.HasBaseType("Shoko.Server.Models.TMDB.TMDB_Title");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_AlternateOrdering", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Show", "Show")
                        .WithMany("AlternateOrderings")
                        .HasForeignKey("TmdbShowID")
                        .HasPrincipalKey("TmdbShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_AlternateOrdering_Episode", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_AlternateOrdering", "TmdbAlternateOrdering")
                        .WithMany("AlternateOrderingEpisodes")
                        .HasForeignKey("TmdbEpisodeGroupCollectionID")
                        .HasPrincipalKey("TmdbEpisodeGroupCollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_AlternateOrdering_Season", "TmdbAlternateOrderingSeason")
                        .WithMany("TmdbAlternateOrderingEpisodes")
                        .HasForeignKey("TmdbEpisodeGroupCollectionID")
                        .HasPrincipalKey("TmdbEpisodeGroupCollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Episode", "TmdbEpisode")
                        .WithMany("TmdbAlternateOrderingEpisodes")
                        .HasForeignKey("TmdbEpisodeID")
                        .HasPrincipalKey("TmdbEpisodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Show", "TmdbShow")
                        .WithMany()
                        .HasForeignKey("TmdbShowID")
                        .HasPrincipalKey("TmdbShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TmdbAlternateOrdering");

                    b.Navigation("TmdbAlternateOrderingSeason");

                    b.Navigation("TmdbEpisode");

                    b.Navigation("TmdbShow");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_AlternateOrdering_Season", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_AlternateOrdering", "TmdbAlternateOrdering")
                        .WithMany("AlternateOrderingSeasons")
                        .HasForeignKey("TmdbEpisodeGroupCollectionID")
                        .HasPrincipalKey("TmdbEpisodeGroupCollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Show", "TmdbShow")
                        .WithMany()
                        .HasForeignKey("TmdbShowID")
                        .HasPrincipalKey("TmdbShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TmdbAlternateOrdering");

                    b.Navigation("TmdbShow");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Company_Entity", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Show", "TVShow")
                        .WithMany()
                        .HasForeignKey("TVShowTMDB_ShowID");

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Company", "Company")
                        .WithMany("XRefs")
                        .HasForeignKey("TmdbCompanyID")
                        .HasPrincipalKey("TmdbCompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("TmdbEntityID")
                        .HasPrincipalKey("TmdbMovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Movie");

                    b.Navigation("TVShow");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Episode", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonTMDB_SeasonID");

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowTMDB_ShowID");

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Season", null)
                        .WithMany("Episodes")
                        .HasForeignKey("TmdbSeasonID")
                        .HasPrincipalKey("TmdbSeasonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Show", null)
                        .WithMany("Episodes")
                        .HasForeignKey("TmdbSeasonID")
                        .HasPrincipalKey("TmdbShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Episode_Cast", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Episode", null)
                        .WithMany("Cast")
                        .HasForeignKey("TMDB_EpisodeID");

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("TmdbEpisodeID")
                        .HasPrincipalKey("TmdbEpisodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Person", "Person")
                        .WithMany("EpisodeRoles")
                        .HasForeignKey("TmdbPersonID")
                        .HasPrincipalKey("TmdbPersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Episode_Crew", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Episode", null)
                        .WithMany("Crew")
                        .HasForeignKey("TMDB_EpisodeID");

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("TmdbEpisodeID")
                        .HasPrincipalKey("TmdbEpisodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Person", "Person")
                        .WithMany("EpisodeCrew")
                        .HasForeignKey("TmdbPersonID")
                        .HasPrincipalKey("TmdbPersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Entity", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Image", "Image")
                        .WithMany()
                        .HasForeignKey("RemoteFileName")
                        .HasPrincipalKey("RemoteFileName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Movie", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Collection", "TmdbCollection")
                        .WithMany("Movies")
                        .HasForeignKey("TmdbCollectionID")
                        .HasPrincipalKey("TmdbCollectionID");

                    b.Navigation("TmdbCollection");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Movie_Cast", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Movie", null)
                        .WithMany("Cast")
                        .HasForeignKey("TMDB_MovieID");

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("TmdbMovieID")
                        .HasPrincipalKey("TmdbMovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Person", "Person")
                        .WithMany("MovieRoles")
                        .HasForeignKey("TmdbPersonID")
                        .HasPrincipalKey("TmdbPersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Movie_Crew", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Movie", null)
                        .WithMany("Crew")
                        .HasForeignKey("TMDB_MovieID");

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("TmdbMovieID")
                        .HasPrincipalKey("TmdbMovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Person", "Person")
                        .WithMany("MovieCrew")
                        .HasForeignKey("TmdbPersonID")
                        .HasPrincipalKey("TmdbPersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Overview", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Collection", null)
                        .WithMany("Overviews")
                        .HasForeignKey("ParentID")
                        .HasPrincipalKey("TmdbCollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Movie", null)
                        .WithMany("AllOverviews")
                        .HasForeignKey("ParentID")
                        .HasPrincipalKey("TmdbMovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Person", null)
                        .WithMany("AllBiographies")
                        .HasForeignKey("ParentID")
                        .HasPrincipalKey("TmdbPersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Season", null)
                        .WithMany("AllOverviews")
                        .HasForeignKey("ParentID")
                        .HasPrincipalKey("TmdbSeasonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Show", null)
                        .WithMany("AllOverviews")
                        .HasForeignKey("ParentID")
                        .HasPrincipalKey("TmdbShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Season", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowTMDB_ShowID");

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Show", null)
                        .WithMany("Seasons")
                        .HasForeignKey("TmdbShowID")
                        .HasPrincipalKey("TmdbShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Show_Network", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Network", "Network")
                        .WithMany("NetworkXRefs")
                        .HasForeignKey("TmdbNetworkID")
                        .HasPrincipalKey("TmdbNetworkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Show", "Show")
                        .WithMany("NetworkXRefs")
                        .HasForeignKey("TmdbShowID")
                        .HasPrincipalKey("TmdbShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Title", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Collection", null)
                        .WithMany("Titles")
                        .HasForeignKey("ParentID")
                        .HasPrincipalKey("TmdbCollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Movie", null)
                        .WithMany("AllTitles")
                        .HasForeignKey("ParentID")
                        .HasPrincipalKey("TmdbMovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Season", null)
                        .WithMany("AllTitles")
                        .HasForeignKey("ParentID")
                        .HasPrincipalKey("TmdbSeasonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Show", null)
                        .WithMany("AllTitles")
                        .HasForeignKey("ParentID")
                        .HasPrincipalKey("TmdbShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Company_Movie", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Movie", null)
                        .WithMany("CompanyXRefs")
                        .HasForeignKey("TMDB_MovieID");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Company_Show", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Show", null)
                        .WithMany("CompanyXRefs")
                        .HasForeignKey("TmdbEntityID")
                        .HasPrincipalKey("TmdbShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Collection", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Collection", null)
                        .WithMany("ImageXRefs")
                        .HasForeignKey("TmdbEntityID")
                        .HasPrincipalKey("TmdbCollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Episode", null)
                        .WithMany("ImageXRefs")
                        .HasForeignKey("TmdbEntityID")
                        .HasPrincipalKey("TmdbEpisodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Company", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Company", null)
                        .WithMany("ImageXRefs")
                        .HasForeignKey("TmdbEntityID")
                        .HasPrincipalKey("TmdbCompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Movie", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Movie", null)
                        .WithMany("ImageXRefs")
                        .HasForeignKey("TmdbEntityID")
                        .HasPrincipalKey("TmdbMovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Season", null)
                        .WithMany("ImageXRefs")
                        .HasForeignKey("TmdbEntityID")
                        .HasPrincipalKey("TmdbSeasonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_Person", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Person", null)
                        .WithMany("ImageXRefs")
                        .HasForeignKey("TmdbEntityID")
                        .HasPrincipalKey("TmdbPersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Image_TVShow", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Show", null)
                        .WithMany("ImageXRefs")
                        .HasForeignKey("TmdbEntityID")
                        .HasPrincipalKey("TmdbShowID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Overview_Episode", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Episode", null)
                        .WithMany("AllOverviews")
                        .HasForeignKey("ParentID")
                        .HasPrincipalKey("TmdbEpisodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Title_Episode", b =>
                {
                    b.HasOne("Shoko.Server.Models.TMDB.TMDB_Episode", null)
                        .WithMany("AllTitles")
                        .HasForeignKey("ParentID")
                        .HasPrincipalKey("TmdbEpisodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_AlternateOrdering", b =>
                {
                    b.Navigation("AlternateOrderingEpisodes");

                    b.Navigation("AlternateOrderingSeasons");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_AlternateOrdering_Season", b =>
                {
                    b.Navigation("TmdbAlternateOrderingEpisodes");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Collection", b =>
                {
                    b.Navigation("ImageXRefs");

                    b.Navigation("Movies");

                    b.Navigation("Overviews");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Company", b =>
                {
                    b.Navigation("ImageXRefs");

                    b.Navigation("XRefs");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Episode", b =>
                {
                    b.Navigation("AllOverviews");

                    b.Navigation("AllTitles");

                    b.Navigation("Cast");

                    b.Navigation("Crew");

                    b.Navigation("ImageXRefs");

                    b.Navigation("TmdbAlternateOrderingEpisodes");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Movie", b =>
                {
                    b.Navigation("AllOverviews");

                    b.Navigation("AllTitles");

                    b.Navigation("Cast");

                    b.Navigation("CompanyXRefs");

                    b.Navigation("Crew");

                    b.Navigation("ImageXRefs");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Network", b =>
                {
                    b.Navigation("NetworkXRefs");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Person", b =>
                {
                    b.Navigation("AllBiographies");

                    b.Navigation("EpisodeCrew");

                    b.Navigation("EpisodeRoles");

                    b.Navigation("ImageXRefs");

                    b.Navigation("MovieCrew");

                    b.Navigation("MovieRoles");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Season", b =>
                {
                    b.Navigation("AllOverviews");

                    b.Navigation("AllTitles");

                    b.Navigation("Episodes");

                    b.Navigation("ImageXRefs");
                });

            modelBuilder.Entity("Shoko.Server.Models.TMDB.TMDB_Show", b =>
                {
                    b.Navigation("AllOverviews");

                    b.Navigation("AllTitles");

                    b.Navigation("AlternateOrderings");

                    b.Navigation("CompanyXRefs");

                    b.Navigation("Episodes");

                    b.Navigation("ImageXRefs");

                    b.Navigation("NetworkXRefs");

                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
