name: Publish to Docker Hub

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  
jobs:

  daily:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        ref: v4.1.0-arm
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/shokoserver:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/shokoserver:v4.1.0
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REPO }}:daily
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    # - name: Push daily to Docker Hub
    #   run: docker push ${{ secrets.DOCKER_REPO }}:daily
