name: Publish to Docker Hub (Manual)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git Reference
        default: master
        required: true
      tag:
        description: Docker Tag
        default: daily
        required: true
      release:
        description: Release Channel
        default: dev
        required: true
      version:
        description: Application Version
        default: "0.0.0.0"
        required: true

jobs:
  webui:
    runs-on: ubuntu-latest

    name: Download Web UI

    steps:
      - name: Get Web UI Release URL
        id: webui_release
        run: |
          if [ "${{ github.event.inputs.release }}" = "stable" ]; then
            channel=Stable
          else
            channel=Dev
          fi
          download_url=$(curl -s https://raw.githubusercontent.com/ShokoAnime/Shoko-WebUI/metadata/manifest.json | jq -r ".${channel}[0].downloadUrl")
          echo "download_url=${download_url}" >> "$GITHUB_OUTPUT"

      - name: Download and Extract Web UI
        run: |
          mkdir -p webui
          curl -L "${{ steps.webui_release.outputs.download_url }}" -o webui/latest.zip
          cd webui
          unzip -o latest.zip
          rm latest.zip

      - name: Upload Web UI Artifact
        uses: actions/upload-artifact@v7
        with:
          name: webui
          path: webui/
          retention-days: 1

  cli:
    runs-on: ubuntu-latest

    name: Build CLI

    needs:
      - webui

    strategy:
      matrix:
        include:
          - rid: linux-x64
            arch: amd64
          - rid: linux-arm64
            arch: arm64

    steps:
      - name: Checkout "${{ github.event.inputs.ref }}"
        uses: actions/checkout@v7
        with:
          ref: "${{ github.event.inputs.ref }}"
          fetch-depth: 0

      - name: Download Web UI
        uses: actions/download-artifact@v8
        with:
          name: webui
          path: Shoko.Server/webui

      - name: Download Offline Importer
        run: |
          download_url=$(curl -s https://api.github.com/repos/revam/dotnet-shoko-plugin-offline-importer/releases/latest | jq -r '.assets[0].browser_download_url')
          mkdir -p Shoko.Server/plugins
          curl -L "${download_url}" -o Shoko.Server/plugins/latest.zip
          cd Shoko.Server/plugins && unzip -o latest.zip && rm latest.zip

      - name: Replace Sentry DSN and other keys
        shell: pwsh
        run: |
          ./.github/workflows/ReplaceSentryDSN.ps1 -dsn ${{ secrets.SENTRY_DSN }}
          ./.github/workflows/ReplaceTmdbApiKey.ps1 -apiKey ${{ secrets.TMDB_API }}
          ./.github/workflows/ReplaceAVD3URL.ps1 -url ${{ secrets.AVD3_URL }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: arm64
        if: ${{ matrix.rid == 'linux-arm64' }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Cache NuGet packages
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: nuget-${{ matrix.rid }}-${{ hashFiles('**/*.csproj', '**/*.sln') }}
          restore-keys: |
            nuget-${{ matrix.rid }}-

      - name: Publish CLI
        run: |
          dotnet publish -c Release -r ${{ matrix.rid }} -f net10.0 --no-self-contained Shoko.CLI \
            /p:Version="${{ github.event.inputs.version }}" \
            /p:InformationalVersion="\"channel=${{ github.event.inputs.release }},commit=${{ github.sha }},tag=${{ github.event.inputs.tag }},date=$(git log -1 --format='%aI'),\""

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v7
        with:
          name: Shoko.CLI_Framework_${{ matrix.rid }}
          path: Shoko.Server/bin/Release/net10.0/${{ matrix.rid }}/publish/
          retention-days: 1

  docker-manual-build:
    name: Build and push Docker image

    needs:
      - cli

    runs-on: ubuntu-latest

    steps:
      - name: Checkout "${{ github.event.inputs.ref }}"
        uses: actions/checkout@v7
        with:
          ref: "${{ github.event.inputs.ref }}"

      - name: Download amd64 CLI artifact
        uses: actions/download-artifact@v8
        with:
          name: Shoko.CLI_Framework_linux-x64
          path: publish/amd64/

      - name: Download arm64 CLI artifact
        uses: actions/download-artifact@v8
        with:
          name: Shoko.CLI_Framework_linux-arm64
          path: publish/arm64/

      - name: Retrieve Commit Date
        id: version
        run: echo "COMMIT_DATE=$(git log -1 --format='%aI')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          provenance: true
          tags: |
            ghcr.io/${{ secrets.DOCKER_REPO }}:${{ github.event.inputs.tag }}
            ${{ secrets.DOCKER_REPO }}:${{ github.event.inputs.tag }}
          cache-from: type=registry,ref=ghcr.io/${{ secrets.DOCKER_REPO }}:cache-buildkit
          cache-to: type=registry,ref=ghcr.io/${{ secrets.DOCKER_REPO }}:cache-buildkit,mode=max,image-manifest=true,oci-mediatypes=true
