name: Build Tray Service (Manual)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git reference for what to push
        default: master
        required: true
      tag:
        description: filename
        default: shokoserver.zip
        required: true

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet: [ '6.x' ]

    name: Shoko Tray Service build

    steps:
      - name: Pull
        uses: actions/checkout@master
        with:
          submodules: recursive
          ref: "${{ github.event.inputs.ref }}"
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet publish -c Release -r win10-x64 --self-contained true -f net6.0-windows Shoko.TrayService
      - uses: actions/upload-artifact@v2
        with:
          name: Shoko.TrayService
          path: Shoko.Server/bin/Release/net6.0-windows/win10-x64/publish/
      - name: Archive Release
        shell: powershell
        run: Compress-Archive .\\Shoko.Server\\bin\\Release\\net6.0-windows\\win10-x64\\publish .\\ShokoServer.zip
      - name: Upload Daily to shokoanime.com
        shell: powershell
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
        run : .\\.github\\workflows\\UploadArchive.ps1 -filename "${{ github.event.inputs.tag }}"
